### ISSUE TITLE
Can you post a few examples on how to transfer onclick values back into R for shiny applications.Thank you for this package.

### ISSUE THREAD

**Issue by amrutainc01** [davidgohel/ggiraph#101]

**Comment by amrutainc01** [comment]
Created a work around for not using the search_value.js in shiny. 


server<-function(input,output,session){
output$plot<-renderggiraph{
**dat.gg$oc<-"var z=this.getAttribute(\"data-id\");Shiny.onInputChange(\"clickvalue\",z);"** 
p=ggplot() + 
  geom_polygon_interactive(data = dat.gg, aes(x=dat.gg$x, y=dat.gg$y,tooltip =dat.gg$text, size=5,   data_id = dat.gg$Measure, **onclick=oc**),fill=dat.gg$Color, alpha=dat.gg$Transparency, colour = "black",size = 1, show.legend = FALSE)
}
output$Text<-renderText(paste0(**input$clickvalue**))


Thank you for this interactive package it greatly compliments the ggplots.

**Comment by davidgohel** [comment]
Thanks,

You can have a look at https://davidgohel.github.io/ggiraph/articles/offcran/using_ggiraph.html#selections

There are also examples in that package about how to get selected values in shiny: https://davidgohel.github.io/ggiraph/articles/offcran/using_ggiraph.html#examples

So in your example, the value(s) are accessible in variable `input$plot_selected`.

Sorry, I don't know what you are referring to when mentioning `search_value.js`.

**Comment by davidgohel** [comment]
I am closing that issue, please let me know if I should reopen it.

**Comment by amrutainc01** [comment]
Thank you David for this wonderful package.
