### ISSUE TITLE
Feature request: geom_sf_interactive

### ISSUE THREAD

**Issue by d-qn** [davidgohel/ggiraph#102]
Two arguments for it. 

1. Simple features, [sf](https://cran.r-project.org/web/packages/sf/index.html), is emerging as the standard format for spatial data. 
1. ggplot2 is great for geospatial mapping and recently introduced [geom_sf](http://ggplot2.tidyverse.org/reference/ggsf.html) in the dev version to support sf. 

So, a geom_sf_interactive would be awesome to easily create interactive geospatial maps

**Comment by davidgohel** [comment]
hi @d-qn 

Sure. 

(I already have prepared `rvg` for that ;) and) Next week I will probably have time for `geom_sf_interactive`. 

David

**Comment by davidgohel** [comment]
@d-qn I have implemented `geom_sf_interactive` :) 

This version need github version of ggplot2 to work. ggplot2 new version should be on cran end of this month, I will then send to CRAN that ggiraph version.
