### ISSUE TITLE
Return click coordinates

### ISSUE THREAD

**Issue by jshukle** [davidgohel/ggiraph#103]
I am interested in using ggiraph within a shiny app that I am developing. When using geom_line_interactive I can return the id of a clicked line as an input; however, I would also like the plot coordinates where the mouse click was made.

With a base R plot, ggplot, or even a plotly plot this is trivially accomplished within the UI output() function for the  relative plot type. Unfortunately, ggiraphOutput() lacks this functionality ... or maybe I am just missing it.

Is it possible to return the mouse click coordinates within a shiny app as an input using ggiraph?

**Comment by davidgohel** [comment]
Sorry for the delay. 

I think you want to get the *user* x and y values. This is unfortunately not possible. 

KR
David
