### ISSUE TITLE
Option to have a fixed tooltip position

### ISSUE THREAD

**Issue by d-qn** [davidgohel/ggiraph#105]
It would be nice to have the possibility to have a fixed position for tooltip, in addition to at the cursor position. It can be preferable on mobile device or to address cases where there is no space for the tooltip at the edges of the chart area.

**Comment by davidgohel** [comment]
thanks for the suggestion. I am not able to do it now but will do it later.

**Comment by davidgohel** [comment]
The new github version (>=0.5.0) has now new functions: `girafe`, `girafe_options` and few helper functions to help specify the animations you want. The code below is demonstrating how to set the tooltip at a fixed position:

```
library(ggplot2)

dataset <- mtcars
dataset$carname = row.names(mtcars)

gg_point = ggplot( 
    data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp,
                  tooltip = carname, data_id = carname) ) +
  geom_point_interactive() + theme_minimal()

x <- girafe(ggobj = gg_point)
x <- girafe_options(x = x, opts_tooltip(use_cursor_pos = FALSE, offx = 5, offy = 5) )
print(x)
```

I think `girafe()` will be easier to work with than `ggiraph()` when there will be a need to customize animations.

David
