### ISSUE TITLE
Problem with sizing (extra white space) in ggiraph shiny 

### ISSUE THREAD

**Issue by anapaularg** [davidgohel/ggiraph#106]
Hi,

I'm working on a shiny app which uses `ggiraph`. I'm trying to combine two donut plots (actually bar plots with polar coordinates). This is my code, which uses `plot_grid` to combine two ggplots using a personal function `grafico_donut` which uses `geom_bar_interactive`:

```
ggiraph(ggobj = plot_grid(
grafico_donut(filter(cuotas_prueba,GRUPO_CUOTA == "GAL_PREMIUM"), tamano = 10, unidad = "Gl "), 
grafico_donut(filter(cuotas_prueba,GRUPO_CUOTA == "GAL_SATINADO"), tamano = 10, unidad = "Gl "))) 
```

When I use only plot_grid I get the following image:

![img1](https://user-images.githubusercontent.com/10159306/44952877-f7edb400-ae4f-11e8-8e7e-df997e7415d5.PNG)

But after using `ggiraph `I get this:

![img2](https://user-images.githubusercontent.com/10159306/44952884-25d2f880-ae50-11e8-82e0-2c9f6bbefbc6.PNG)

Then later I'm using `ggiraphOutput `for a shiny app.

Changing width and size parameters in `ggiraphOutput `has no effect.

**Comment by cderv** [comment]
FWIW, the question has also been asked  on community.rstudio.com
https://community.rstudio.com/t/how-to-combine-two-plots-in-ggiraph-without-creating-extra-white-space/13589

**Comment by davidgohel** [comment]
@cderv thanks for the info :)

@anapaularg Arguments `width` and `height` of function `ggiraphOutput()` will define the size of the box containing the graphic. Arguments `width_svg` and `height_svg` define aspect ratio of the graphic (width/height) within the box defined by `ggiraphOutput()`.

Here you are comparing a plot with a plot within a responsive container. The plot is not produced by the javascript (as plotly, dygraphs, rbokeh) and when created, it does not know what are the values of width and height of the HTML container. It is created by an R graphical device and theses are corresponding to classical arguments of R devices {width, height} (i.e pdf, png, svg). You need to play with arguments width_svg and height_svg, it defines width and height and the aspect ratio of the graphic (width/height).

**Comment by anapaularg** [comment]
Thanks David, moving the `width_svg` and `height_svg` parameters seem to help but it appears there is a white bounding box within the box defined by `ggiraphOutput()`, is there a way to remove this?

**Comment by davidgohel** [comment]
This has to be done in your ggplot code
