### ISSUE TITLE
Error in geom_tile_interactive: aesthetics width & height not recognized 

### ISSUE THREAD

**Issue by sigmapi** [davidgohel/ggiraph#107]
Hi & thanks for your work!

There is a minor issue when using geom_tile_interactive:
I specify width & height as aesthetics or layer parameters and I get a warning:

> Warning: Ignoring unknown aesthetics: width, height

I looked at your code and indeed these attributes are not specified at function GeomInteractiveTile.

As you can see [in ggplot](https://github.com/tidyverse/ggplot2/blob/master/R/geom-tile.r) at GeomTile function, width and height are defined with default value NA:
```
default_aes = aes(fill = "grey20", colour = NA, size = 0.1, linetype = 1,
    alpha = NA, width = NA, height = NA),

```

So I think, GeomInteractiveTile should define the default_aes as:
```
default_aes = aes(fill = "grey20", colour = NA, size = 0.1, linetype = 1,
                     alpha = NA, width = NA, height = NA, tooltip = NULL, onclick = NULL, data_id = NULL),
```

**Comment by davidgohel** [comment]
cool, thanks for that, much appreciated!

I will update soon

**Comment by sigmapi** [comment]
That was fast, thanks!

Btw, I think it would be safe to remove them from extra_params now (in same function)
