### ISSUE TITLE
Tiny and non-responsive ggiraph in (latest) IE versions

### ISSUE THREAD

**Issue by d-qn** [davidgohel/ggiraph#108]
Sorry to come back on issue #74 (especially after the latest great ggiraph release), but I am bearer of bad news. It appears the latest ggiraph version (0.5.0.001) still doesn't fix IE issue with rendering ggiraph (it is all tiny and non-responsive). It seems to be the case for any IE versions, even the latest ones. 

<img width="1047" alt="capture d ecran 2018-09-11 a 17 12 53" src="https://user-images.githubusercontent.com/4863520/45369347-f6598400-b5e5-11e8-9e25-07aa1fcf56a9.png">

**Comment by davidgohel** [comment]
Just tested it, I can see your issue. But one of the ressource `styles.css` is not copied in your directory.

<img width="1117" alt="capture d ecran 2018-09-11 a 23 43 02" src="https://user-images.githubusercontent.com/4331618/45389541-82869e00-b61c-11e8-8aca-b3e9c4f860f8.png">

How did you produce that output? I cannot reproduce (tried with saveWidget, with rmd).

Can you have a look at that page and tell me if it work for you (it works for me on IE 11)? https://davidgohel.github.io/ggiraph/articles/offcran/examples.html

**Comment by davidgohel** [comment]
> great ggiraph release 

yes, I am very happy with this one, there are still few details to adjust and the issue 108 to solve, then it will be a great release ;)

**Comment by d-qn** [comment]
Thanks David :-) What a silly problem, I think I finally figured out the reason! First, here is the code I used to generate the ggiraph chart. A version with htmltools::save_html or as you suggested htmlwidgets::saveWidget, it turns out both options work regarding the css file you mention.

```
library(ggplot2)
library(ggiraph)
library(htmltools)
library(htmlwidgets)

dataset <- iris
gg_point <- ggplot(
  dataset, 
  aes(x = Sepal.Length, y = Petal.Width,color = Species)
) +
  geom_point_interactive(aes(data_id = 1:nrow(dataset)))
gg <- girafe(ggobj = gg_point, width = 1)

htmltools::save_html(gg, file = "test1.html", 
                     libdir = "lib1")
htmlwidgets::saveWidget(gg, file = "test2.html", 
                        libdir = "lib2", selfcontained = F)
```

Both versions work fine locally. But when uploaded on a server, the css file can never be found although it is present! This has to do somehow with all the dots in the folder structure (_ggiraphjs-0.1.0_) I believe. Somehow it is fine for js files but not for css. Because if rename manually the dots and hyphen of the folder name, it works: https://www.tdg.ch/extern/interactive_wch/tdg/test/lib3/ggiraphjs/styles.css

**Comment by davidgohel** [comment]
Thanks for your feedback.

I was however planning to embed the css in the javascript module and not in the htmlwidgets ressource dir. I will give a try today or tomorrow.

**Comment by d-qn** [comment]
Thank you David. I am still puzzled by it, but since it is working locally and not on a remote server maybe this is not a ggiraph bug per se

**Comment by davidgohel** [comment]
I am going to have a look soon. I'd like to send that version to CRAN after :)

**Comment by davidgohel** [comment]
Sorry I am going to close that one.  I don't think ggiraph is responsible for that and I have not being able to reproduce it.

And sorry, I am not going to embed the css in the bundle as I am not sure how it works ;)

**Comment by d-qn** [comment]
No worries, I totally understand. And I also don't think it is a ggiraph bug
