### ISSUE TITLE
Duplicate girafe output

### ISSUE THREAD

**Issue by sigmapi** [davidgohel/ggiraph#109]
I tried the latest version from github and I noticed an error:
Every time a girafeOutput is updated from shiny server, a new girafe_container_std container is appended inside the html-widget-output element. But the previous svg container is not removed, it stays there. As a result every time the server sends a new output, the containers keep on stacking one under the other.

I looked at the code and the function addSvg in ggiraphjs.js looks wrong:
1. It appends a new container, instead of replacing the contents of the parent.
2. It appends a new tooltip div to the body, without removing the tooltip div for the old svg.

**Comment by davidgohel** [comment]
Thanks, I did not test that case. This should be fix now. 

1 is intentional but 2 was a regression!

**Comment by sigmapi** [comment]
Seems that this works:
```
d3.select(".tooltip_" + d3.select("#" + this.containerid + " svg").attr("id")).remove()
d3.select("#" + this.containerid + " div.girafe_container_std").remove();

```

**Comment by davidgohel** [comment]
should be better now

**Comment by sigmapi** [comment]
Yes it works fine, thank you

**Comment by sigmapi** [comment]
Ok, one more thing I noticed related to that: 
A style element appended to document head for every tooltip. 
I guess that's trickier to remove, but it would be great to have a clean element tree
