### ISSUE TITLE
vertical facet titles are missing

### ISSUE THREAD

**Issue by RoJoRZ** [davidgohel/ggiraph#11]
Dear David,

Today I was exploring ggiraph and I really like it!. 
However I  think that I encountered a bug: in the vertical facet panels the titles are not shown. I created example code to show what happens. Hope that this helps to figure out what is going on?

All the best,
Ronny

`
## Loading packages
require(ggplot2)
require(ggiraph)
## creating dummy data
input <- data.frame(ID = letters[1:20],
                    chr = c(rep(1,5), rep(2,5), rep(3,5), rep(4,5)),
                    pos = rep(seq(1,4,1),5),
                    Refgroup = c(rep(1,5), rep(2,5), rep(3,5), rep(4,5)),
                    Position = rep(seq(1,4,1),5))
input$chr <- as.factor(input$chr)
input$Refgroup <- as.factor(input$Refgroup)

## creating the tooltips
data_id <- tolower(input$ID)
tooltip <- input$ID

## creating the plot
p <- ggplot(input, aes(x=pos, y=Position, tooltip = tooltip, data_id = data_id)) +
  geom_point_interactive(shape=1, alpha = 0.4) +
  facet_grid(Refgroup~chr) +
  xlab('Position1') +
  ylab('Position in Reference')

## have a look at the plot without ggiraph
print(p)
## plot the graph using ggiraph
ggiraph(code = {print(p)}, 
        width = 5, height = 5, 
        hover_css = "{fill:orange;r:6px;}")
### Note that the facet panels lost the titles at the right side
`

**Comment by davidgohel** [comment]
Hi 

This is related to #9

If reducing the text size, it will be ok:

    p <- ggplot(input, aes(x=pos, y=Position, tooltip = tooltip, data_id = data_id)) +
      geom_point_interactive(shape=1, alpha = 0.4) +
      facet_grid(Refgroup~chr) +
      xlab('Position1') +
      ylab('Position in Reference') +
      theme(strip.text = element_text(face = "bold", size = 6))

**Comment by RoJoRZ** [comment]
Hi,
Perfect, that solved my issue. I just noticed that it was indeed related to #9. I didn't connect the title to my issue, sorry for that. Thanks a lot for the solution!
