### ISSUE TITLE
Feature request - animation with ggiraph

### ISSUE THREAD

**Issue by d-qn** [davidgohel/ggiraph#110]
Just an idea, it might be completey silly, impossible or tons of work... It would be great to have the possibility to create animation from R with ggiraph, i.e. have transition between ggiraph charts via d3.js. Maybe the grammar for it on the R/ggplot2 side could be inspired by [gganimate](https://github.com/thomasp85/gganimate) but would leverage d3.js instead of interpolating from the R side.

**Comment by davidgohel** [comment]
yeahhh, it should be tested. I don't think that's impossible... Let's tag that issue as "improvement", I will try it later this year...

**Comment by davidgohel** [comment]
Hello
Almost 6 years later... I am closing this issue because it is unlikely that I or someone else will implement this feature
