### ISSUE TITLE
Svg sizing in Shiny

### ISSUE THREAD

**Issue by sigmapi** [davidgohel/ggiraph#111]
Currently, in function `adjustSize`, the svg width is always set to "100%", but height is set using the height specified in `girafeOutput` (also in function `resize`). 
This may result in a bit clumsy result in a shiny app, as the svg may have very small actual width but very large height.

For example I generate a plot with size 576x648 pixels. 
In shiny ui I define it as
`
girafeOutput("plot", width = "100%", height = "648px")
`
This looks fine in my pc browser, but in a mobile phone with a small screen size like 375x667, the svg has actual width 354px and height 648px. As the `aspectRatio` is set to `xMidYMin` there is a lot of blank space at the bottom part of the svg. Under the plot there are other elements, so the blank space does not look good. The actual height should be much smaller than 648px, exactly at 398.25px.

If I define it as
`
girafeOutput("plot", width = "100%", height = "100%")
`
which is exactly what I'd like, the svg has zero height.

So, I thought to fix this by modifying `adjustSize`:
- height is set to "100%" (as the width)
- max-height is set to svg's viewport height
- resize function does nothing

You can see it in [a branch I created: here](https://github.com/sigmapi/ggiraph/commit/fa5c6b761298439e1fe67cbdb84ac3b9f9430727)

The result is that the svg scales beautifully in all screens.

Of course I could set a custom CSS rule in my app like this:
```
    height: 100% !important;
    max-height: 648px !important;

```
But I'd like it to be dynamic. I don't want to hardcode the max-height.

Perhaps the correct way of doing this would be to have some sizing options like

```
opts_sizing(
  svg_auto_width = TRUE,
  svg_auto_height = TRUE,
  svg_limit_width = FALSE,
  svg_limit_height = TRUE
)
```
When `svg_auto_width/svg_auto_height` are TRUE, they're set to 100% and when they are FALSE they are set by the girafeOutput parameters (as the height currently).

When `svg_limit_width/svg_limit_height` are TRUE, the max-width/height is set by the svg's viewport width/height and when they are FALSE no max-width/max-height is set.

NOTE: I haven't included the compiled ggiraphjs.min.js in my branch/commit

**Comment by davidgohel** [comment]
Hi

Thanks for your comments.

I tried to make the documentation clearer on size :
https://github.com/davidgohel/ggiraph/commit/20d7972e634461c06413f2a96159722c676272ca#diff-7478aa390f956e0d8ef8601f57e784f6


This parameters are set as is intentionally. This allow a responsive behavior and compatibility with `IE < 11`. The preserveAspectRatio parameter is set 'xMidYMin' because I want the svg to be centered horizontally and top aligned vertically.

In your implementation, the shiny instructions (500px height) is no more respected and that is generating unwanted behavior (see below for an illustration, the title is now overlapping the svg instead of beeing positioned after the svg.

<img width="606" alt="capture d ecran 2018-09-24 a 09 16 27" src="https://user-images.githubusercontent.com/4331618/45940853-a57d5e80-bfdb-11e8-86ce-343c89a3ee8a.png">

I think you are after another behavior, resizing the svg but also rescaling the coordinate system to available space in HTML container (like plotly do). This is not possible because there is a fixed aspect ratio. That's how `ggiraph` is working and unfortunately can not be modified.

David

**Comment by sigmapi** [comment]
Hm, I can't reproduce the above result.
Note that `ggiraphjs.min.js` was not updated in my branch, I've updated it now.
I used the same example like this:
`
ggiraph::ggiraphOutput("plot", width = "100%", height = "100%")
`
With my patch I get this in a small screen:
![screenshot from 2018-09-24 10-22-33](https://user-images.githubusercontent.com/2146002/45942848-643d7c80-bfe4-11e8-8b6d-0d58d8c77b58.png)

Without it I get this:
![screenshot from 2018-09-24 10-22-11](https://user-images.githubusercontent.com/2146002/45942861-77504c80-bfe4-11e8-8668-abfd7aecfa98.png)

**Comment by sigmapi** [comment]
The empty space between the real svg elements and the "Selected states" is what I'm talking about.
As it has a fixed height this will happen.
With my patch the height is 100% and max-height is 576px, so it fits in any screen.

On the other hand I understand completely if you don't want to change the sizing behavior :)
Just wanted to share my finding.

**Comment by sigmapi** [comment]
Also on a side note, I've tried plotly but it has more issues than I have time to fix.
Your implementation is much more cleaner and I like it much more, so I've decided to use your package. :+1: 
I'll let you know when my app is published

**Comment by davidgohel** [comment]
I don't have much time for the subject right now but I will look deeper at your suggestions later. I agree removing bottom white space could be a good think in some cases.

BTW, what is the tool you are sing that let you emulate devices (as Iphone 6/7/8) rendering?

**Comment by sigmapi** [comment]
Ok sure. Basically I suggested the introduction of sizing options just for the purpose of being flexible and apply this alternative sizing only when we want it. Have the defaults to behave as it is now and being able to pass alternative sizing options for cases like the above. 
 
I'm using Chrome, Dev Tools, device toolbar/emulation.

**Comment by sigmapi** [comment]
If I have time I'll make a branch to implement these sizing options

**Comment by sigmapi** [comment]
Hi,

I've created a branch that introduces `opts_shiny_sizing`.
Check it out here: [opts_shiny_sizing](https://github.com/sigmapi/ggiraph/tree/opts_shiny_sizing)
There are 4 boolean parameters and the defaults, set the svg styles as there are now in main.
But they can be adjusted as we like, to reproduce alternative sizing.
Perhaps it needs more documentation and examples.

**Comment by davidgohel** [comment]
Hi @sigmapi, please send me a private email :)

David

**Comment by sigmapi** [comment]
Sure

**Comment by sigmapi** [comment]
Sent to ardata account

**Comment by davidgohel** [comment]
Hi, your work is integrated. Many thanks for your help :)

**Comment by sigmapi** [comment]
Thank you David!
