### ISSUE TITLE
Latest commits may break svgs with image data

### ISSUE THREAD

**Issue by sigmapi** [davidgohel/ggiraph#113]
Hi David,
I checked out latest master and there is an issue coming from function `updateSvgId`:

It does a very generic search/replace for "cl2" in the svg text. In a plot of mine I have an image element (grob with annotation_custom) which is base64 encoded in  the svg and it happens to contain the string "cl2". Naturally it breaks the image completely. 
A more explicit search/replace with a regex would be much better:
`
    updateSvgId(str){
        const replacement = '$1' + this.svgid + '$3';
        let regex = new RegExp('( id=")(svg_' + this.uid + ')(" )', 'g');
        let newsvg = str.replace(regex, replacement);
        regex = new RegExp('( id="cl| clip-path="url\\(#cl)(' + this.uid + ')(_)', 'g');
        newsvg = newsvg.replace(regex, replacement);
        return newsvg;
    }
`

On the other hand, why do this thing on the client side, it'll be much more expensive operation and may result in data corruption, to manipulate the svg like that.

Wouldn't it be better to generate a uuid on the server side and pass it directly to dsvg? 
There is the [uuid package](https://cran.r-project.org/web/packages/uuid/index.html) for that and I'm sure there will be ready functions for that.
That way there will be no need for replacement on the client side.

And something semi-relevant: All image grobs (with annotation_custom) refer to a clip path #cl1 which does not exist in the svg. Is that dsvg's fault?

**Comment by davidgohel** [comment]
Thanks.

The plan is to migrate dsvg from rvg to ggiraph and to adapt it more easily. I will not need any regexp in this case. 

> All image grobs (with annotation_custom) refer to a clip path #cl1 which does not exist in the svg. Is that dsvg's fault?

Could you open an issue with a reproducible example?

**Comment by davidgohel** [comment]
You can try the version here: https://github.com/davidgohel/ggiraph/tree/dsvg

It now requires a compiler as `dsvg` has migrated in this package.

**Comment by sigmapi** [comment]
Thank you, that's awesome! Works like a charm and it solves #114 too!

One minor detail is that there is an extra single quote char and a space after the opening of `<g>` element. I traced it at dsvg.cpp, line 501:
`
  fputs("><g>' ", svgd->file);
`

**Comment by davidgohel** [comment]
thanks again! (just corrected the `' `).
