### ISSUE TITLE
SVG Image elements refer to non-existent clip path element

### ISSUE THREAD

**Issue by sigmapi** [davidgohel/ggiraph#114]
When a plot contains image grobs (added via `rasterGrob` and `annotation_custom`), in the output svg they are inserted as image elements and they have the attribute `clip-path="url(#cl1)"`.
The issue is that there is no clip-path definition with that id. Perhaps this may result that the image is not displayed in some browsers.
I'm assuming that this clip-path should have the same x,y,width,height as the svg viewport.
I'm not sure if it's ggiraph's fault or dsvg's.

I attached a shiny app that reproduces the problem. Examine the svg output in a browser. All images refer to the same non-existent  clip-path. It doesn't matter if it's the same image or different. They all behave the same way.
[svg-image-test.zip](https://github.com/davidgohel/ggiraph/files/2424249/svg-image-test.zip)

**Comment by davidgohel** [comment]
thanks,

dsvg is the responsible :)

**Comment by sigmapi** [comment]
Yeah, I suspected so

**Comment by davidgohel** [comment]
It seems I fixed that issue when adding and refactoring `dsvg`...

Note that the branch `dsvg` has been merged into master.
