### ISSUE TITLE
Request: Include opts_toolbar under the See Also section of the help page for girafe_options

### ISSUE THREAD

**Issue by philstraforelli** [davidgohel/ggiraph#116]
I had trouble how to find out how to remove the "download" icon. Having the `opts_toolbar` included along with the other `opts_*` functions in the "See Also" section of `girafe_options()`'s help page would be a very nice touch.

**Comment by davidgohel** [comment]
Thanks for reporting this!

I have updated the documentation, it should be ok now

David

PS: for other reasons this new version is containing some cpp code and a compiler will be required to install it from github.
