### ISSUE TITLE
feature request: bringing highlighted points to forefront

### ISSUE THREAD

**Issue by devonorourke** [davidgohel/ggiraph#117]
Hi,
One of the terrific features that `ggiraph` offers is to highlight points which are connected to common groups. However, in cases where these points are overlapping with other non-related points, the highlighted point is obscured. Is there a way to ensure that the highlighted parts come to the forefront? I've tried fuddling with `alpha` but that makes all the points - including highlighted ones - faint. It'd be great to have a sort of feature where the alpha is actually tuned to two different values based on the highlighted and non-highlighted points.
Here's a quick example of what I'm talking about with regards to highlighted points being obscured:
```
install.packages("nycflights13")
library(nycflights13)
library(ggplot2)
library(ggiraph)

badair <- subset(flights[,c(9:11,13:15)], carrier == c("UA", "DL", "AA") & arr_delay > 100)

gg_flights <- ggplot(badair, aes(x = air_time, y = arr_delay, group = origin, label = origin)) + 
  facet_wrap( ~ carrier) + 
  geom_point_interactive(aes( data_id = origin,
                              tooltip = flight))

girafe(ggobj = gg_flights)
```

If you click on the middle facet (`DL`) and hover over the top-most datapoint (_2391_) you'll see that there are may datapoints sharing that group (what airline they came from). I wonder if there's a way so that these highlighted points are hidden behind the black points?

One option would be to color the groups so you don't need to use the highlighting feature, but then the colors get so overlapped that you can't distinguish them. You can certainly facet that layer as well, but your highlighting feature presents an elegant way to reduce a faceted dimension which I think always makes data comparison easier.

Thanks for your consideration!

**Comment by d-qn** [comment]
You can adjust the hover effect with ggiraph::girafe_options(opts_hover)

`#install.packages("nycflights13")
library(nycflights13)
library(ggplot2)
library(ggiraph)

badair <- subset(
  flights[,c(9:11,13:15)], carrier == c("UA", "DL", "AA") & arr_delay > 100)

gg_flights <- ggplot(badair, 
                     aes(x = air_time, y = arr_delay, group = origin, label = origin)) +
  facet_wrap( ~ carrier) +
  geom_point_interactive(aes( data_id = origin,
                              tooltip = flight), alpha = 0.2)

x <- girafe(ggobj = gg_flights)
x <- girafe_options(x, opts_hover(css = "fill-opacity:1;fill:orange;stroke:red;") )
x`

**Comment by devonorourke** [comment]
Ah, that's wonderful. Thanks very much.

**Comment by davidgohel** [comment]
thanks @d-qn 

I am closing the issue (as it seems answered to me).

David

**Comment by brooksambrose** [comment]
At first I thought this should be resolved by setting the z-index for the hover, but couldn't get it to work. Then I learned SVG elements don't accept a z-index, and everything is determined by draw order. The only way to put something on top would be with javascript to reorder the element in the DOM. Is there a way to add a js function like this in ggiraph?
