### ISSUE TITLE
add outputFunction argument to render function

### ISSUE THREAD

**Issue by sebdalgarno** [davidgohel/ggiraph#122]
In R Markdown documents, Shiny render functions can be called without their UI component. Arguments that would normally be passed to UI can be given like:
```
renderPlot({ 
  plot(yourData) 
}, outputArgs = list(width = "200px", 
                     height = "100px")
)
```
Any plans to make `renderGirafe` have similar functionality?
```
---
pagetitle: "test"
output: html_document
runtime: shiny
---

```{r, echo=FALSE}
 renderPlot({
  plot(iris[1:2])
}, outputArgs = list(width = "250"))

# library(ggiraph)
#  renderGirafe({
#   plot(iris[1:2])
# }, outputArgs = list(width = "250"))
```

**Comment by davidgohel** [comment]
That's already possible. Your script is containing issues: 

- you want to use `renderPlot` arguments in the call to `renderGirafe()`. 
- you are not creating any *girafe* object there, you should call `girafe()` 
- girafe is expecting a ggplot object

```
library(ggiraph)
library(ggplot2)
g <- ggplot(mpg, aes( x = displ, y = cty, color = hwy) )
my_gg <- g + geom_point_interactive(aes(tooltip = model), size = 2) 

renderGirafe({
  girafe(code = print(my_gg) )
})
```

**Comment by davidgohel** [comment]
I don't think `shinyRenderWidget` can handle `outputArgs` but if you have an idea, I would be happy to provide the feature. Do you know any other htmlwidget that support this kind of argument?

**Comment by sebdalgarno** [comment]
I'm sorry my example was a very bad one!
Here is better code for testing in an Rmarkdown document:

---
pagetitle: "test"
output: html_document
runtime: shiny
---

```{r, echo=FALSE}

library(ggplot2)
library(ggiraph)

# gg <- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width)) + geom_point()
#  renderPlot({
#   gg
# }, outputArgs = list(width = "250"))

library(ggiraph)
 renderGirafe({
  girafe(ggobj = gg)
}, outputArgs = list(width = "250"))
```

**Comment by sebdalgarno** [comment]
Perhaps you are right that it is not possible. I will try to find another htmlwidget that supports outputArgs

**Comment by davidgohel** [comment]
No no, I was wrong, I should have waited before answering! 

I just reread `shinyRenderWidget` doc, there is an argument named `outputFunction` that should make it possible.

Thanks, that is a very good point.

**Comment by CRG180** [comment]
Just to be crystal clear, right now there is not working function to change the size of **shiny** ggiraph objects in **R markdown**?  Is there a workaround like, maybe inserting a javascript function to override the default px size.
