### ISSUE TITLE
Flexdashboard breaks down when displayed in full screen and in browser mode

### ISSUE THREAD

**Issue by makis23** [davidgohel/ggiraph#123]
I have the flexdashboard below which generates a datatable and a plotly line chart. As you will see when the app is loaded initially in minimized vied the whole line chart is displayed. Wheh I try to watch it in full view I lose half of the lines. The second issue is that when I open it in browser nothing seems to work. Besides plotly I also tried ggplot2 with the same result.

```
---
title: "[School Name] Enrollment Projections for Fall 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    runtime: shiny
---
```{r setup, include = FALSE}
library(flexdashboard)
library(shiny)
library(reshape2)
library(plotly)
library(tidyverse)
```
Column {.sidebar }
-------------------------------------
### Menu
```{r}
```

Row {data-height=400}
-------------------------------------
### Enrollments
```{r}
renderTable(mtcars)
```
Row {data-height=400}
-------------------------------------
### Enrollments
```{r}

year<-c("2000","2000","2001","2002","2000")
gender<-c("M","F","M","F","M")
YG<-data.frame(year,gender)

ns<-data.frame(YG %>%
                 group_by(year) %>%
                 count(gender) %>%
                 spread(gender, n) %>%
                 mutate_all(replace_na, 0))


plot_ly(ns, x = ~factor(year), y = ~M, name = 'Males', type = 'scatter', mode = 'lines',
        line = list(color = 'rgb(205, 12, 24)', width = 4)) %>%
  add_trace(y = ~F, name = 'Females', line = list(color = 'rgb(22, 96, 167)', width = 4)) %>%
  layout(title = "Day 10 Enrollments",
         xaxis = list(title = "Years"),
         yaxis = list (title = "Count"))
```
```

**Comment by sigmapi** [comment]
Hm, this is ggiraph project. It has nothing to do with plotly.
