### ISSUE TITLE
plots overlap when generating a dynamic number of plots

### ISSUE THREAD

**Issue by tdwils** [davidgohel/ggiraph#124]
I am dynamically adding plots to a Shiny app, similar to this example that uses plotOutput:
https://gist.github.com/wch/5436415/

When I convert the code to use ggiraph (0.6.0), it behaves properly in Chrome, but in Firefox and IE the height parameter in girafeOutput is not behaving as expected. The height parameter ends up being the distance between the top of consecutive graphs. As a result, in Firefox and IE the graphs are too large and they overlap.

Here is the original code using plotOutput: https://gist.github.com/wch/5436415/

Here is the code converted to ggiraph:

```
library(shiny)
library(ggplot2)
library(ggiraph)

max_plots <- 5

server <- function(input, output) {
  
  # Insert the right number of plot output objects into the web page
    output$plots <- renderUI({
      plot_output_list <- lapply(1:input$n, function(i) {
      plotname <- paste("plot", i, sep="")
      girafeOutput(plotname, height = 250) 
    })
    
    # Convert the list to a tagList - this is necessary for the list of items
    # to display properly.
    do.call(tagList, plot_output_list)
  })
  
  # Call renderPlot for each one. Plots are only actually generated when they
  # are visible on the web page.
  for (i in 1:max_plots) {
    # Need local so that each item gets its own number. Without it, the value
    # of i in the renderPlot() will be the same across all instances, because
    # of when the expression is evaluated.
    local({
      my_i <- i
      plotname <- paste("plot", my_i, sep="")
      
      output[[plotname]] <- renderGirafe({
        plotdata <- data.frame(x = 1:my_i, y = 1:my_i)
        g <- ggplot(plotdata, aes(x=x, y=y)) + xlim(1, max_plots) + ylim(1, max_plots) +
          geom_point_interactive(shape = 1, size = 4) +
          labs(title = paste("1:", my_i, ".  n is ", input$n, sep = ""))
        girafe(code = print(g))
      })
    })
  }
}

ui <- pageWithSidebar(
  
  headerPanel("Dynamic number of plots"),
  
  sidebarPanel(
    sliderInput("n", "Number of plots", value=1, min=1, max=5)
  ),
  
  mainPanel(
    uiOutput("plots") # This is the dynamic UI for the plots
  )
)

shinyApp(ui = ui, server = server)
```

This displays correctly in Chrome:
 
![image](https://user-images.githubusercontent.com/16843423/50492867-0c018680-09e8-11e9-8d0e-23a058c83b9b.png)

When run in Firefox, the graphs are not sized correctly and they overlap (same in IE):
 
![image](https://user-images.githubusercontent.com/16843423/50492873-13289480-09e8-11e9-9915-ea49cf783c83.png)

Is there some way to adjust the settings so the plots in Firefox and IE don’t overlap and are sized correctly?

**Comment by davidgohel** [comment]
Thanks for reporting that. I can't answer for now, I don't know exactly what is going on (but at least I am able to reproduce)

**Comment by davidgohel** [comment]
Hi,

This should be fixed in the new Github version (thanks to @sigmapi work)

David

**Comment by tdwils** [comment]
Thank you for the fast response. 

Great package. It is my first choice when I need interactive plots in Shiny.
