### ISSUE TITLE
Missing values in geom_line vs geom_line_interacting

### ISSUE THREAD

**Issue by dickoa** [davidgohel/ggiraph#125]
Hi,

I was playing a little bit with `geom_line_interactive` and it looks like it handle missing values that occurs in the middle of a a line differently than `geom_line`. `ggplot2::geom_line` breaks the line but `ggiraph::geom_line_interactive` doesn't. Find below a reprex:

```r
library(ggiraph)
library(ggplot2)

set.seed(1)
d <- seq(Sys.Date(), (Sys.Date() + 10), by = "day")
n <- length(d)
x <- rnorm(n)
x[floor(n/2)] <- NA
df <- data.frame(d = d, x = x)

ggplot(df, aes(d, x)) +
    geom_line() +
    labs(title = "ggplot2::geom_line")

ggplot(df, aes(d, x)) +
    geom_line_interactive()  +
    labs(title = "ggiraph::geom_interactive_line")
```

![ggplot_line](https://user-images.githubusercontent.com/500140/50608383-6f962300-0ec4-11e9-9c1f-2c56aab74e3c.png)
![ggiraph_line](https://user-images.githubusercontent.com/500140/50608395-76bd3100-0ec4-11e9-8766-3180f2bc0985.png)

I apologize if it's a known feature or a bug documented that I somehow missed.

Happy new year and thanks again for this awesome package!

**Comment by davidgohel** [comment]
Hi,

Thanks for reporting this, this was not a known issue. This won't be fixed right now but will be probably in the next weeks

david

**Comment by sigmapi** [comment]
This is occurring because GeomPathInteractive implementation is outdated. 
ggplot2 handles this differently inside GeomPath.
GeomPathInteractive should be updated (I'm working on it and in similar cases, where ggplot2 has updated the geom implementations) .

**Comment by davidgohel** [comment]
Thanks @sigmapi 

This is fixed now.

**Comment by JT-39** [comment]
Hello!

I have an issue which is similar to this, so commenting here. But apologies if that is not the standard, I can create a new issue.

So, I have a `NA` in the middle of a time series for one of the groups I am plotting (in a line with point chart):

Here is the code:

```

la_long <- read.csv("path_to_data/ggiraph_na_potential_bug_warning.csv", check.names = FALSE)

la_line_chart <- la_long |>
  # Filter out NAs to stop warning
  # "Failed setting attribute 'data-id', mismatched lengths of ids and values"
  # dplyr::filter(!is.na(values_num)) |> 
  ggplot2::ggplot() +
  ggiraph::geom_point_interactive(
    ggplot2::aes(
      x = Years_num,
      y = values_num,
      color = `LA and Regions`,
      data_id = `LA and Regions`
    ),
    na.rm = TRUE
  ) +
  ggiraph::geom_line_interactive(
    ggplot2::aes(
      x = Years_num,
      y = values_num,
      color = `LA and Regions`,
      data_id = `LA and Regions`
    ),
    na.rm = TRUE
  )

# Plotting interactive graph
ggiraph::girafe(
  ggobj = la_line_chart,
  width_svg = 8
)

```

The data is attached below.

Barnsley has a missing value for , but values either side of it. For some reason this causes the warning message: 

```
Warning message:
In set_attr(name = attrName, ids = as.integer(ids), values = attrValue) :
  Failed setting attribute 'data-id', mismatched lengths of ids and values (most often, it occurs because of clipping or because of NAs in data)
```

If I remove the NA from the data the warning message goes away (but then this causes the line chart to join the data points either side of the NA so is not desired) and if I change all the data points to NA either up to or after the NA, then the non NA data will plot with no warning.

Potentially this warning is too strict?

Data:
[ggiraph_na_potential_bug_warning.csv](https://github.com/user-attachments/files/17061684/ggiraph_na_potential_bug_warning.csv)
