### ISSUE TITLE
Feature request: ggbeeswarm

### ISSUE THREAD

**Issue by davemcg** [davidgohel/ggiraph#126]
https://github.com/eclarke/ggbeeswarm

Would you consider adding support for geom_quasirandom and/or geom_beeswarm to ggiraph? I'm a big fan of beeswarm plots as they show the points, but also the distribution, when you have many data points. 

Thanks,
David

**Comment by davidgohel** [comment]
I am afraid I don't have enough free time for it. Sorry

**Comment by davidgohel** [comment]
just to let you know... you can use exported objects to create your functions, use GeomInteractivePoint 
 for example if you need to extends ggbeeswarm.

**Comment by davemcg** [comment]
I don't quite follow - is there a guide you could point me to? This? https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html (apologies for my naiveté)

**Comment by davidgohel** [comment]
Yes for example. `GeomInteractivePoint` is an exported ggproto.

**Comment by saramasarone** [comment]
Hi, we are having the same issue @davemcg. How did you solve this? Is there a standard way to implement this or a tutorial? (I'm not an R user, so not very familiar with this)
