### ISSUE TITLE
Girafe plot won't display if interrupted

### ISSUE THREAD

**Issue by kellyasche** [davidgohel/ggiraph#127]
I'm creating a shiny app that utilizes ggiraph to display interactive ggplot charts. The functionality is fantastic and I love this package, but I'm having an issue where a chart won't display if it's clicked away from while it's still loading and then you go back to that "page" to see the chart.

I created a quick example. When you run the app, click on the tab "Click here!" before the map loads and then click back to the "Map" tab and you will see that the map won't display. If I just use ggplot and don't convert to girafe, the map will display no matter if you click away quick.

I apologize if this is the inappropriate place to ask a question. I've been using Shiny for over a year now but very new at posting questions. I did post this question on the RStudio Community forum but have not received a response yet. I've googled this issue but couldn't find anything related.

Thanks for any guidance

````
library(shiny)
library(sf)
library(ggiraph)
library(tidyverse)
library(shinycssloaders)


# Prepare object ----------------------------------------------------------

sf.object <- system.file("shape/nc.shp", package = "sf")

nc <- st_read(sf.object)

# Define UI for application
ui <- fluidPage(
  tabsetPanel(
    tabPanel("Map",
             girafeOutput("examplemap") %>% withSpinner()),
    
    tabPanel("Click here!")
  )
)

# Define server logic 
server <- function(input, output) {
  
  output$examplemap <- renderGirafe({
    
    plot <- ggplot(nc) +
      geom_sf_interactive(aes(fill = FIPSNO, data_id = FIPS, tooltip = NAME)) +
      scale_fill_gradient()
    
    girafe(code = print(plot))
    
    
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
````

**Comment by davidgohel** [comment]
Hi, 

This is the correct place to ask :)  I am able to reproduce your issue

What is happening is that the plot is sized according to its container size. When clicking on the tab, it makes an height equals to 0... So the plot is existing but cannot be seen as it height is set to 0.

I don't have solution for that for now. I will think about a way to manage that case but I can't work on it for now

David

**Comment by kellyasche** [comment]
Okay, that makes perfect sense. 

As for process, should I go ahead and close this or keep it open?

**Comment by davidgohel** [comment]
keep it open, I will close it if I can fix that (or if I can't but I need to spend time on it first)

**Comment by RozennGZ** [comment]
Hi,

I have exactly the same problem, I thought that it was an issue with my app but apparently not. The weird thing is that the graph can re-appear by changing the size of the browser... 

Let us know if you have a trick to solve this issue ! :) 

Thanks !

Rozenn.

**Comment by davidgohel** [comment]
Hi,

Could you update the package from github and give a try to the following code:

```
library(shiny)
library(sf)
library(ggiraph)
library(tidyverse)
library(shinycssloaders)


# Prepare object ----------------------------------------------------------

sf.object <- system.file("shape/nc.shp", package = "sf")

nc <- st_read(sf.object)

# Define UI for application
ui <- fluidPage(
  tabsetPanel(
    tabPanel("Map",
             girafeOutput("examplemap", width = 1000, height = 800) %>% withSpinner()),
    tabPanel("Click here!")
  )
)

# Define server logic 
server <- function(input, output) {
  
  output$examplemap <- renderGirafe({
    
    plot <- ggplot(nc) +
      geom_sf_interactive(aes(fill = FIPSNO, data_id = FIPS, tooltip = NAME)) +
      scale_fill_gradient()
    
    girafe(code = print(plot)) %>% 
      girafe_options(opts_sizing(rescale = FALSE))
    
    
  })
}

# Run the application 
shinyApp(ui = ui, server = server) %>% print
```

The key point is usage of `girafe_options(opts_sizing(rescale = FALSE))`. It will make the graph sized to fixed dimensions of the container (the `girafeOutput` in our case)

**Comment by kellyasche** [comment]
Yes! I was able to update the package from GitHub and it resolved my issue. Thanks a ton! Should I go a head and close?

For anyone else following along, if you're experiencing errors when attempting to update from GitHub (devtools::install_github(),  make sure to update all of your packages first. Once you do that, updating ggiraph from GitHub worked like a charm.

**Comment by RozennGZ** [comment]
Hi,
It's also solved my issue ! Thank you very much for your reactivity !!!

**Comment by davidgohel** [comment]
Cool

Thanks @RozennGZ and @kellyasche 

I will submit to cran soon 

I will close the issue a little bit later (I need to add documentation)
