### ISSUE TITLE
Display tooltip(s) of selected point(s)?

### ISSUE THREAD

**Issue by smile1000** [davidgohel/ggiraph#129]
Hello,

Could you please give me the command line/option or parameter to specify so that the tooltip(s) are displayed for all selected point(s) in a ggiraph graphic in a Shiny app (and not just when hovering over a point with the mouse)? If that is possible of course?

For instance, I assume the following line in server.R should be modified:

```
output$myImage <- renderggiraph({ggiraph(code = print(gg_interactiveimage),width=.9,zoom_max=4,selection_type="multiple",hover_css = "fill:gold;",selected_css = "fill:gold;")})
```

Thank you for your help with this,

Emile

**Comment by davidgohel** [comment]
Hi Emile,

Sorry this is not a feature. A tooltip is displayed when mouse over an element but there is no option to display `p` tooltip in another context (i.e. after having selected points)

KR
David
