### ISSUE TITLE
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, : internal error: Huge input lookup [1]

### ISSUE THREAD

**Issue by VamsiGundaba** [davidgohel/ggiraph#130]
I am new to r programming.
I am getting this error only if the file has a large number of records.
With a smaller number of records, I don't get any error and can print the output in .docx format.

I am using officer & flextable packages for output. This is the code i am using.

library(officer)
library(flextable)
myft <- regulartable(dataset, col_keys = names(dataset))
my_doc <- body_add_par(my_doc, "", style = "Normal")
my_doc <- body_add_flextable(my_doc, value = myft)
print(my_doc, target = "path/ABC.docx") 
How do I write a docx file from a dataset with a large number of records?

**Comment by davidgohel** [comment]
Issue moved to [davidgohel/flextable #114](https://github.com/davidgohel/flextable/issues/114) via [**ZenHub**](https://www.zenhub.com/)
