### ISSUE TITLE
Get tooltip value for selection in shiny-app

### ISSUE THREAD

**Issue by tothuhien** [davidgohel/ggiraph#131]
Hello, 
I'm trying to find a why to get the tooltip value on selection in a shiny-app. I've read in your guide page that I will get the data-id value when select; but I want to get the tooltip value - which in my case is different from data-id. Is there anyway to do that?
Thanks a lot for your help.
Hien

**Comment by davidgohel** [comment]
Hello,

You can use match function to match the selected id with all id existing in your dataset, you will get an index and then you can use that index on the tooltip column.

KR
David

**Comment by tothuhien** [comment]
Thanks David for your response. My problem is several tooltip values can have the same data-id value; so having data-id is not enough to infer the tooltip of only the point I've selected. Do you have any suggestion? Thanks
Hien

**Comment by davidgohel** [comment]
No sorry.
