### ISSUE TITLE
Shiny dynamic chart height

### ISSUE THREAD

**Issue by jdk11** [davidgohel/ggiraph#132]
I am working on a Shiny app which uses girafe. I am trying to display at least two bar charts one above the other in a column of limited width. However, I need the height and width of the chart to increase if the web page is increased and vice versa. This means I cannot set the height explicitly in the ui component.

 

When I do not set the height then the first chart includes a large amount of white space below it (this is the default size). Is there a way to remove this white space without setting the height explicitly?

 

An example code is below:

 

server <- function(input, output) {

  output$bar_1 <- renderGirafe({

   

    df <- data.frame(dose=c("D0.5", "D1", "D2"),

                     len=c(4.2, 10, 29.5))

   

    p<-girafe(code = print(ggplot(data=df, aes(x=dose, y=len)) +

      geom_bar_interactive(stat="identity")

    ))

    p

  })

 

  

  output$bar_2 <- renderGirafe({

   

    df <- data.frame(dose=c("D0.5", "D1", "D2"),

                     len=c(4.2, 10, 29.5))

   

    p<-girafe(code = print(ggplot(data=df, aes(x=dose, y=len)) +

                             geom_bar_interactive(stat="identity")

    ))

    p

  })

}

 

ui <- fluidPage(

  fluidRow(

    column(width = 2,

           fluidRow(

             girafeOutput("bar_1")

           ),

           fluidRow(

             girafeOutput("bar_2")

           )

    )

  )

)

**Comment by davidgohel** [comment]
Can you add a reproducible example and the `sessionInfo()` please

**Comment by jdk11** [comment]
library(shiny)

library(ggplot2)

library(ggiraph)

 

server <- function(input, output) {

  output$bar_1 <- renderGirafe({

   

    df <- data.frame(dose=c("D0.5", "D1", "D2"),

                     len=c(4.2, 10, 29.5))

   

    p<-girafe(code = print(ggplot(data=df, aes(x=dose, y=len)) +

      geom_bar_interactive(stat="identity")

    ))

    p

  })

 

  

  output$bar_2 <- renderGirafe({

   

    df <- data.frame(dose=c("D0.5", "D1", "D2"),

                     len=c(4.2, 10, 29.5))

   

    p<-girafe(code = print(ggplot(data=df, aes(x=dose, y=len)) +

                             geom_bar_interactive(stat="identity")

    ))

    p

  })

}

 

ui <- fluidPage(

  fluidRow(

    column(width = 2,

           fluidRow(

             girafeOutput("bar_1")

           ),

           fluidRow(

             girafeOutput("bar_2")

           )

    )

  )

)

 

shinyApp(ui = ui, server = server)

 

## SESSION INFO

# R version 3.4.3 (2017-11-30)

# Platform: x86_64-w64-mingw32/x64 (64-bit)

# Running under: Windows 7 x64 (build 7601) Service Pack 1

#

# Matrix products: default

#

# locale:

#   [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252

# [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252   

#

# attached base packages:

#   [1] parallel  stats     graphics  grDevices utils     datasets  methods   base    

#

# other attached packages:

#   [1] ggrepel_0.8.0     bindrcpp_0.2      plotly_4.8.0      gdtools_0.1.7     ggiraph_0.5.0     ggplot2_3.0.0     RJSONIO_1.3-1.1 

# [8] doParallel_1.0.11 iterators_1.0.9   foreach_1.4.4     RODBC_1.3-15      dygraphs_1.1.1.6  xts_0.10-1        zoo_1.8-0       

# [15] boot_1.3-20       scales_1.0.0      shinyjs_1.0       shiny_1.2.0     

#

# loaded via a namespace (and not attached):

#   [1] purrr_0.2.4         lattice_0.20-35     colorspace_1.3-2    htmltools_0.3.6     viridisLite_0.3.0   yaml_2.1.19       

# [7] base64enc_0.1-3     rlang_0.2.2         pillar_1.0.1        later_0.7.3         glue_1.2.0          withr_2.1.2       

# [13] uuid_0.1-2          bindr_0.1           plyr_1.8.4          munsell_0.5.0       gtable_0.2.0        zip_1.0.0         

# [19] htmlwidgets_1.2     codetools_0.2-15    labeling_0.3        crosstalk_1.0.0     httpuv_1.4.4.2      Rcpp_0.12.14      

# [25] xtable_1.8-3        promises_1.0.1      jsonlite_1.5        mime_0.5            digest_0.6.15       dplyr_0.7.4       

# [31] grid_3.4.3          tools_3.4.3         magrittr_1.5        lazyeval_0.2.1      tibble_1.4.1        crayon_1.3.4      

# [37] tidyr_0.7.2         pkgconfig_2.0.1     data.table_1.10.4-3 xml2_1.2.0          rvg_0.1.9           rstudioapi_0.7    

# [43] assertthat_0.2.0    httr_1.3.1          officer_0.3.2       R6_2.2.2            compiler_3.4.3

**Comment by davidgohel** [comment]
OK OK, I will format the message for you

**Comment by davidgohel** [comment]
So you are working with an old version. Please update to 0.6.1

**Comment by davidgohel** [comment]
You need to get the latest version to have a widget where height is not fixed. 

You have another issue in your code (you forgot `column` in `fluidRow` but that is not linked to ggiraph)
