### ISSUE TITLE
Programmatically set/clear lasso selections?

### ISSUE THREAD

**Issue by Dreznel** [davidgohel/ggiraph#133]
Hello,

Thanks for all the great work on ggiraph. I was wondering, is there a way to programmatically set/unset lasso selections in the context of a Shiny application? 

I have a girafe object that uses `geom_point_interactive()` (so basically a scatterplot), and I want to allow users to make multiple distinct selections, one at a time, without having to anti-lasso-select in between groups. Ideally, I would also like to "reload" previous selections so that users can modify them even after they've moved on.

Is this possible?

**Comment by davidgohel** [comment]
Hello,

Yes, use the following method where `myplot` is the id of the `ggiraph` output:

set values: `session$sendCustomMessage(type = 'myplot_set', message = '<your ids>')`

get values: `input$myplot_selected`

This is documented here: https://davidgohel.github.io/ggiraph/articles/offcran/using_ggiraph.html#selections

KR

**Comment by Dreznel** [comment]
Hi David,

Just wanted to say thanks for your help, and I apologize for missing that in the docs.
