### ISSUE TITLE
tooltip displaying two tooltips when shinyjqui functions are called in shiny app

### ISSUE THREAD

**Issue by smlehman** [davidgohel/ggiraph#136]
Hi David.  
First off, thanks much for all your work on this package. I'm using it extensively in a large (8k lines of code) app and like it much better than plotly.  I'm trying to solve one problem.  I would like users to be able to resize and drag plots so that they could easily see them side by side. Was initially using functions from shinyjqui to enable dragging and resizing plots but had to disable these because my tooltips (across all plots in the app) display 2 tooltips (see screenshot). One that's formatted and then another unformatted one on top.  I haven't been able to reproduce this issue in a simple app, so thought I'd check to see if you had any ideas for making ggiraph and shinyjqui get along.  Any ideas would be much appreciated.
Steve
<img width="894" alt="Screen Shot 2019-06-01 at 10 39 26 AM" src="https://user-images.githubusercontent.com/49706314/58852167-b6926b00-8652-11e9-952f-e9a11fffb75e.png">
...and yes, for those who work in education, this is protected data, but the student is my son. 

###list of packages called in the app
library(ggrepel) 
library(ggthemes)
library(RColorBrewer)
#library(plotly) 
library(shinyjs) 
library(shiny) 
library(shinydashboard) 
library(shinydashboardPlus)  
library(tidyverse) 
library(DT)   
library(shinycssloaders)
library(shinyWidgets)  
library(stringr)
library(lazyeval) 
library(ggiraph)
library(shinyjqui) ##  !!!!!conflict with ggiraph... interactive graphs show double tooltip boxes
library(randomNames)
library(htmlwidgets) 
library(lubridate)

**Comment by davidgohel** [comment]
Hi @smlehman 

Sorry, I would need a minimal reproducible example to help, I don't know shinyjqui. 
I will re open if you can provide one.

Thank you
