### ISSUE TITLE
Cannot follow the "Arrange multiple plots into a grid" example

### ISSUE THREAD

**Issue by najsaqib** [davidgohel/ggiraph#137]
I am looking at making use of cowplot in conjunction with ggiraph in a Shiny app to have an interactive plot inset and/or be able to arrange a couple of interactive plots into a grid.

However, I am unable to follow the example provided [here](https://davidgohel.github.io/ggiraph/articles/offcran/examples.html) in the `ggiraph` documentation to utilize cowplot, which has an output that should look like below: 

![image](https://user-images.githubusercontent.com/22086214/59282845-8ab94b80-8c37-11e9-8bb4-00a9f2a3d7df.png)

Using `girafe( code = print(gg1 + gg2), width_svg = 8, height_svg = 4)` gives me the following error: 

> Error: Don't know how to add gg2 to a plot

Am I correct in assuming that there is missing code for that example?

**Comment by davidgohel** [comment]
Thanks for reporting that, you're right, it should be:

```
girafe( ggobj = plot_grid(gg1, gg2), width_svg = 8, height_svg = 4)
```

I will update the web site soon - the wignette code has been updated

**Comment by najsaqib** [comment]
Thanks for the quick response, and the great package in general!
