### ISSUE TITLE
geom_histogram_interactive incompatibility with geom_density

### ISSUE THREAD

**Issue by JackThHanley** [davidgohel/ggiraph#139]
Hello,

I really enjoy using ggiraph, but I've run into an issue recently when trying to incorporate density curves with geom_histogram_interactive. 

Typically, when I'm doing a regular geom_histogram, I'll specify that y = ..density.. so that everything is properly scaled. However, this scaling is skewed with geom_histogram_interactive, showing different density results than before. It appears that the height of each is greater than those of the original geom_histogram. The relative heights of the bins look the same, so I believe it might be something to do with the height of each stack in.

I've looked through the function documentation and read the vignettes provided, but I still can't seem to find any solution. There are obviously ways to brute-force the scaling to be the same, but I then run the risk of biasing my visualizations.

An example of this issue is visualized in the attached code example using the iris dataset, tidyverse (ggplot2 and dplyr's pipe).

```{r}
library(tidyverse)
library(ggiraph)

iris %>%
  ggplot(aes(x = Sepal.Width, y = ..density..))+
  geom_histogram()+
  geom_density(col = "red")

testgg <- iris %>%
  ggplot(aes(x = Sepal.Width))+
  geom_histogram_interactive(aes(data_id = Species, tooltip = Species, y = ..density..))+
  geom_density(col = "red")
girafe(ggobj = testgg)
```
![Rplot1](https://user-images.githubusercontent.com/43326345/62143885-d5158b00-b2be-11e9-96e1-7799391b368e.png)
![Rplot2](https://user-images.githubusercontent.com/43326345/62143886-d5158b00-b2be-11e9-9976-4dd34a3c01da.png)

**Comment by sigmapi** [comment]
Hi,
the problem here is that the aesthetics in geom_histogram_interactive call include the Species data column. This introduces a grouping in the data and the density is calculated differently.
If you remove the aesthetics (data_id and tooltip) you'll see that you'll get the same result as in geom_histogram. So, it's not really a bug in ggiraph.

Another way to verify this, is by adding an aesthetic using the Species in the first call:
```
iris %>%
  ggplot(aes(x = Sepal.Width, y = ..density.., colour=Species))+
  geom_histogram()+
  geom_density()

girafe(ggobj = iris %>%
  ggplot(aes(x = Sepal.Width, y = ..density.., colour=Species))+
  geom_histogram_interactive(aes(data_id = Species, tooltip = Species))+
  geom_density()
)
```
You'll see that now, the plots are the same.
