### ISSUE TITLE
Error loading ggiraph

### ISSUE THREAD

**Issue by ameliabedelia** [davidgohel/ggiraph#140]
When I try to load ggiraph (using the CRAN version) I get the following error message:

`> library(ggiraph)`
Error: package or namespace load failed for ‘ggiraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found

***

I also tried to install the development version and got the same error.

***

My session info is:
`> sessionInfo()`
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  bookdown_0.12   htmltools_0.3.6 tools_3.6.1    
 [5] yaml_2.2.0      Rcpp_1.0.2      rmarkdown_1.14  blogdown_0.14  
 [9] knitr_1.24      xfun_0.8        digest_0.6.20   evaluate_0.14  

Thanks in advance,
Amelia

**Comment by davidgohel** [comment]
Hi @ameliabedelia 

Can you try to install X11 from [here](https://www.xquartz.org/) and retry the installation?

Also if you updated your OSX, make sure you have Xcode installed and accept the licence?

David

**Comment by ameliabedelia** [comment]
Thanks for the help! Installing XQuartz fixed the problem and I am able to load and use with no problems now. 

Amelia
