### ISSUE TITLE
Compatible with R 3.3.0? 

### ISSUE THREAD

**Issue by cardiomoon** [davidgohel/ggiraph#15]
I am a big fan of package "ggiraph".
But I recently updated my R to version 3.3.0 and I am not able to see the interactive plot.
Is it compatible with R 3.3.0?

I use the latest version of RStudio 0.99.902  and OS X Yosemite 10.10.4.

**Comment by davidgohel** [comment]
Yes it is compatible with R 3.3.0.

If running code from the vignette, what is happening?

https://cran.r-project.org/web/packages/ggiraph/vignettes/ggiraph.html

**Comment by cardiomoon** [comment]
Nothing happened. I am trying now.

**Comment by davidgohel** [comment]
what's your `sessionInfo()`?

**Comment by cardiomoon** [comment]
Dear David,

My sessionInfo() is as follows.

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/ko_KR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reshape2_1.4.1     gdtools_0.0.7      ggiraph_0.3.0.9000 ggplot2_2.1.0     
[5] moonBook_0.1.5     plyr_1.8.3        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5        xml2_0.1.2         magrittr_1.5       munsell_0.4.3     
 [5] colorspace_1.2-6   stringr_1.0.0      tools_3.3.0        grid_3.3.0        
 [9] gtable_0.2.0       rvg_0.0.9          R.oo_1.20.0        htmltools_0.3.5   
[13] yaml_2.1.13        digest_0.6.9       RColorBrewer_1.1-2 htmlwidgets_0.6   
[17] R.utils_2.3.0      rsconnect_0.4.3    labeling_0.3       stringi_1.0-1     
[21] scales_0.4.0       R.methodsS3_1.7.1  jsonlite_0.9.20   


Thank you very much for your concern.

Keon-Woong Moon

**Comment by davidgohel** [comment]
So you did run code from the vignette but nothing happened. 
I have no clue how to reproduce that...

Could you try to update xml2 and rvg (I have to make modification yesterday to rvg) and see if it solve the issue?

```
devtools::install_github("hadley/xml2")
devtools::install_github("davidgohel/rvg")
```

David

**Comment by cardiomoon** [comment]
Dear David, 

I have updated two packages from github as you recommended.

May I ask some questions?


1. I executed the following code In your vignette


library(ggiraph)

dataset <- mtcars
head(dataset)
dataset$tooltip <- row.names(dataset)

# geom_point_interactive example
gg_point_1 <- ggplot(dataset, aes(x = disp, y = qsec, 
                                  color = wt, tooltip = tooltip ) ) + 
    geom_point_interactive(size=3) + gg_th

=> ended with error :   cannot find gg_th

1. So, I executed the code without + gg_th 

gg_point_1 <- ggplot(dataset, aes(x = disp, y = qsec, 
                                  color = wt, tooltip = tooltip ) ) + 
    geom_point_interactive(size=3) 

gg_point_1

-> I obtained the plot

# htmlwidget call
ggiraph(code = {print(gg_point_1)}, width = "400px", height = "400px")

-> Nothing was shown in Rstudio View.

But, this is not a big problem. I have a RStudio server using R 2.3.3 and in the server the ggiraph package does well.
I will try in other computers.


2. I tried ggiraph function with this minimal shiny app in my computer and also in my RStudioserver.

I tried both plotOutput and htmlOutput. 

require(shiny)
require(htmlwidgets)

library(ggiraph)


shinyApp(
    ui = fluidPage(
        
        mainPanel(plotOutput("plot"),
                  plotOutput("plot2"),
                  htmlOutput("plot3")
                  )
        
    ), 
    server = function(input, output) {
        
        dataset <- mtcars
        head(dataset)
        dataset$tooltip <- row.names(dataset)
        
        p<- ggplot(dataset, aes(x = disp, y = qsec, 
                                color = wt, tooltip = tooltip ) ) + 
            geom_point_interactive(size=3)
        
        output$plot <- renderPlot({ 
            p
        })
        output$plot2 <- renderPrint({ 
            ggiraph(code=print(p))
        })
       
        output$plot3 <- renderPlot({ 
            ggiraph(code=print(p))
        })
        
    }
)


I have one static plot in my shiny app and one interactive map in my RStudio viewer.





I am not able to get a interactive plot in my shiny app.

Could please show me the way?

Thank you very much.

Keon-Woong Moon

**Comment by davidgohel** [comment]
With the same OS and the same RStudio version, I can't reproduce the viewer issue within RStudio.
I used this code:

```
library(ggiraph)

# gg theme
gg_th <- theme(axis.ticks = element_line(colour = "gray90"), 
    panel.grid.major = element_line(colour = "gray90"), 
    panel.grid.minor = element_line(colour = "transparent"), 
    panel.background = element_rect(fill = "transparent"))

# geom_point_interactive example
gg_point_1 <- ggplot(mtcars, aes(x = disp, y = qsec, 
		color = wt, tooltip = row.names(mtcars), data_id = row.names(mtcars) ) ) + 
	geom_point_interactive(size=3) + 
  scale_color_gradient(low = "#F3C899", high = "#8C120A") 

gg_point_1 <- gg_point_1 + gg_th
# htmlwidget call
ggiraph(code = {print(gg_point_1)}, 
        tooltip_extra_css = "padding:2px;background:rgba(70,70,70,0.1);color:black;border-radius:2px 2px 2px 2px;",
        hover_css = "fill:#1279BF;stroke:#999999;stroke-width:1pt;r:6pt;cursor:pointer;")
```

For shiny, you have to use `ggiraphOutput` and `renderggiraph`. A shiny example is available here:
https://github.com/davidgohel/ggiraph/tree/master/inst/shiny

David

**Comment by cardiomoon** [comment]
Dear David,

Thank you very much for your help.

Keon

**Comment by cardiomoon** [comment]
Dear David,

My problem is related to RStudio.

When I execute your code, I am not able to see any plot in my viewer.

But when I use the browser(show in new viewer in RStudio viewer), I can see the interactive plot.

Final question :

I'd like to put my ggiraph plot into powerpoint.

At present, I make a html file with htmlwidget::saveWidget() function and make a link in my powerpoint file.

Is there any other way to embed the ggiraph plot into powerpoint file such as ReporteRs::addPlot? 

Thank you very much.

Keon-Woong Moon

**Comment by hrbrmstr** [comment]
@davidgohel, I'm wondering if this is potentially an RStudio widget issue with the locale of @cardiomoon?

@cardiomoon: You're not going to be able to embed widgets into powerpoint docs (at least not without some serious hacking). Consider using [`rmdshower`](https://cran.rstudio.com/web/packages/rmdshower/index.html) instead.

**Comment by cardiomoon** [comment]
Dear bob,

Thank you for your help.

I am trying rdmshower.

Koen-Woong Moon

**Comment by davidgohel** [comment]
@hrbrmstr I would need the js console to see what's going on... The locale is `UTF-8`, I am not sure but this should not be an issue, right? I thought issue where when locale was not UTF-8. I hate encoding issues. @cardiomoon are you able to see the console in the RStudio Viewer (contextual menu in the viewer pane, then *inspect element*, then click on the *console* tab)? If yes, could you send any errors and warnings if there are some?

@cardiomoon Bob is right, embed html in PowerPoint is not supported in `ReporteRs`.

**Comment by cardiomoon** [comment]
Dear Bob,

I am trying 'rmdshower' and 'ggiraph'. But in rmdshower presentation, I am not able to see tooltip.

Would you please help me to fix the problem?
