### ISSUE TITLE
outputId cannot contain "."

### ISSUE THREAD

**Issue by kepiej** [davidgohel/ggiraph#151]
Hi!

First of all, thanks for developing this awesome package!

I noticed that the outputId in girafeOutput cannot contain a "." in the name: 
In "ui.r":
<code> girafeOutput("plot.fail") </code>
In "server.r":
<code> output$plot.fail <- renderGirafe({}) </code>
fails to render a plot in the shiny application and prints no warning/error.
The standard <code> plotOutput </code> and <code> renderPlot </code> in shiny do support "." in the outputId.

It took me longer then I'd like to admit before I figured this out. 😢

**Comment by davidgohel** [comment]
Hi

You are welcome. Sorry you spent time on it, I never tried to add an input id with a `.`.

With shiny, it is recommended to not use special JavaScript characters such as a period `.` in the input id's when dealing with JavaScript. The standard `plotOutput` and `renderPlot` are not using JavaScript. I will add a note similar to the one of `shiny::conditionalPanel` in the documentation.

**Comment by kepiej** [comment]
Ok, thanks for adding the note to the documentation! 😄
