### ISSUE TITLE
Plots appearing small on shiny

### ISSUE THREAD

**Issue by dkesh** [davidgohel/ggiraph#155]
I see that there was a change to resizing behavior in shiny in 0.6.1.  I recently updated to 0.7.0, probably from a version previous to 0.6.1, and started seeing issues with plots always appearing small. Here's a simple app and here's how it appears: ![Screenshot_20200110_123632](https://user-images.githubusercontent.com/1952932/72177234-e0a8ca00-33a5-11ea-8da9-fd28d1bc9d38.png)

```
library(shiny)
library(ggplot2)
library(ggiraph)

# Define UI for application that draws a histogram
ui <- fluidPage(
   sidebarLayout(
      sidebarPanel(h4("Test Plot width")),
      mainPanel(
         ggiraphOutput("simplePlot", width = "100%", height = "950px")
      )
   )
)

server <- function(input, output) {
  output$simplePlot <- renderggiraph({
    plot <- ggplot(mtcars, aes(x=mpg, y=hp)) + geom_line()
    ggiraph(ggobj = plot)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by davidgohel** [comment]
The behavior you are describing is expected. 

This is documented here: 
https://davidgohel.github.io/ggiraph/articles/offcran/customizing.html#size-options

Note you are using the old functions and should use `girafe`, `renderGirafe` and `girafeOutput` instead. See documentation here: https://davidgohel.github.io/ggiraph/articles/offcran/shiny.html

KR

**Comment by sbashevkin** [comment]
Is there any way to increase the size of these plots in shiny apps? According to the size options link you referred to, plots should resize to fill the width by default, right? But from the example above (and my experience with the same problem) it seems like that is not working? Or am I misunderstanding something?

I used to add something like `tags$head(tags$style("#plotname{height:100vh !important;}"))` to the UI to ensure plots were resized to fill their container. This worked perfectly for ggiraph 0.6.1 but not with 0.7 or the developmental version 0.7.5.005. 

Thank you,
Sam

**Comment by vacon04** [comment]
Same issue here. The opts_sizing options don't really do anything. I tried installing the latest version from github but that one actually crashes shiny.

**Comment by MattCowgill** [comment]
Has anyone figure out a workaround for this? ggiraph plots don’t expand to fill the container

**Comment by davidgohel** [comment]
@MattCowgill please open a new issue and don't forget to add a reproducible example and the sessionInfo() result
