### ISSUE TITLE
defaultWidth and width for girafe not used correctly

### ISSUE THREAD

**Issue by neuwirthe** [davidgohel/ggiraph#159]
`sizingPolicy(defaultWidth(...)) ` is not being honored in the included example. The charts always have the same width.

I tested in Safari, Chrome, and Firefox.

Im I misunderstanding something or is this a bug>

```{r}
library(ggiraph)
library(tidyverse)
library(htmlwidgets)

# curl download file from github ----
xlfile <- tempfile()
curl::curl_download(
  url = paste0("https://github.com/davidgohel/budapestbi2017/",
    "blob/master/docs/ggiraph/data/", 
    "cats-vs-dogs.xlsx?raw=true"), destfile = xlfile)

# aggregate and prepare data for ggplot/ggiraph ----
data <- readxl::read_excel(xlfile) %>% 
  select(Location, `Percentage of Dog Owners`, `Percentage of Cat Owners`) %>% 
  set_names( c( "location", "dog", "cat") ) %>% 
  gather(animal, percentage, -location) %>% 
  mutate(data_id = paste0(location, animal) )
```

```{r}
gg <- ggplot( data = data, aes(x = location, y = percentage, fill = animal, 
          data_id = data_id, tooltip = percentage ) ) + 
  geom_bar_interactive(stat = "identity") + theme_minimal() +
  scale_fill_manual(values = c("#FF4136", "#FFDC00") ) + 
  labs(title = "click on bars to play cat or dog sound!") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
girafe(ggobj = gg, width_svg = 3, height_svg = 2 ) %>% 
  girafe_options(opts_hover(css="fill:#22222288;cursor:pointer;opacity:0.5;"),
                 sizingPolicy(defaultWidth = "50%"))
```

```{r}
girafe(ggobj = gg, width_svg = 3, height_svg = 2 ) %>% 
  girafe_options(opts_hover(css="fill:#22222288;cursor:pointer;opacity:0.5;"),
                 sizingPolicy(defaultWidth = "90%"))
```

```{r}
girafe(ggobj = gg, width_svg = 5, height_svg = 3 ) %>% 
  girafe_options(opts_hover(css="fill:#22222288;cursor:pointer;opacity:0.5;"),
                 sizingPolicy(defaultWidth = "50%"))
```

```{r}
girafe(ggobj = gg, width_svg = 5, height_svg = 3 ) %>% 
  girafe_options(opts_hover(css="fill:#22222288;cursor:pointer;opacity:0.5;"),
                 sizingPolicy(defaultWidth = "90%"))
```

**Comment by neuwirthe** [comment]
I investigated further and it sees the width paramter in `girafe` is not working correctly

In the following code, slightly modified from the example from the help topic,
the output goes wrong when `width` is being used.

```{r}
library(ggplot2)
library(ggiraph)

dataset <- mtcars
dataset$carname = row.names(mtcars)

gg_point = ggplot( data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname) ) +
  geom_point_interactive() + theme_minimal()

x1 <- girafe(ggobj = gg_point, width = 0.7)

x2 <- girafe(ggobj = gg_point)

```
```{r}
x1
```

```{r}
x2
```

**Comment by sigmapi** [comment]
Regarding the "width" parameter: This is passed to dsvg function and it refers to the width of the svg in inches. Default value is 6 (as is the height parameter).
0.7 is a very small value for that graph to produce a visible output. 
Try with something bigger like 2 and you'll see what I mean.

**Comment by sigmapi** [comment]
Regarding the sizingPolicy:
This is passed to (and used by) the htmlWidgets package. It is used by that (and not by ggiraph) depending on the output context.
I'm not sure what is the purpose of using it there (personally I have never used it) but if you'd like to achieve a certain width/height of the container, it'd be better to set these dierctly to the html container of the widget.

**Comment by sigmapi** [comment]
Regarding the "width" parameter, I strongly advise using "width_svg" and not "width": 
This is passed to dsvg function and it refers to the width of the svg in inches. Default value is 6 (as is the height parameter).
0.7 is a very small value for that graph to produce a visible output. 
Try with something bigger like 2 and you'll see what I mean.

**Comment by neuwirthe** [comment]
The code below does what I would like to do, but want to be able to do this without the manually written `iframe` tags and the manual fiddling with the `height` attribute in the `iframe` tag.
And also without the need to save the widget in a separate html file.

```{r}
library(ggplot2)
library(ggiraph)
library(magrittr)
library(htmlwidgets)
```
```{r}
dataset <- mtcars
dataset$carname = row.names(mtcars)
gg_point <- ggplot( data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  geom_point_interactive() + theme_minimal()

xx <- girafe(ggobj = gg_point,width_svg=5,height_svg=3)

saveWidget(xx,file="x.html")
```

First chart 

<iframe src='x.html' width='50%' height='300px' frameborder='0'></iframe>

Second chart

<iframe src='x.html' width='80%' height='500px' frameborder='0'></iframe>

**Comment by davidgohel** [comment]
The documentation is explaining sizing options here: 

https://davidgohel.github.io/ggiraph/articles/offcran/customizing.html#size-options

I assume you are working in an R Markdown document. The usage should be something like:

``````

---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggiraph)
library(magrittr)
```

```{r}
dataset <- mtcars
dataset$carname = row.names(mtcars)
gg_point <- ggplot( data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  geom_point_interactive() + theme_minimal()

xx <- girafe(ggobj = gg_point,width_svg=5,height_svg=3, options = list(opts_sizing(rescale = FALSE)))
xx
```

```{r}
xx <- girafe(ggobj = gg_point,width_svg=3,height_svg=6, options = list(opts_sizing(rescale = FALSE)))
xx
```


``````


<img width="535" alt="Capture d’écran 2020-03-04 à 18 28 13" src="https://user-images.githubusercontent.com/4331618/75905860-f1c20480-5e45-11ea-8682-53a98732a5e4.png">

**Comment by neuwirthe** [comment]
The following to charts should have the same width, but they don't

```{r}
xx <- girafe(ggobj = gg_point,width_svg=3,height_svg=2, 
             options = list(opts_sizing(rescale = FALSE)))
xx
```

```{r}
xx <- girafe(ggobj = gg_point,width_svg=3,height_svg=6, 
             options = list(opts_sizing(rescale = FALSE)))
xx
```

<img width="1045" alt="2020-03-05_01-48-58" src="https://user-images.githubusercontent.com/157619/75936828-93b41200-5e83-11ea-8cac-3564b733bdcd.png">

**Comment by davidgohel** [comment]
Thanks, indeed, this is not the expected behavior.

**Comment by neuwirthe** [comment]
What I would like to have is being able to set the aspect ratio and give the display width with in % and have it displayed without the need for a separate html file.


This 

```
xx <- girafe(ggobj = gg_point,width_svg=5,height_svg=3)
saveWidget(xx,file="x.html")
<iframe src='x.html' width='50%' height='300px' frameborder='0'></iframe>
```

also does not what I want, because the given height is used explicitly changing the aspect ratio.
And of course this needs an external file for the widget.

**Comment by davidgohel** [comment]
Something like that?

`````

---
title: "Untitled"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(ggiraph)
library(magrittr)
```

## example

```{r}
dataset <- mtcars
dataset$carname = row.names(mtcars)
gg_point <- ggplot( data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname)) +
  geom_point_interactive() + theme_minimal()

xx <- girafe(ggobj = gg_point,width_svg=5,height_svg=3, options = list(opts_sizing(width = .5)))
xx
```

`````



<img width="1102" alt="Capture d’écran 2020-03-07 à 12 09 41" src="https://user-images.githubusercontent.com/4331618/76142306-97ef5380-606c-11ea-8ab9-82825ac40b97.png">

**Comment by neuwirthe** [comment]
One further question: Is it possible to align a girafe chart left or right  instead of center?

**Comment by davidgohel** [comment]
yes, but that 's not about ggiraph. You can achieve that with HTML
