### ISSUE TITLE
Are there any good practices for >1000 points in scatterplot?

### ISSUE THREAD

**Issue by bonedi** [davidgohel/ggiraph#160]
Hello,
first of all: thanks for the greats package. 
I just wanted to render a Scatterplot with a few thousand observations, when I realised it is quite slow rendering this amount of observations. Rendering a `geom_point_interactive()` with 1000 observations will take a few seconds. But Rendering 5000 observations the same way takes more than a minute. 
Is there a way to work around this issue? I'm especially interested in the lasso selection option. 

Minimal example:
```
library(dplyr)
library(shiny)
library(ggiraph)
library(ggplot2)

ui <- shiny::fluidPage(
  numericInput('n', 'Number of Observations', value = 1000, min = 10, max = 5000),
  ggiraph::girafeOutput('plot', width = '100%', height = "800px"),
  DT::DTOutput('tab')
)

server <- function(input, output){
  df <- reactive({
    data.frame(val = rnorm(input$n),
               group = sample(LETTERS[1:5], input$n, T),
               id = 1:input$n)
  })
  plt <- reactive({
    ggplot(df(), aes(x = group, y = val)) + geom_boxplot(outlier.size = 0) + 
      geom_point_interactive(aes(data_id = id))
  })
  
  output$plot <- renderGirafe({
    start <- Sys.time()
    gg <- girafe(ggobj = plt(), options = (opts_selection(type = "multiple")),
           width_svg = 15, height_svg = 10)
    end <- Sys.time()
    print(end-start) # print on Console
    gg
  })
  
  dfsel <- reactive({
    df() %>% filter(id %in% as.numeric(input$plot_selected))
  })
  
  output$tab <- DT::renderDT({
    dfsel()    
  })
}

shiny::runApp(shiny::shinyApp(ui,server))
```

**Comment by bonedi** [comment]
Looking forward to your solution @sigmapi !

**Comment by sbashevkin** [comment]
I love this package but I've also noticed that plot rendering with ggiraph 0.7.0 is considerably slower than 0.6.1. Does this sound like the same issue? I've mostly been using geom_bar_interactive within a shiny app.

**Comment by davidgohel** [comment]
hooray for @sigmapi 

The new version is considerably faster.
Running the upper example gives:


> With new version: 

Time difference of 0.1932809 secs for 1000 points
Time difference of 3.497098 secs for 100000 points

> With previous version:

Time difference of 2.933751 secs for 1000 points
Time difference of > 60 secs for 100000 points

**Comment by bonedi** [comment]
Great, thank you!

Will this also be published in CRAN?

**Comment by davidgohel** [comment]
yes

**Comment by bonedi** [comment]
Do you know when it will be available in CRAN?
