### ISSUE TITLE
Customize naming of PNG download

### ISSUE THREAD

**Issue by bonedi** [davidgohel/ggiraph#163]
Could you add a parameter where the default filename of the downloaded plot can be set? Currently every plot is named "diagram.png".  

Also when you hover over the lasso buttons, both of them show "lasso selection". I think it is more intuitive if the red one would be named "lasso deselection".

**Comment by sigmapi** [comment]
Thanks, for reporting, both of these will be fixed.

**Comment by davidgohel** [comment]
The new version enable to set default filename of the downloaded plot, see example below:

```
library(ggplot2)

dataset <- mtcars
dataset$carname = row.names(mtcars)

gg <- ggplot(
  data = dataset,
  mapping = aes(x = wt, y = qsec, color = disp,
                tooltip = carname, data_id = carname) ) +
  geom_point_interactive() + theme_minimal()

x <- girafe(ggobj = gg, 
  options = list(opts_toolbar(pngname = "imagename")))
print(x)
```

Red button is also labeled as "lasso deselection" now.
