### ISSUE TITLE
Javascript to play audio from click event

### ISSUE THREAD

**Issue by PeterGilles** [davidgohel/ggiraph#165]
Following your example on the website using onclick in a shiny application:

````
# create an 'onclick' column
crimes$onclick <- sprintf("window.open(\"%s%s\")",
  "http://en.wikipedia.org/wiki/", as.character(crimes$state) )
````

I'd like to play instantly an audio by clicking on a symbol on the scatter plot. I've created the onlick column in my data set and referenced it to the corresponding sound file of the data point. But I am struggling with the javascript code to play the audio directly. 
window.open() will open a new browser window with the correct sound file, but this not what I want. I'd like to stay in the shiny app and play the sound file there. I also tried
````
var audio= new Audio("https://www.zzz.yy/audio/aachtafofzeg1.mp3"); audio.play()
````
but it did not work. Any hint for correct javascript code here is greatly appreciated.

**Comment by sigmapi** [comment]
Your example works fine for me. Check that the url is valid:

`p <- ggplot(mtcars, aes(wt, mpg))+
  geom_point_interactive(onclick="var audio= new Audio(\"https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3\"); audio.play();")
x <- girafe(ggobj = p)
x`

**Comment by PeterGilles** [comment]
Thank you, yes, it works now for me, too. I had a kind of type issue there.
While using `geom_point_interactive` I'd like to have symbols instead of the pure points in the plot. In my original plot I was using thus `label` to plot the corresponding symbols. 
![image](https://user-images.githubusercontent.com/3244485/78637220-3eb45300-78aa-11ea-82a7-4306d34b4d15.png)

When using this with `ggiraph` it is not possible, only the colored points are shown.

````
p <- ggplot(data=without_outliers) + 
        geom_point_interactive(aes(x = T2, y = T1, label = labels, col = next_label, 
                                  data_id = bundle, tooltip = word,
                                  onclick = onclick))
````

![image](https://user-images.githubusercontent.com/3244485/78637282-5ee41200-78aa-11ea-93a5-903a1b7cb510.png)

**Comment by sigmapi** [comment]
I'm not sure how you created the first plot, but it can't be with geom_point.
`geom_point` does not understand `label` aesthetic. It uses the `shape` aesthetic for the symbol.
`geom_text` understands the `label` aesthetic.
So try with:
```
p <- ggplot(data=without_outliers) + 
        geom_text_interactive(aes(x = T2, y = T1, label = labels, col = next_label, 
                                  data_id = bundle, tooltip = word,
                                  onclick = onclick))
```

In general, you can always create and test a ggplot2 plot as you like it and then just use the `*_interactive` geoms where appropriate for ggiraph.
Also for javascript, you can use the RStudio element inspector and check for errors in the javascript console.
