### ISSUE TITLE
uncaught exception causing plot to show wrong size

### ISSUE THREAD

**Issue by juferban** [davidgohel/ggiraph#17]
Hi, 

First of all thanks a lot for such a fantastic package. 
I have started using it in a shiny app to add some interactivity to my ggplots2 and provide the users of the tool with some extra information and it is very convenient.
Recently I noticed a small issue that I cannot seem to figure out how to solve. When I generate a plot from the first time the size of thep lot correspond to the height and width that I specify. If I change one of the variables in my interface and click on the button to re-calculate the plot this gets generated but in much smaller size. If I then maximize and minimize my browser window the plot gets to the correct size.
I checked in the javascript console and I always get a message saying _'uncaught exception: handler for message of type "plot_set" already added.'_ but apart from that I couldn't find any other reason why the plot had that weird sizing behaviour.

The only place I manage to find a "message _set" is in ggiraph.js in the code between line 94 and 110 (line 95: _Shiny.addCustomMessageHandler(el.id + "_set",_) but not sure if that could be what is triggering the issue.

My current code is quite long but will try to generate some minimal example to reproduce the issue.  

Thanks,

J.

**Comment by juferban** [comment]
Hi,

As a follow up from my previous post. I enclosed the code in ggiraph.js between lines 95 and 107 with a try catch and that seem to have solve the issue with the size of the plot.
Another side effect that I was experiencing was the the hover function was not working after I do my plot for the second time. This is also now fixed with the try catch. 

try{
            Shiny.addCustomMessageHandler(el.id + "_set",
                                          function(message) {
                                            var varname = el.id + "_selected";
                                            var variable_ = window[varname];
                                            d3.selectAll(variable_)
                                            .each(function(d, i) {
                                              d3.selectAll('#svg_' + x.canvas_id + ' *[data-id="'+ variable_[i] + '"]')
                                              .classed('selected_', false);
                                            });
                                            window[varname] = message;
                                            Shiny.onInputChange(varname, window[varname]);
                                          }
            );
            }catch(err){}

**Comment by davidgohel** [comment]
Hi,

Thanks, this shiny message handler should be a singleton, I will try to solve that without the `try` first.

**Comment by juferban** [comment]
Hi David,

Thanks a lot for the answer and great to hear you are looking into it. I understand that the try catch approach is more of a hack than a "valid" solution, unfortunately I don't have much experience with javascript to be able to offer much help.

I'll look forward to your update.

Thanks a great for such an useful packaged.

Julio

**Comment by davidgohel** [comment]
Hi,

exception issue is solved but the resizing is another issue. I will let you know when solved.

David

**Comment by davidgohel** [comment]
I think resizing issue is solved now. Could you have a try?

David

**Comment by juferban** [comment]
Hi David,

I just installed your latest version and gave it a try. Both issues that I was experiencing seem to be solved now.

Thanks a lot for taking a look into it and for fixing them so quickly.

Best regards,

Julio

**Comment by davidgohel** [comment]
thanks
