### ISSUE TITLE
Can't install ggiraph 0.7.8

### ISSUE THREAD

**Issue by jcverah** [davidgohel/ggiraph#172]
Hello,

I'm geeting some problems in my app when switching from 0.7.0 to 0.7.8 in the shiny server.
I'm trying to install ggiraph 0.7.8 in my local environment in order to solve the problem but I can't.

* installing *source* package 'ggiraph' ...
** package 'ggiraph' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/jcvera/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/jcvera/Documents/R/win-library/3.6/gdtools/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
sh: c:/Rtools/mingw_32/bin/g++: No such file or directory
make: *** [C:/PROGRA~1/R/R-36~1.2/etc/i386/Makeconf:215: RcppExports.o] Error 127
ERROR: compilation failed for package 'ggiraph'
* removing 'C:/Users/jcvera/Documents/R/win-library/3.6/ggiraph'
* restoring previous 'C:/Users/jcvera/Documents/R/win-library/3.6/ggiraph'
Warning in install.packages :
  installation of package ‘ggiraph’ had non-zero exit status

Can you please help with this?

Thank you very much.

**Comment by davidgohel** [comment]
Hello,

You are on R 3.6, it needs to compile the source as the binary for r-oldrel s not yet built.

You can install RTools https://cran.r-project.org/bin/windows/Rtools/ to be able to compile source with R but my advice is to wait few days so that CRAN has time to build the package and your installation will be easier.

**Comment by davidgohel** [comment]
Closing that issue as all binaries have been build for windows
