### ISSUE TITLE
Enhanced Tooltips

### ISSUE THREAD

**Issue by mrworthington** [davidgohel/ggiraph#175]
## Feature Request - Enhanced Tooltips

Hi! First of all, I want to compliment the work y'all have done with ggiraph. It's amazing and feels like R just keeps getting. I had no idea about `geom_sf_interactive()` but have been looking for alternatives to leaflet. That said, I've been able to get a fairly clean looking `geom_sf()` object to work with ggiraph, but am wondering if there's a way to improve the tooltips for all interactive geoms. It could be that it exists, I just couldn't find it in the documentation nor could I find a way to make it work by tinkering with the tooltip argument inside of the geom's `aes()` function.

Here's a screenshot of my chart. I was able to get Google Fonts working in a standalone output and I was able to get the tooltip working, I just couldn't find a way to add more context to the tooltip. While I read the documentation and realize there's ways to improve the CSS (and didn't have any trouble playing with that), I was at a loss as to how to add more information to the tooltip.

**The idea I had about enhancing it** would be to incorporate something along the lines of a [`gt()`](https://gt.rstudio.com) object that gets read into the tooltip argument. Given that I'm not familiar with y'alls code, I'm not certain if this is even possible. I was just trying to think along the lines of how detailed [tooltips and popups](https://rstudio.github.io/leaflet/popups.html) are built in packages like `leaflet`, where functions for the tooltip are written outside of functions like `addPopups()` or `addPolygons()`. 

The amazing thing about y'alls package is that this wouldn't just apply to spatial graphics, but other kinds of visualizations.

### Screenshot of my geom_sf_interactive()

![Screen Shot 2020-07-16 at 1 30 39 PM](https://user-images.githubusercontent.com/8171106/87719663-8e879d80-c768-11ea-835d-38375892ba33.png)

### Examples of Detailed Tooltips/Popups

[Link to Leaflet with Detailed Tooltip ](https://texas-2036.github.io/Texas-Diversity-Growth/tx_diversity_map_alt.html)

[Texas Tribune Hospitalization Chart ](https://apps.texastribune.org/features/2020/texas-coronavirus-cases-map/?_ga=2.53861675.2052076661.1594878483-1467282683.1593418604)

![Screen Shot 2020-07-16 at 1 17 02 PM](https://user-images.githubusercontent.com/8171106/87721018-a829e480-c76a-11ea-8c19-e445bf92ef91.png)

[New York Time US COVID Cases Map](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html?action=click&module=Top%20Stories&pgtype=Homepage)

![Screen Shot 2020-07-16 at 1 18 21 PM](https://user-images.githubusercontent.com/8171106/87721927-18853580-c76c-11ea-9e1b-5ed054923ad9.png)

## Code For Map Produced with My Example

```
library(ggiraph)
library(tidyverse)
library(gfonts)

ts_county_cases <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

sf_counties <- tidycensus::county_laea
ts_county_cases_sf <- ts_county_cases %>% 
  filter(date=="2020-03-27",
         state=="Texas") %>% 
  left_join(sf_counties, by=c("fips"="GEOID")) %>% 
  sf::st_as_sf()

setup_font(
  id = "roboto",
  output_dir = "www",
  variants = "regular"
)

generate_css("roboto", "regular", font_dir = "path/to/font")
use_font("roboto", "www/css/roboto.css")

tx_map <- ts_county_cases_sf %>%
  ggplot() +
  geom_sf(data=sf_counties %>% filter(str_detect(GEOID,"48")),color="#dddddd", fill="#f2f2f2", lwd=.3) +
  geom_sf_interactive(aes(fill=cases, tooltip=cases, data_id = county), lwd=.3) +
  scale_fill_gradientn(colours = tinter("#5da5da", steps = 5), labels = function(x) paste0(x,"Cases")) +
  coord_sf(datum=NA) +
  hrbrthemes::theme_ipsum_es(base_family="Roboto") +
  theme(plot.title = element_text(family="Roboto", face = "bold"),
        plot.subtitle = element_text(family="Roboto", face = "plain"),
        plot.caption = element_text(family="Roboto", face = "plain")) + 
  labs(title="Confirmed COVID-19 Cases By County - Texas",
       subtitle="As of March 26th, 2020",
       caption="SOURCE: New York Times COVID-19 Database")

girafe(ggobj = tx_map, fonts = list(sans = "Roboto"), width_svg = 12, height_svg = 8,
       options = list(
         opts_hover_inv(css = "opacity:0.5;"),
         opts_hover(css = "stroke-width:2;")
       ))
```

## Idea for gt() implementation

While this code doesn't work, I'm wondering if it's possible to do some kind of implementation like shiny that looks like this. Open to other ideas. I just know @rich-iannone and others have made gt() really flexible and useful for a lot of applications!

```
library(gt)

tooltip_table <-
  ts_county_cases_sf %>%
    # filter(county==input$county) %>% 
        gt() %>%
        tab_header(title = paste0("COVID-19 in ", input$county, " County")) %>%
        cols_hide(contains(c("geometry","state","fips"))) %>%
        cols_label(county=md("**County**"),
                   date=md("**Date**"),
                   cases=md("**Cases**"),
                   deaths=md("**Deaths**"))

tx_map <- ts_county_cases_sf %>%
  ggplot() +
  geom_sf(data=sf_counties %>% filter(str_detect(GEOID,"48")),color="#dddddd", fill="#f2f2f2", lwd=.3) +
  geom_sf_interactive(aes(fill=cases, tooltip = tooltip_table, data_id = county), lwd=.3) 

```

**Comment by davidgohel** [comment]
I don't know if possible with gt package, I supposed it is but don't know how. 

You can use package flextable to have nice tables within ggiraph's tooltips: 

* https://davidgohel.github.io/flextable/
* https://github.com/davidgohel/flextable


To see an example, you can try this app: https://github.com/ardata-fr/municipales-paris. The code is not well documented, I will try to add a simpler example in this thread later. 

<img width="631" alt="Capture d’écran 2020-07-17 à 15 02 05" src="https://user-images.githubusercontent.com/4331618/87788948-88fc8700-c83e-11ea-9e34-4ce34e257e9b.png">


You need to call `as.character(flextable::htmltools_value(your_flextable_object))` to get a string representation of the flextable.

**Comment by mrworthington** [comment]
Hey. This is awesome. I'm not as familiar with the flextable package, but I do know know that gt has an [`as_raw_html()`](https://gt.rstudio.com/reference/as_raw_html.html) export option, which I imagine functions in the same way. By default, if you're writing a gt object in an RMarkdown code chunk, you don't need to use that function, so I imagine it's for generating html in situations like this. 

In any event, would love to see any doc you have about using flextable and I'll see if I can replicate the flextable process with that function in gt. And I will definitely check this repo out. 

Anyway, thanks for this package. Excited to see where it heads and how I can help.

**Comment by davidgohel** [comment]
Yes, this is the same

Here is a dummy example:

<img width="601" alt="Capture d’écran 2020-07-18 à 13 29 53" src="https://user-images.githubusercontent.com/4331618/87851628-cf172080-c8fa-11ea-8f20-b2917c8eddf8.png">


```
library(ggiraph)
library(tidyverse)
library(gfonts)
library(flextable)
library(tinter)

ts_county_cases <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

sf_counties <- tidycensus::county_laea
ts_county_cases_sf <- ts_county_cases %>% 
  filter(date=="2020-03-27",
         state=="Texas") %>% 
  left_join(sf_counties, by=c("fips"="GEOID")) %>% 
  sf::st_as_sf()

# flextable part -----
fun_flextable <- function(dat){
  ft <- flextable(dat, col_keys = c("county", "cases", "deaths"), 
                  defaults = list(fontname = "Roboto") )
  ft <- bold(ft, part = "header", bold = TRUE)
  ft <- color(ft, color = "orange", part = "all")
  ft <- set_table_properties(ft, layout = "autofit")
  as.character(htmltools_value(ft))
}
temp_dat <- as.data.frame(ts_county_cases_sf)[,c("county", "cases", "deaths")]
temp_dat <- split(temp_dat, seq_len(nrow(temp_dat)))
ts_county_cases_sf$tooltip <- map_chr(temp_dat, fun_flextable)
# end of flextable part

tx_map <- ts_county_cases_sf %>%
  ggplot() +
  geom_sf(data=sf_counties %>% filter(str_detect(GEOID,"48")),color="#dddddd", fill="#f2f2f2", lwd=.3) +
  geom_sf_interactive(aes(fill=cases, tooltip=tooltip, data_id = county), lwd=.3) +
  scale_fill_gradientn(colours = tinter("#5da5da", steps = 5), labels = function(x) paste0(x,"Cases")) +
  coord_sf(datum=NA) +
  hrbrthemes::theme_ipsum_es(base_family="Roboto") +
  theme(plot.title = element_text(family="Roboto", face = "bold"),
        plot.subtitle = element_text(family="Roboto", face = "plain"),
        plot.caption = element_text(family="Roboto", face = "plain")) + 
  labs(title="Confirmed COVID-19 Cases By County - Texas",
       subtitle="As of March 26th, 2020",
       caption="SOURCE: New York Times COVID-19 Database")

girafe(ggobj = tx_map, fonts = list(sans = "Roboto"), width_svg = 12, height_svg = 8,
       options = list(
         opts_tooltip(css = "padding:5px;background:white;border-radius:2px 2px 2px 2px;"),
         opts_hover_inv(css = "opacity:0.5;"),
         opts_hover(css = "stroke-width:2;")
       ))
```

> In any event, would love to see any doc you have about using flextable

This is the link I provided upper: https://davidgohel.github.io/flextable/index.html. (you can click on items on the top menu, it brings you to corresponding pages)

<img width="1228" alt="Capture d’écran 2020-07-18 à 13 27 13" src="https://user-images.githubusercontent.com/4331618/87851652-0be31780-c8fb-11ea-8fe3-063a8c333ec1.png">

**Comment by mrworthington** [comment]
This is awesome and amazing. Thank you very much! I'm gonna have to look into flextable!

**Comment by Ari04T** [comment]
Sorry to reopen this thread. I just wanted to ask if this is still working or if something has changed? I tried running the example provided by David but I only get this

![image](https://user-images.githubusercontent.com/7259598/115795438-ee693f80-a39d-11eb-81da-7774a52d5661.png)

As you can see, the tooltip is completely empty so I don't know if something has changed with the package or if it's a problem with my system.

Thanks!

**Comment by davidgohel** [comment]
This is flextable that changed. Now tables are using shadow dom. 

Is it a real need or are you only trying example codes?

**Comment by Ari04T** [comment]
Ah makes sense. I was trying to integrate flextable with ggiraph for a real application. Right now my fix was to use the as_raw_html() function from the gt package since it just produces the <table> object.

**Comment by davidgohel** [comment]
@Ari04T I'm confused, you don't run the above example if you use gt?

**Comment by Ari04T** [comment]
> 
> 
> @Ari04T I'm confused, you don't run the above example if you use gt?

Sorry for the confusion. Yes, I ran the above example with the code that you wrote last year (with flextable) and the result is the empty tooltip that I show in the image. Since I couldn't get to use flextable to get an enhanced tooltip, I switched to gt and used the following code

```
ts_county_cases_sf<- ts_county_cases_sf%>% 
  nest(data = c(county, cases, deaths)) %>%  
  mutate(tooltip = map(data, ~ as_raw_html(gt(.x))),
         tooltip_clean = str_replace_all(tooltip, "\\\n" , "")) %>% 
  unnest()
```
This basically does the same as the example you used for the flexatable code, but with the gt as_raw_html function that creates the table HTML object. I had to use the str_replace_all function to remove all the line breaks since ggiraph was showing a ton of empty space at the top of the tooltip because of them.

**Comment by py9mrg** [comment]
Just as a side note to this issue, you can indeed use `gt::as_raw_html()` or any package that will produce an html table (or even a manual one). But the quirky thing I notice is that the table is always bottom aligned in an oversized container? 

``` r
library(ggplot2)
library(ggiraph)

# manual table
test_tbl <- '<table style="text-align:right">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td>
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td>
    <td>94</td>
  </tr>
</table>'

dataset <- mtcars
dataset$carname = row.names(mtcars)

gg_point = ggplot(data = dataset) +
  geom_point_interactive(aes(x = wt, y = qsec, color = disp,
                             tooltip = test_tbl, data_id = carname)) + theme_minimal()

x <- girafe(ggobj = gg_point)
x
```

![Untitled](https://user-images.githubusercontent.com/12600721/116398962-4a114e00-a820-11eb-842e-70f499d9c3a1.png)

``` r
# gt table
test_tbl2 <- gt::as_raw_html(gt::gt(dataset[1:3, 1:3]))

gg_point2 = ggplot(data = dataset) +
  geom_point_interactive(aes(x = wt, y = qsec, color = disp,
                             tooltip = test_tbl2, data_id = carname)) + theme_minimal()

x2 <- girafe(ggobj = gg_point2)
x2
```

![Untitled2](https://user-images.githubusercontent.com/12600721/116398983-509fc580-a820-11eb-93b8-94de82fe38ce.png)

**Comment by sigmapi** [comment]
I think this is a bug: The empty space above is a lot of <br/> tags.
It's happening because in the tooltip text, we replace newline chars with the break tag, which in your case are pushed above.

**Comment by py9mrg** [comment]
Aaaaah I see. For me it's not really a problem, as I can get pretty much what I want with some careful use of `paste0`, but just thought I'd highlight the quirk as I happened to notice it just before stumbling across this issue.

**Comment by Ari04T** [comment]
@sigmapi Yes, right now the best way to fix it is to remove the line breaks ("\n") with gsub or str_replace_all and that way the empty space is removed from the tooltip
```
ts_county_cases_sf<- ts_county_cases_sf%>% 
  nest(data = c(county, cases, deaths)) %>%  
  mutate(tooltip = map(data, ~ as_raw_html(gt(.x))),
         tooltip_clean = str_replace_all(tooltip, "\\\n" , "")) %>% 
  unnest()
```
In my case I like to use the tidyverse and go with a nested workflow approach but at the end of the day as long as the line breaks are removed then the tooltip works as expected.

**Comment by sigmapi** [comment]
Ok, the issue is fixed now. Updated documentation for `tooltip` interactive parameter:

> To use html markup it is advised to use htmltools::HTML() function in order to mark the text as html markup. If the text is not marked as html and no opening/closing tags were detected, then any existing newline characters (`\r\n`, `\r` and `\n`) are replaced with the `<br/>` tag.

So, the above code will work fine now.
Function 'gt::as_raw_html' already marks the text as html, and no character replacement is required.
The first example with manual table will work as well, because ggiraph will detect that it's markup.

But as general rule, always use htmltools::HTML() to wrap the text for tooltip , if it's already in html markup.

**Comment by sigmapi** [comment]
@Ari04T thanks, no need for workarounds now

**Comment by davidgohel** [comment]
@Ari04T flextable has been updated so that this code work again. Note `htmltools_value(ft, ft.shadow = FALSE)`, `ft.shadow = FALSE` is the option to set to FALSE to display flextable in a ggiraph tooltip


```
library(ggiraph)
library(tidyverse)
library(gfonts)
library(flextable)
library(tinter)
library(hrbrthemes)
library(tidycensus)

ts_county_cases <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")

sf_counties <- tidycensus::county_laea
ts_county_cases_sf <- ts_county_cases %>% 
  filter(date=="2020-03-27",
         state=="Texas") %>% 
  left_join(sf_counties, by=c("fips"="GEOID")) %>% 
  sf::st_as_sf()

# flextable part -----
fun_flextable <- function(dat){
  ft <- flextable(dat, col_keys = c("county", "cases", "deaths"), 
                  defaults = list(fontname = "Roboto") )
  ft <- bold(ft, part = "header", bold = TRUE)
  ft <- color(ft, color = "orange", part = "all")
  ft <- set_table_properties(ft, layout = "autofit")
  as.character(htmltools_value(ft, ft.shadow = FALSE))
}
temp_dat <- as.data.frame(ts_county_cases_sf)[,c("county", "cases", "deaths")]
temp_dat <- split(temp_dat, seq_len(nrow(temp_dat)))
ts_county_cases_sf$tooltip <- map_chr(temp_dat, fun_flextable)
# end of flextable part

tx_map <- ts_county_cases_sf %>%
  ggplot() +
  geom_sf(data=sf_counties %>% filter(str_detect(GEOID,"48")),color="#dddddd", fill="#f2f2f2", lwd=.3) +
  geom_sf_interactive(aes(fill=cases, tooltip=tooltip, data_id = county), lwd=.3) +
  scale_fill_gradientn(colours = tinter("#5da5da", steps = 5), labels = function(x) paste0(x,"Cases")) +
  coord_sf(datum=NA) +
  hrbrthemes::theme_ipsum_es(base_family="Roboto") +
  theme(plot.title = element_text(family="Roboto", face = "bold"),
        plot.subtitle = element_text(family="Roboto", face = "plain"),
        plot.caption = element_text(family="Roboto", face = "plain")) + 
  labs(title="Confirmed COVID-19 Cases By County - Texas",
       subtitle="As of March 26th, 2020",
       caption="SOURCE: New York Times COVID-19 Database")

girafe(ggobj = tx_map, fonts = list(sans = "Roboto"), width_svg = 12, height_svg = 8,
       options = list(
         opts_tooltip(css = "padding:5px;background:white;border-radius:2px 2px 2px 2px;"),
         opts_hover_inv(css = "opacity:0.5;"),
         opts_hover(css = "stroke-width:2;")
       ))

```



<img width="563" alt="Capture d’écran 2021-05-01 à 10 42 18" src="https://user-images.githubusercontent.com/4331618/116776660-e8442480-aa69-11eb-9890-1cf09c3f26d5.png">
