### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by Evanleen** [davidgohel/ggiraph#179]
Hi David,

I'm a big fan of your package and I've used it in a shiny app that I made. Everything is fully working for me however unfortunately the first rending of the plots can be really slow is you're plotting more points  (~5s for 1000 points ~30s for 3000 points). Would you have any suggestions on how to speed this up?

Thank you in advance

Eric

**Comment by sigmapi** [comment]
Is this still occurring? 
Performance has been improved a lot in ggiraph so I'm surprised with these numbers.
See https://github.com/davidgohel/ggiraph/issues/160#issuecomment-609032990
