### ISSUE TITLE
tooltip fails hard if newline in text

### ISSUE THREAD

**Issue by rubenarslan** [davidgohel/ggiraph#18]
Basically, if there is a newline in the text for the tooltip, no tooltips are displayed, the JS console throws a parsing error. Should probably escape all such user input.
## Reproduce

```
library(ggiraph)

dataset <- mtcars
dataset$tooltip <- row.names(dataset)
dataset$tooltip[1] = "new\nline" ## add newline
gg_point_1 <- ggplot(dataset, aes(x = disp, y = qsec, 
        color = wt, tooltip = tooltip ) ) + 
    geom_point_interactive(size=3) + gg_th

ggiraph(code = {print(gg_point_1)}, width = "400px", height = "400px")
```

If I change the third line to this:  

```
dataset$tooltip[1] = "new\\nline" ## add newline
```

it works, but the newline isn't shown.

**Comment by davidgohel** [comment]
Hi,

tooltips are html chunks, using corresponding html tag instead of `\n` is working:

```
dataset$tooltip[1] = "new<br/>line" ## add newline
```

**Comment by rubenarslan** [comment]
Ah good to know! I know what to do then. But still, you should probably escape " and \n by default?

**Comment by davidgohel** [comment]
Maybe `\n` but not `"`. 

`'` are not allowed and `"` could be used for many reasons, e.g. `dataset$tooltip[1] = "<span style=\"color:red;\">hello</span>"`
