### ISSUE TITLE
Feature request: make the interactive part of geom_line_interactive the data points of the line rather than the whole line

### ISSUE THREAD

**Issue by betsisliz** [davidgohel/ggiraph#186]
Thank you for this awesome package. We want to implement it for our interactive plots. However, currently there is an issue for time series analysis because using geom_line_interactive applies to the whole line rather than data points on the line. That is, the tool tip gives an average value for the whole line and doesn't change as you point to different parts of the line. This can be overwritten with a point layer but we have yet to find a way to hide the points. This is highly impractical for data with high frequency and not visually pleasing in most cases. 

Is there an existing workaround? I have failed to find a suitable solution. This would be a great feature.

Thank you.

**Comment by sigmapi** [comment]
Hi, this is not feasible at the moment. A point layer must be used for displaying tooltips with point data.
If you don't want the points to be visible, you can easily hide them by setting the alpha value on the point layer to be small enough so that a point is drawn but it's practically invisible. 

Here is an example with time series data:

```
library(ggplot2)
library(ggiraph)

gg <- ggplot(economics, aes(x = date, y = unemploy)) +
  geom_line() +
  geom_point_interactive(aes(tooltip = pop, data_id=paste0(date,unemploy)), alpha = 0.005)
x <- girafe(ggobj = gg)
x <- girafe_options(x, opts_hover(css = "fill:orange;fill-opacity:1;r:3") )
print(x)
```

**Comment by betsisliz** [comment]
Thank you for the very prompt reply.


On Feb 10, 2021, at 10:10 AM, Panagiotis Skintzos <notifications@github.com> wrote:

﻿

Hi, this is not feasible at the moment. A point layer must be used for displaying tooltips with point data.
If you don't want the points to be visible, you can easily hide them by setting the alpha value on the point layer to be small enough so that a point is drawn but it's practically invisible.

Here is an example with time series data:

library(ggplot2)
library(ggiraph)

gg <- ggplot(economics, aes(x = date, y = unemploy)) +
  geom_line() +
  geom_point_interactive(aes(tooltip = pop, data_id=paste0(date,unemploy)), alpha = 0.005)
x <- girafe(ggobj = gg)
x <- girafe_options(x, opts_hover(css = "fill:orange;fill-opacity:1;r:3") )
print(x)
