### ISSUE TITLE
Tooltip is only showing once but not after action button is pressed

### ISSUE THREAD

**Issue by shehwana** [davidgohel/ggiraph#19]
Hi David
Thanks for very nice package. I am developing a shiny app and i want little guidance in following issues. Shiny code is at the end of my comment. 
1) Tooltip shows first but if you change something and try to update the plot, next time it does not show tooltip
2)If i try to modify graph, not only tooltip disappear but graph size changes as well.
(Code to show first two issues is at the end of my comment)
3) I could not produce example of this problem but actually i am coding for web application having multiple tab panels and it takes few seconds (almost 30 seconds) to complete execution and plot to show up. While shiny is busy, If i go to any other tab and come back to graph tab, graph does not show up (even if execution is finished) unless i press update button in that case i can see graph but again without tool tip. NOTE: Using only ggplot and changing tab does not cause this problem.

```
# UI.R
library(shiny)

shinyUI(navbarPage(useShinyjs(), id='navbar',position='static-top',
                   tabPanel('Home',
                            fluidRow(
                             column(3,  radioButtons("xaxis", "x axis on plot",list('disp',"hp",'drat','wt',"qsec"),selected="disp"),
                                        actionButton(inputId = 'start', label = 'update', icon = NULL)
                                     ),
                             column(9,
                                        ggiraph::ggiraphOutput("plot1",width='800px',height='800px')
                                    )   #column
                            ) #fluidrow
                              
                        ) #tabpanel home
                       
                   ) #shinyUI
    )


# Server.R
library(rvg)
library(xml2)
library(igraph)

toplot<-function(datatoplot,xxx)
{
  datatoplot$description=rownames(datatoplot)
  plotteddata=ggplot()+geom_point_interactive(data=datatoplot,aes(x= get(xxx),y= mpg,tooltip=description),alpha=0.8,size=2,colour='blue') 
  return(plotteddata)
}


##############################################################################################################################################

shinyServer(function(input, output, session) {
data=mtcars
  plot_react<- reactive({
    toplot(data,input$xaxis)
  })
  
  
  output$plot1 <-renderggiraph({
   input$start
    isolate({
            ggiraph(code = print(plot_react()), zoom_max = 1,hover_css = "stroke:#ffd700;cursor:pointer;", selected_css = "fill:#fe4902;stroke:#ffd700;")
            })
          })
  
})

```

**Comment by davidgohel** [comment]
Hi,

I think the modification I made yesterday for issue #17 should solve most of your issue.
Could you try it?

```
devtools::install_github("davidgohel/ggiraph")
```


For the resize issue, there is still work to do but I need to spend more time on this subject (not before next week)

David

**Comment by shehwana** [comment]
Thanks David. Yeah most of the problem is solved.

**Comment by davidgohel** [comment]
cool, 

I will close this ticket when sizing policy will be better managed.

**Comment by davidgohel** [comment]
Hi 

Sizing policy has been improved. It should be better now.

David
