### ISSUE TITLE
Left-align SVG inside widget element

### ISSUE THREAD

**Issue by petrbouchal** [davidgohel/ggiraph#190]
I *think* this is a feature request and has not been specifically discussed before but it may be I am missing something obvious:

I am trying to left-align ggiraph widgets so they are aligned in the same way in Rmarkdown HTML output as regular plots. However the htmlwidget produced by `girafe()` is center-aligned inside its parent element - here is a reprex Rmarkdown doc:

~~~
---
title: "GGiraph alignment"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggiraph)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ggo <- ggplot(mpg) +
  geom_point(aes(cty, hwy))
```

```{r}
ggi <- girafe(ggobj = ggo, width_svg = 3,
              options = list(opts_sizing(rescale = FALSE, 
                                    width = 1)))
ggi
```
~~~

and here is what I see:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/1666657/110642276-2aac5c00-81b3-11eb-8394-f9dfbda1f079.png">

I haven't found a simple way to properly align the left edge to the left to make the alignment the same as regular plots in Rmarkdown. The only way is using a hint from [this SO post](https://stackoverflow.com/questions/39562947/how-to-arrange-html-widgets-inside-of-a-rmarkdown-document-pdf-html) and also manually reducing the htmlwidget's padding:

~~~
```{r}
ggi <- girafe(ggobj = ggo, width_svg = 3,
              options = list(opts_sizing(rescale = FALSE, 
                                    width = 1)))

ggi$sizingPolicy$padding <- 0
```

<script>
  $(document).ready(function() {
    $('.girafe').css('float','left');
  });
</script>

```{r}
ggi
```
~~~

Then I see:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/1666657/110644057-fe91da80-81b4-11eb-819e-666d8f987dca.png">

If I've missed an obvious way to achieve this, would it be worth including the solution in the documentation? It just seems like a long journey to having a uniform look with standard plots. (I noticed that in #159 you responded that this can be achieved via HTML. I tried wrapping the code chunk in `<div style = "float: left;">` but that also applies to the code block if `echo = TRUE`).

Moreover, this workaround is not available when saving a widget to a standalone HTML file via `saveWidget()`.

**Comment by sigmapi** [comment]
Hi, the centered alignment of the widget occurs because by default the container div of the output, with class `.girafe_container_std` has the `text-align` css property set to `center`.
To easily override this without js manipulation is to include a custom css file and override the t`ext-align` property:

Create a css file (for example custom.css, in the same location as the Rmd document) with contents: 
```
.girafe_container_std {
  text-align: left;
}
```

And add the file to the Rmd document:
```
---
title: "GGiraph alignment"
output: html_document
css: custom.css
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggiraph)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ggo <- ggplot(mpg) +
  geom_point(aes(cty, hwy))
```

```{r}
ggi <- girafe(ggobj = ggo, width_svg = 3,
              options = list(opts_sizing(rescale = FALSE, 
                                    width = 1)))
ggi
```
```

You should see the desired result

**Comment by petrbouchal** [comment]
Thank you @sigmapi! That does work.
