### ISSUE TITLE
Feature request: Add geom_dotplot_interactive

### ISSUE THREAD

**Issue by knutwannheden** [davidgohel/ggiraph#192]
It would be really nice with an interactive version of `geom_dotplot` to allow displaying a label when hovering over a dot or also a clickable link for the dots.

**Comment by knutwannheden** [comment]
Are there any more details or information I can provide? I am completely new to the R universe, but I will do my best.

**Comment by davidgohel** [comment]
Sorry, you do not have an answer because we could not work on your request due to lack of available time. 

This has nothing to do with your R experience but with the availability in our schedule for open source work on ggiraph :)

**Comment by knutwannheden** [comment]
Thanks for your feedback! I would be willing to invest some of my own time here, if you can point me to some modules which should be similar. I think all I need is support for the `tooltip`, `onclick`, and `data_id` aesthetics.

**Comment by davidgohel** [comment]
This repo contains the source of the R package. You can look for `geom_` and see other implementations

**Comment by knutwannheden** [comment]
I took a brief look at the code and added the obvious missing pieces, but that wasn't enough to get it to work. It looks like I need a better understanding of R as a language, the tooling (debugger etc.) and also the libraries `ggplot2` and `ggiraph` to be able to implement this on my own.

**Comment by davidgohel** [comment]
Hi @knutwannheden 

Thanks, we implemented the new function `geom_dotplot_interactive`.

**Comment by knutwannheden** [comment]
Wow, that's great news! Thank you very much for taking the time!
