### ISSUE TITLE
ggtext and ggiraph on distill: letters are overlapping on mobile device

### ISSUE THREAD

**Issue by werkstattcodes** [davidgohel/ggiraph#193]
Hello,

I am producing a `ggiraph `plot with a colored word in the title. The color is added by using the `ggtext `package. The plot is part of a blog post on `distill`. The plot looks fine, however, when seeing the plot on a mobile device the letters are overlapping.

I tried to isolate the issue [here](https://distill-test-drive.netlify.app/post/2021-03-16-ggiraph-ggtext-problem/) (incl. code):

I don't know whether this is due to ggtext, ggiraph or a combination of both etc. I also placed an [issue](https://github.com/wilkelab/ggtext/issues/62) with the author of ggtext and pertaining questions - with appropriate pause - on [SO](https://stackoverflow.com/questions/66664411/font-distorted-when-viewing-graph-on-mobile-device), [Slack](https://rfordatascience.slack.com/archives/C8JRJSW4S/p1616749139075500), and [RStudio Community](https://community.rstudio.com/t/letters-in-plot-title-overlap-when-viewed-on-mobile-device/100221). However, all remained without a n answer. Many thanks.

Screenshot from laptop:
![laptop_screenshot](https://user-images.githubusercontent.com/9595585/111608206-3f9f7580-87d9-11eb-9868-80be953d6538.png)

Screenshot from mobile device:
![mobile_screenshot](https://user-images.githubusercontent.com/9595585/111608515-95741d80-87d9-11eb-9534-86b5c1b46b23.png)

**Comment by davidgohel** [comment]
Hello,

I think you are in the case where you did not add the font in the web page and your phone does not have it (your computer have it, so it displays as expected)

See 

https://davidgohel.github.io/ggiraph/articles/offcran/customizing.html#fonts-1

Could you try with the font settings specified as in the example of the link?

**Comment by davidgohel** [comment]
Closing the issue - will open again if necessary
