### ISSUE TITLE
trigger js with onhover, onenter, onexit?

### ISSUE THREAD

**Issue by ssp3nc3r** [davidgohel/ggiraph#194]
Thanks for the helpful package! 

I like the ability to trigger javascript with the onclick. Would it be a lot to add that functionality to on hover, on enter, onexit events? Or maybe it's already available and I missed it in the docs.

**Comment by davidgohel** [comment]
If you are in a shiny context, you can have click and hover:

```
run_girafe_example("gender")
```

In a static HTML page (rmarkdown for example), only onclick is implemented for now.

Could you be more specific with your need?

**Comment by ssp3nc3r** [comment]
I'm making stand-alone html document, and have an on click event trigger a js function that loads a video, but I'd like to trigger that function when entering a shape instead of waiting to click, if that makes sense?

**Comment by sigmapi** [comment]
I think this goes out of the scope of ggiraph.
However you can achieve this with the current github version by setting functions `onmouseenter` and `onmouseleave` as extra interactive parameters, by using the new `extra_interactive_params` argument:

```
library(ggplot2)
library(ggiraph)

mtcars$carname <- rownames(mtcars)
# plots
gg_point = ggplot(data = mtcars) +
  geom_point_interactive(
    aes(
      x = wt, y = qsec, color = disp,
      tooltip = carname, data_id = carname,
      onmouseenter = paste('console.log("Entering point: ', carname, '");'),
      onmouseleave = paste('console.log("Leaving point: ', carname, '");')
    ), 
    extra_interactive_params = c("onmouseenter", "onmouseleave")
  ) + theme_minimal()

x <- girafe(ggobj = gg_point)
if( interactive() ) print(x)
```
