### ISSUE TITLE
Problem of system font detection with gdtools::font_family_exists ?

### ISSUE THREAD

**Issue by BriceNocenti** [davidgohel/ggiraph#198]
Hi, 

I’ve got a problem with some fonts in `ggiraph`, namely "DejaVu Sans Condensed" : it works in the tooltips with css, but not as the general font for text elements in the plot itself (set with the `fonts` argument of `girafe`, passed to `dsvg`). And in fact, I don’t find it with `gdtools::font_family_exists("DejaVu Sans Condensed")`. With `gdtools::sys_fonts()`, I found something interesting : "DejaVu Sans Condensed" exists, but the "family" name is simply "Deja Vu Sans", and the "Condensed" part went to "style" (while on the medatada of this font in my computer, using Windows, the font family name is "DejaVu Sans Condensed"). I don’t know if it’s normal behavior (then, where to specify the Condensed style to use it in ggiraph ?), or if it’s a problem with the system font detection algorithm. If I’m not clear, I can also open a subject is StackOverflow with reproducible code. 

Thanks,

**Comment by davidgohel** [comment]
We improved the font management by using systemfonts.

In your case, you would have to use the following code:

```
library(ggplot2)
library(ggiraph)
library(systemfonts)
library(dplyr)
condensed <- 
  system_fonts() %>% 
  filter(
    family %in% "DejaVu Sans", 
    grepl("condensed", style, ignore.case = TRUE))

register_font(
  "DejaVu Sans Condensed", 
  plain = list(filter(condensed, !weight %in% "bold", italic) %>% pull(path), 0), 
  bold = list(filter(condensed, weight %in% "bold", !italic) %>% pull(path), 0), 
  italic = list(filter(condensed, !weight %in% "bold", !italic) %>% pull(path), 0),
  bolditalic = list(filter(condensed, weight %in% "bold", italic) %>% pull(path), 0)
)
dat <- mtcars
dat$carname <- row.names(dat)
gg <- ggplot(dat, aes(drat, carname)) + 
  geom_point() + 
  geom_text(data = sample_n(dat, 3), aes(label = "coco"), family = "Arial")+
  theme_minimal(base_family = "DejaVu Sans Condensed") + 
  theme(axis.title = element_text(face = "bold"),
        axis.text.x = element_text(face = "italic"),
        axis.text.y = element_text(face = "bold")
  ) 
ggiraph(ggobj = gg) %>% print()
```


However, you should also declare/create new font faces to embed the font "DejaVu Sans Condensed" in the web page. For example, the font is not found on Rstudio Viewer

<img width="533" alt="Capture d’écran 2021-04-30 à 18 30 03" src="https://user-images.githubusercontent.com/4331618/116725352-1a11a880-a9e2-11eb-977f-47cc257542c9.png">

but is available from Chrome browser (on my machine).

<img width="876" alt="Capture d’écran 2021-04-30 à 18 30 46" src="https://user-images.githubusercontent.com/4331618/116725450-344b8680-a9e2-11eb-8097-3de2324313d4.png">

**Comment by BriceNocenti** [comment]
Thanks, it works that way !!
