### ISSUE TITLE
Use of the onclick event in a shiny app

### ISSUE THREAD

**Issue by cardiomoon** [davidgohel/ggiraph#20]
Is it possible to send a click information to server in a shiny app?

For example, 

ui<-fluidPage(
ggiraphOutput("plot"),
textInput("choice","choice",value="")
)
server=function(session,input,output){
output$plot=renderggiraph({
    p<-ggplot(aes(x=wt,y=mpg),data=mtcars)+geom_point_interactive()
   ggiraph(code=print(p))
})
}
shinyApp(ui,server)

Is it possible to change the input$choice with information made by click in "plot"?

**Comment by davidgohel** [comment]
Yes, either with the `onclick` argument where javascript commands can be executed or with `data_id` argument (elements with associated data_id can be selected): 

```
library(shiny)
library(ggiraph)

shinyApp(ui = fluidPage(
  sidebarLayout(

    sidebarPanel(
      textInput("title", label = "Title", placeholder = "type graph title")
    ),

    mainPanel(
      ggiraph::ggiraphOutput("plot")
    )
  )
), server = function(input, output, session) {

  selected_car <- reactive({
    input$plot_selected
  })

  output$plot <- renderggiraph({
    p <- ggplot(aes(x=wt,y=mpg, data_id = row.names(mtcars) ),data=mtcars) + geom_point_interactive()

    ggiraph(code = print(p), hover_css = "fill:orange;r:4pt;cursor:pointer;",
            selected_css = "fill:red;r:4pt;", selection_type = "multiple")
  })

  observeEvent(selected_car(), {
    updateTextInput(session = session, "title", value = paste0( selected_car(), collapse = " - " ) )
  })
} )
```

**Comment by cardiomoon** [comment]
Dear David,


Thank you so much !!


Sincerely,


Keon-Woong Moon
