### ISSUE TITLE
area from girafe_css doesn't work with geom_tile_interactive

### ISSUE THREAD

**Issue by Ari04T** [davidgohel/ggiraph#200]
As stated. The function `girafe_css` can't be used to specify a specific css style for `geom_tile_interactive`. I initially assumed that the area option of `girafe_css` would be useful for the tiles since they are, well, area elements, but the documentation says that it only works for svg:rect, svg:polygon, svg:path.

**Comment by davidgohel** [comment]
Sorry, a "plus" made of two lines can not be controled with the css associated with polygon (for example).

----

Next time, please provide a minimal reproducible example as required when you open a new issue.

When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 


When you file a bug report, please spend some time making it easy for us to follow and reproduce. The more time you spend on making the bug report coherent, the more time we can dedicate to investigate the bug as opposed to the bug report.
