### ISSUE TITLE
Ability to zoom by dragging zoom-box?

### ISSUE THREAD

**Issue by cboettig** [davidgohel/ggiraph#208]
Amazing package here.  After trying out a good number of the alternative interactive plot engines now available in R, I've found none entirely satisfactory and then have just been completely amazed by `ggiraph`.  Having a native ggplot/R feel, complete with the integration with patchwork is really mind-blowing.  thank you!

Perhaps this is out of scope or the ability of the underlying rendering engine, but the one feature I miss from libraries like plotly is the ability to draw a box area around where I want to zoom (though admittedly I do not like the way plotly zoom works on facetted plots!).  The zoom interface with mouse scroll is quite nice, but somewhat tricky to navigate, particularly if you intend to zoom into a particular range of x axis values say, without shrinking the range of y values.  Would it be possible to have a drag-box driven interface for zooming?  Thanks so much for considering this!

**Comment by sigmapi** [comment]
Hey @cboettig , this feature is now implemented in the latest github version.
There is a `zoom by rectangle` button which will do exactly what you asked.
(Also the zoom on/off buttons are unified into one switch button)
