### ISSUE TITLE
Disappearing Tooltip in rmdshower presentation 

### ISSUE THREAD

**Issue by cardiomoon** [davidgohel/ggiraph#21]
Thank you for great package!!

I'd like to make a rmdshower presentation with ggiraph function(using rmdshower package). But in rmdshower presentation, I can't see tooltips.   

Could you please help me to fix the problem?

This is my test.Rmd file
---
title: "Shower Presentations with R Markdown"
author: test
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: material
---

\# { .fullpage }

<div class="fullpage width">
```{r, echo=FALSE,message=FALSE,warning=FALSE}
require(ggplot2)
require(ggiraph)
data<-mtcars
data$tooltip=rownames(data)
data$data_id=1:nrow(data)
p<-ggplot(data,aes(x=wt,y=mpg,data_id=data_id,tooltip=tooltip))+
    geom_point_interactive()
ggiraph(code={print(p)})
```
</div>

**Comment by davidgohel** [comment]
It should be solved with the latest github version
