### ISSUE TITLE
Disable lasso controls in toolbar

### ISSUE THREAD

**Issue by brooksambrose** [davidgohel/ggiraph#215]
I would be great to be able to hide the lasso selectors from the toolbar even when `opts_selection(type='multiple')`. Something parallel to `opts_toolbar(saveaspng = FALSE)` for the lasso controls. They don't make sense in my use case but I'm having a hard time disabling them. I would like to keep the download png button, however. Maybe an option to turn off the toolbar altogether would also be helpful.

**Comment by sigmapi** [comment]
Can you please explain the reasoning behind this? 
If `opts_selection(type='multiple')` then by removing the lasso controls you will not be able to select/deselect elements. So why you want to hide the controls?

**Comment by sigmapi** [comment]
Ok, in the latest github version there is an argument `hidden` in `opts_toolbar`.  
Setting `opts_toolbar(hidden = 'selection')` will hide the lasso selection buttons
