### ISSUE TITLE
ggiraph.Rd

### ISSUE THREAD

**Issue by masalmon** [davidgohel/ggiraph#22]
`widget width ratio (0 > width >= 1)` should be `widget width ratio (0 < width <= 1)`

**Comment by masalmon** [comment]
Moreover now that there are two folders in the `shiny` folder, the example

```r
if( require(shiny) && interactive() ){
  app_dir <- file.path( system.file(package = "ggiraph"), "shiny" )
  shinyAppDir(appDir = app_dir )
}
```
doesn't work.

**Comment by davidgohel** [comment]
thanks
