### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [davidgohel/ggiraph#235]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are due to our switch to using the `linewidth` aesthetic for stroke width instead of `size`. Please see https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/ for more info on this.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by sigmapi** [comment]
There are several changes involved in this (from v3.3.6 to v3.4.0), we have to review/update each geom implementation.

@thomasp85 I installed the 3.4.0-rc branch and I get errors when running the examples for `geom_path` and `geom_dotplot` (R v4.2.1)

**Comment by thomasp85** [comment]
You may need the dev version of vctrs which are planned for release soon

**Comment by davidgohel** [comment]
fixed with version 0.8.4, now on CRAN
