### ISSUE TITLE
Feature request - Save as svg

### ISSUE THREAD

**Issue by anna-doizy** [davidgohel/ggiraph#236]
Hi,
Thank you, first, for this package!
Would it be possible to choose the format of the exported graph (ie svg OR png) when clicking on the "save" button in the toolbar?
I have no idea if this would be complicated to code. If it's the case, no worries.
Thanks again
Anna

**Comment by davidgohel** [comment]
Dear Anna

Sorry, this is not possible. 

The graphics generated by girafe are SVG graphics and can be saved as PNG with a JS program named 'saveSvgAsPng'. You can still generate PNG/SVG versions from R and add these as links below the girafe output.

**Comment by anna-doizy** [comment]
Thank you for your quick answer, David, and thanks for the workaround ;)
