### ISSUE TITLE
installing ggiraph fails

### ISSUE THREAD

**Issue by jgheerardyn** [davidgohel/ggiraph#24]
When trying 
_devtools::install_github("davidgohel/ggiraph")_
I get as error
_Error in loadNamespace(name) : there is no package called 'httr'_
Thanks for help,
Jos

**Comment by davidgohel** [comment]
Hi
Install it from cran. It will probably install all missing dependancies

David

Le 25 juil. 2016 10:35 AM, "Jos Gheerardyn" <notifications@github.com> a
écrit :

**Comment by jgheerardyn** [comment]
Hi,

thanks for the reply. However, when I install from CRAN, I get 

install.packages("ggiraph")
Installing package into ‘C:/Users/c934501/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependency ‘rvg’
 
 
  There is a binary version available but the source version is later:
    binary source needs_compilation
rvg  0.0.9  0.1.0              TRUE
 
  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rvg_0.0.9.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rvg_0.0.9.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rvg_0.0.9.zip'
Warning in install.packages :
  download of package ‘rvg’ failed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/ggiraph_0.3.0.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/ggiraph_0.3.0.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/ggiraph_0.3.0.zip'
Warning in install.packages :
  download of package ‘ggiraph’ failed

**Comment by davidgohel** [comment]
From what I read you cant install packages because of your network

Le 25 juil. 2016 3:01 PM, "Jos Gheerardyn" <notifications@github.com> a
écrit :
