### ISSUE TITLE
Graph not output in a flexdashboard using Shiny

### ISSUE THREAD

**Issue by awcm0n** [davidgohel/ggiraph#240]
This outputs a graph in my flexdashboard:
```
fig <- reactive({ my_plotting_func_returning_ggplot_object() })
output$fig <- renderPlot({ fig() })
plotOutput("fig")
```
This also outputs a graph:
```
fig <- reactive({ my_plotting_func_returning_ggplot_object() })
output$fig <- renderPlotly({ ggplotly(fig()) })
plotlyOutput("fig")
```
This does **not** output a graph (but no error message):
```
fig <- reactive({ my_plotting_func_returning_ggplot_object() })
output$fig <- renderGirafe({ girafe(fig()) })
girafeOutput("fig")
```
flexdashboard 0.5.2
ggiraph 0.8.3
ggplot2 3.4.0
shiny 1.7.3

**Comment by awcm0n** [comment]
Here is a minimal example of a flexdashboard using Shiny that renders a plotly object but fails to render a ggiraph object.

[test.txt](https://github.com/davidgohel/ggiraph/files/9976985/test.txt)

**Comment by davidgohel** [comment]
I don't understand exactly why, but it seems with ggiraph the call to `girafeOutput("fig")` should happen before the call to `output$fig <- renderGirafe()`.

**Comment by awcm0n** [comment]
But Shiny discovers the reactive graph and determines execution order, doesn't it? Is there a way to fix the minimal example I posted?

**Comment by davidgohel** [comment]
I am not sure, maybe :)

This does work for me, doesn't it work for you?

```
girafeOutput("fig")
fig <- reactive({ my_plotting_func_returning_ggplot_object() })
output$fig <- renderGirafe({ girafe(fig()) })
```

**Comment by awcm0n** [comment]
Unfortunately, it doesn't. The order of the statements doesn't change the result on my end.

**Comment by awcm0n** [comment]
Thanks, David, with your feedback, I was able to fix my example. I found that one cannot omit the argument name `ggobj` in `girafe()` [ggplotly()` behaves different in that regard]:

This does not work:
`output$fig <- renderGirafe({ girafe(ggplotobject) })`

This works:
`output$fig <- renderGirafe({ girafe(ggobj = ggplotobject })`

**Comment by davidgohel** [comment]
Next time, provide  a reprex as required, we would have saved some time
