### ISSUE TITLE
Specifying fonts on ubuntu machine (github action)

### ISSUE THREAD

**Issue by othomantegazza** [davidgohel/ggiraph#242]
Hi, is it possible that there is an issue with fonts when a ggiraph is deployed through github actions?

I'm using ggplot's theme_set to set the font locally, but it does not work when I deploy it through github action, even if the font sans exists (checking with `validated_fonts()`) and is associated with "DejaVu Sans".

```
theme_set(
  theme_minimal(base_family = 'sans') +
    theme(
      axis.text.x = element_text(
        angle = 90,
        vjust = 0,
        hjust = 1,
        size = label_size
      ),
      axis.text.y = element_text(
        vjust = 0,
        hjust = 1,
        size = label_size
      ),
      axis.title.y = element_text(
        hjust = 1,
        vjust = 2,
        size = label_size
      )
    ) 
)
```

You might have the same issue in the help page at https://davidgohel.github.io/ggiraph/articles/offcran/fonts.html, because the fonts in the demostrative plots look like serif, even when specified otherwise.

Thank you so much in advance!

**Comment by davidgohel** [comment]
Yes

We are thinking on making that easier, but this is totally possible.

I believe the page you show is OK, I can see all configured font being used:

<img width="990" alt="Capture d’écran 2022-11-23 à 11 19 34" src="https://user-images.githubusercontent.com/4331618/203522656-a1c5c91a-42b8-4abb-a0b4-bdee7b9dc8c9.png">

-----
What I did is: 

1. Install a specific package I created recently to manage this issue (https://github.com/davidgohel/ggiraph/blob/master/.github/workflows/pkgdown.yaml#L35)
2. use the package [here](https://github.com/davidgohel/ggiraph/blob/master/vignettes/offcran/fonts.Rmd#L60) to register font with systemfonts
3. use the package [here](https://github.com/davidgohel/ggiraph/blob/master/vignettes/offcran/fonts.Rmd#L69) to add the font as an htmlDependancy

Note that 'usefonts' might change or even be removed, as I'd like to take advantage of package 'gfonts' instead (and avoid an unnecessary new font package...).

**Comment by davidgohel** [comment]
Hello, 

I can close this issue now. I believe all is ok now.

The font management has been very much improved since this thread started. It's documented here: https://davidgohel.github.io/ggiraph/fonts.html

Basically, fonts are now managed by 'gdtools', which will have a second life instead of slowly dying. It helps manage 'Google Fonts' in plots and web pages:

To make sure that we can use font "Open Sans":
```
gdtools::register_gfont("Open Sans")
```

To make sure that font "Open Sans" is embedded in the web page:

```
gdtools::addGFontHtmlDependency(family = "Open Sans")
```
