### ISSUE TITLE
Error when publishing app with ggiraph

### ISSUE THREAD

**Issue by Spswitzer** [davidgohel/ggiraph#243]
I started to see an error last week when I attempt to publish an app with geom_col_interactive(), geom_bar_interactive(), or element_text_interactive(). 
When I run in the R Studio IDE all looks fine, but the I publish to shinyapps.io, I see the following error: An error has occurred. Check your logs or contact the app author for clarification

The log provides the following:
ℹ Error occurred in the 1st layer.
Caused by error in `check.length()`:
 ! 'gpar' element 'lwd' must not be length 0

`# Load required packages ----
library(shiny)
library(ggiraph)
library(tidyverse)

# Data ----
irisSummary <- iris %>% 
  group_by(Species) %>% 
  summarise(Sepal.Width = first(Sepal.Width))

# UI ----
ui <- function(request) {
  fluidPage(
    fluidRow(
      ggiraph::ggiraphOutput('Plot', height = '250px')
    )
    )
}
# SERVER -----
server = function(input, output, session) { 
  
  output$Plot <- ggiraph::renderggiraph({
    
    p <- ggplot(data = irisSummary,
                mapping = aes(
                  x = Species,
                              y = Sepal.Width,
                              fill = Species))+
      geom_bar_interactive(stat= 'identity') +
       theme_minimal() 
    
    ggiraph::ggiraph(code = print(p)
    )
  })
}
shinyApp(ui = ui, server = server)
`
If I remove the _interactive, all publishes error-free. 

Also, if I use geom_point_interactive or geom_text_interactive() , I can publish as expected to shinyapps.io

I am using R version 4.2.2 and ggirpah version 0.8.3 (0.8.4) is not downloading from CRAN. 

I am not sure how to parse this out any further. Thanks for any help you can offer.

**Comment by davidgohel** [comment]
Hello,

Sorry, it can't work because of #235. ggplot2 changed (v 3.4.0), we had to adapt the code, then ggiraph 0.8.4 must be available.
