### ISSUE TITLE
Plot not resized vertically in Flexdashboard using Shiny (ggiraph v0.8.5)

### ISSUE THREAD

**Issue by awcm0n** [davidgohel/ggiraph#249]
My intention is to fill a Flexdashboard container with a plot. While a ggplot object is resized correctly vertically and horizontally (Chart A), the ggiraph object is only resized horizontally and does not fit the container vertically (Chart B). Can this be fixed, so that the ggiraph object is rendered like the ggplot object?

The code:

````
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggiraph)
library(ggplot2)
```

Row {data-height=500}
-----------------------------------------------------------------------

### Chart A

```{r}
dataset <- mtcars
dataset$carname = row.names(mtcars)

gg_point1 = ggplot( data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp)) +
  geom_point() + theme_minimal()
output$fig1 <- renderPlot({ gg_point1 })
plotOutput("fig1")
```

Row {data-height=500}
-----------------------------------------------------------------------

### Chart B

```{r}
gg_point2 = ggplot( data = dataset,
    mapping = aes(x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname) ) +
  geom_point_interactive() + theme_minimal()
output$fig2 <- renderGirafe({ girafe(ggobj = gg_point2,  options = list(opts_sizing(rescale = TRUE)) ) })
girafeOutput("fig2", height = "100%", width = "100%")
```
````

<img width="1044" alt="Screenshot 2023-01-08 at 3 14 40 PM" src="https://user-images.githubusercontent.com/29875025/211224234-50e26814-641a-411e-981c-11b1568b50a5.png">

**Comment by davidgohel** [comment]
Hello

I am sorry, we don't have a solution for your issue, `girafe()` produces a graphic with an aspect ratio. It can't fit and adapt perfectly in a flexdashboard. 

We tried to make that clearer here: 
https://davidgohel.github.io/ggiraph/size.html

Let us know if something is unclear.
