### ISSUE TITLE
Error: length(ids) == length(str) is not TRUE

### ISSUE THREAD

**Issue by daria6** [davidgohel/ggiraph#25]
Hi, I often get the error  "**Error: length(ids) == length(str) is not TRUE**"
when running the ggiraph() function on interactive plots having more than 1 element of interactivity.
However, I don't get it all the times I have multiple interactive elements.
I don't understand what I need to do to solve this problem. Any help would be much appreciated.
Thank you !

**Comment by davidgohel** [comment]
Hi,

It means size of your IDs (tooltips, data_id?)  do not equal to size of the graphical elements you've drawn (if everything in a data.frame, it should not happen).

**Comment by daria6** [comment]
Thank you for your reply.
Is it possible to use different dataframes to plot different layers on the final ggplot, and still use the interactivity?

For example: 
_ggplot(df1,aes(x=x,y=y))+
 geom_point_interactive(aes(tooltip=tooltip,data_id=data_id))+
geom_segment_interactive(data=df2,aes(x=x2start,xend=x2end,y=y2,yend=y2,tooltip = tooltip2,data_id=data_id2),colour="white",size=0.3)_

**Comment by davidgohel** [comment]
Yes
It is just a ggplot extension

David
Le 28 juil. 2016 1:43 PM, "daria6" <notifications@github.com> a écrit :

>

> Thank you for your reply.
> Is it possible to use different dataframes to plot different layers on
the final ggplot, and still use the interactivity?
>
> For example:
> ggplot(df1,aes(x=x,y=y))+
> geom_point_interactive(aes(tooltip=tooltip,data_id=data_id))+
>
geom_segment_interactive(data=df2,aes(x=x2start,xend=x2end,y=y2,yend=y2,tooltip
= tooltip2,data_id=data_id2),colour="white",size=0.3)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
<https://github.com/davidgohel/ggiraph/issues/25#issuecomment-235871815>, or
mute the thread
