### ISSUE TITLE
persistent download  button/icon

### ISSUE THREAD

**Issue by Yousuf28** [davidgohel/ggiraph#250]
Thanks for the ggiraph package. I am using it in my shiny app. I like how I can create  clean interactive plot.

![download](https://user-images.githubusercontent.com/31291716/212082806-f368f030-4145-4e57-b42b-22463e5bd598.jpg)

I have two question/request:
1. It seems download button/icon only appear when mouse hover on the plot. Is  it possible that download button  always visible so I can see the button without mouse hovering on the plot?
2. I am using the ggiraph in my shiny app. I see the plot is svg and I can only download as png.  Is it possible to add option to download the  plot as  svg file?

**Comment by davidgohel** [comment]
1. no. For now, there is no option like this. 
2. same than in 1 :) Sorry. 

We already have internal mechanisms for enabling any button action by the user, this would make possible your 2. And I agree, a fixed toolbar would be great.

We will try to implement these

**Comment by Yousuf28** [comment]
Thanks for reply. A fixed toolbar would be really great.

**Comment by davidgohel** [comment]
implemented via `opts_toolbar(fixed = TRUE)`.
