### ISSUE TITLE
Webpage does not provide help I need

### ISSUE THREAD

**Issue by jromanowska** [davidgohel/ggiraph#255]
I visited the webpage today (https://davidgohel.github.io/ggiraph/), but all I can see is the book about ggiraph, no links to functions and documentation.
I think it's kind of a bug. ;)

**Comment by davidgohel** [comment]
This is user documentation. Manual are still available in R, you can use`?girage()`, F1 with RStudio, etc.

I will remove the book from github soon, no problem

**Comment by jromanowska** [comment]
I understand that I can check manual in R, but it was soooo much nicer to check it online :)
The book is great! I just think it should be an addition to the documentation. But of course, this is your package, so it's up to you!
Thanks for the great work!

**Comment by davidgohel** [comment]
Sorry, I meant to say: this book is temporarily there (kind of bug as you said :)), the manuals will be back soon and the book will be in another location or in a subdirectory.

**Comment by davidgohel** [comment]
fixed now :)
