### ISSUE TITLE
Unclear whether to use girafe or ggiraph for shiny outputs

### ISSUE THREAD

**Issue by daattali** [davidgohel/ggiraph#256]
There is a pair of functions called `ggiraphOutput()`/`renderggiraph()`, and another pair called `girafeOutput()`/`renderGirafe()`. It is not clear which one should be used in shiny apps, and whether or not there's a difference.

**Comment by davidgohel** [comment]
OK
ggiraphOutput() and renderggiraph() have been deprecated
