### ISSUE TITLE
selection with duplicated id

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/ggiraph#26]
if one id is selected, all elements with this id should be highlighted (tbd in the JS code)

**Comment by dave-clare** [comment]
I've been doing badly hacky work arounds for this issue involving having a "selected" variable in my data and then using two different graphics that switch depending on if any point was selected or not. I think its messing up other things (like tooltips that won't go away). Would love a fix to this.

**Comment by davidgohel** [comment]
Hi,

It should be solved now. Could you try?

```
devtools::install_github("davidgohel/gdtools")
devtools::install_github("davidgohel/rvg")
devtools::install_github("davidgohel/ggiraph")
```

(Zoom has been disabled temporary as I am trying to move from D3.js v3 to v4 and met an issue with zoom... It should be back end of this week.)

David

**Comment by dave-clare** [comment]
David,

Sorry, but it doesn’t seem to be fixed.

I’m happy to try out any other possible fixes.

Thank you,
David Clare

**Comment by davidgohel** [comment]
Could you send a reproducible example?

David

**Comment by dave-clare** [comment]
David,

Attached is a ui and server file adapted from your crimes shiny example.
In the data set, I made many of the states repeat. When I click on one dot, the others of the same state are not also highlighted (though they do populate the list to the left).

Let me know if it works for you?

Thank you,
David Clare

**Comment by davidgohel** [comment]
sorry... I simply forgot to push on github the modifications...

It should be better now. 

David

PS: I can't see any code in your previous answer.

**Comment by dave-clare** [comment]
David,

It works perfectly! Beautiful!!

I suppose CRAN will take a while to clear the next update? I’m crossing my fingers I can publish with this version. I’ve never published with not-CRAN-cleared packages before.

The previous reply had attached files. All they were doing was adding a line making repeating states in the data for:
shiny::runApp(appDir = system.file("shiny/crimes", package = "ggiraph"), display.mode = "showcase")
Do attached files not follow through the github notification system? Good thing to remember.

Thank you so much for the fix! The package is really great. Please let me know if there is some way I can aid development.

Thank you,
David Clare

**Comment by davidgohel** [comment]
I will submit to cran soon, it should not take time (they are very efficient, if it is slow, it will because of me ;))
