### ISSUE TITLE
Alpha changes depending where it is defined

### ISSUE THREAD

**Issue by siirtola** [davidgohel/ggiraph#263]
Thanks for the super-useful package! 

I have run into following problem, demonstrated by the following code snippets.

I am using one of the given examples. In the first version, everything is as expected.  The `alpha`
is set outside the `aes`, and the displayed value is clearly the same as in the legend.

```
library(ggplot2)
library(ggiraph)
data <- mtcars
data$cyl <- factor(data$cyl)
data$carname <- row.names(data)

gg_point = ggplot(data = data) +
  geom_point_interactive(
    aes(x = wt, y = qsec, color = cyl,
        tooltip = carname, data_id = carname), alpha = 1.0) + 
  theme_minimal() +
  scale_color_discrete()

girafe(ggobj = gg_point)
```

This is the second version, the only difference being that the `alpha` is **defined
within** `aes` -- and the displayed alpha value is clearly not 1.

```
gg_point = ggplot(data = data) +
  geom_point_interactive(
    aes(x = wt, y = qsec, color = cyl, alpha = 1.0,
        tooltip = carname, data_id = carname)) + 
  theme_minimal() +
  scale_color_discrete()

girafe(ggobj = gg_point)
```

Have I overlooked something, or is this a bug?

**Comment by davidgohel** [comment]
hello,

Aesthetics in `aes()` are not expected to be scalars, they are expected to be mapped with a variable name.
I think it is what's expected. 


If I print the ggplot without `girafe()`, I get

<img width="746" alt="Capture d’écran 2023-05-02 à 21 40 06" src="https://user-images.githubusercontent.com/4331618/235768540-4d5d7175-8703-4005-84e0-3a654e11cde3.png">


 If I print the ggplot with `girafe()`, I get

<img width="738" alt="Capture d’écran 2023-05-02 à 21 40 36" src="https://user-images.githubusercontent.com/4331618/235768629-00b039a4-4ff0-4b56-a194-8414cf4bc490.png">

**Comment by siirtola** [comment]
Hello David,

Thanks for the reply!  The problem is probably not ggirafe-related. Mapping the alpha with a variable having a value 1.0 (as alpha is expected to be 0..1) does not the change the behavior – this is starting to look like a ggplot problem since the alpha of the points is clearly not 1.0 as in the legend.

**Comment by davidgohel** [comment]
Sorry if I was not clear

The problem is your code, not ggplot, not girafe

**Comment by siirtola** [comment]
I changed the code to use a variable for alpha, sorry I should have mentioned this. I will ask from ggplot forums – probably I have misunderstood something.
