### ISSUE TITLE
Can't load ggiraph with dev ggplot2

### ISSUE THREAD

**Issue by olivroy** [davidgohel/ggiraph#267]
Hi,
I can't load ggiraph,

I am getting the following error message.

```r 
library(ggiraph)
Error: package or namespace load failed for ‘ggiraph’:
 object 'guide_gengrob' not found whilst loading namespace 'ggiraph'
```

I am using the development version of ggplot2 on Windows if it helps with R 4.2.3. 

I tried with the CRAN ggplot2, and it worked.

It seemed to be related to ggplot2, removing the guide_gengrob function from its internals.

When submitting a new issue:

- [x] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by schloerke** [comment]
Related PR in `{ggplot2}`: https://github.com/tidyverse/ggplot2/pull/4879

Related fix in `{plotly}`: https://github.com/plotly/plotly.R/commit/5b73531f0f41e123c6b5519069c02f7cfe03b2d0

**Comment by sigmapi** [comment]
Related PR in ggiraph: #269

**Comment by davidgohel** [comment]
fixed with https://github.com/davidgohel/ggiraph/commit/3672a99f6e46552a4fe4d97d922eaf22a38885a7 that use #269 and deployed to CRAN
