### ISSUE TITLE
Feature request-Add a button to draw geometries

### ISSUE THREAD

**Issue by liuyadong** [davidgohel/ggiraph#272]
Hi, I am currently using geom_sf_interactive with Shiny to enable interactive attribute editing and color filling, and it works well. However, it only supports existing geometries, and I think it would be great to have the ability to draw new geometries as well. Perhaps a new button in the toolbar, similar to lasso selection, could be added to facilitate this feature?

**Comment by davidgohel** [comment]
Hello, I am sorry but it's unlikely we can add a drawer tool in ggiraph. "ggiraph makes ggplot2 interactive", it's based on ggplot2 production. This would drive us beyond the scope of the package
