### ISSUE TITLE
Output preprocessor for R Shiny testing

### ISSUE THREAD

**Issue by isfraser** [davidgohel/ggiraph#276]
When trying to do snapshot testing of shiny applications using the shinytest or shinytest2 packages, ggiraph elements will always fail testing (that is, comparison to known good outputs) because each rendering creates different unique id values for graph elements. 

The [Shinytest FAQ](https://rstudio.github.io/shinytest2/articles/zzz-faq.html)  says that the correct solution to this is adding an output preprocessor so that the unique elements are not stored in a snapshot output. Can this be added to renderGirafe?

**Comment by davidgohel** [comment]
You can use any controlled/defined ID - see https://www.ardata.fr/ggiraph-book/extra-ipar.html#controling-svg-identifier

**Comment by davidgohel** [comment]
The svg `id` can be controlled with argument `canvas_id` (pass to `dsvg()`)

```library(gdtools)
library(ggiraph)

register_gfont("Open Sans")

dat <- mtcars
dat$carname <- row.names(dat)

gg <- ggplot(dat, aes(drat, carname)) +
  geom_point() +
  theme_minimal(base_family = "Open Sans")

girafe(
  ggobj = gg,
  canvas_id = "zzz",
  dependencies = list(gfontHtmlDependency(family = "Open Sans"))
)


```

<img width="1215" alt="Capture d’écran 2024-02-24 à 00 53 20" src="https://github.com/davidgohel/ggiraph/assets/4331618/ea43b514-7ff8-4108-8460-b54d0cdb2010">
