### ISSUE TITLE
Respect RNG seed for SVG IDs

### ISSUE THREAD

**Issue by salim-b** [davidgohel/ggiraph#277]
SVG `id` attributes of ggiraph htmlwidgets vary independently of the input. This creates annoying noise when the HTML output is version-controlled using Git.

I tried setting R's RNG seed before creating the htmlwigets without success:

```r
set.seed(42L)
```

I know I can stabilize the htmlwidget *container* IDs using

```r
htmlwidgets::setWidgetIdSeed(seed = 42)
```

But how can I also make the SVG `id` attributes ggiraph generates stable?

**Comment by davidgohel** [comment]
The svg `id` can be controlled with argument `canvas_id` (pass to `dsvg()`)

```library(gdtools)
library(ggiraph)

register_gfont("Open Sans")

dat <- mtcars
dat$carname <- row.names(dat)

gg <- ggplot(dat, aes(drat, carname)) +
  geom_point() +
  theme_minimal(base_family = "Open Sans")

girafe(
  ggobj = gg,
  canvas_id = "zzz",
  dependencies = list(gfontHtmlDependency(family = "Open Sans"))
)


```

<img width="1215" alt="Capture d’écran 2024-02-24 à 00 53 20" src="https://github.com/davidgohel/ggiraph/assets/4331618/ea43b514-7ff8-4108-8460-b54d0cdb2010">

**Comment by davidgohel** [comment]
Let me know if it needs to be reopened

**Comment by salim-b** [comment]
Thanks a lot for the hint! I wasn't aware of the `canvas_id` parameter, works perfectly.
