### ISSUE TITLE
geom_col_interactive() ignoring specified order of stacked bars

### ISSUE THREAD

**Issue by LREMitchell** [davidgohel/ggiraph#285]
## The issue
I've been creating a series of stacked bar charts using ggplot2 and ggiraph. I had tried to re-order the levels of the stacked bars, but have experienced some unexpected behaviour where it ignores the specified order once I add a tooltip in `geom_col_interactive`

## Some code to demonstrate the issue
I've used the mpg data set from the ggplot2 package to create a reproducible example. This is by no means meant to be a good data visualisation - it is just meant to demonstrate the issue, where the visualisations goes from presenting the stacked bars in the correct order to an undesired order:

```
# Packages ----

library(ggplot2)
library(dplyr)
library(glue)
library(ggiraph)


# Example visualisation data ----

mpg_data <- 
  mpg |> 
  mutate(manufacturer_group = case_when(
    manufacturer == "dodge" ~ "dodge",
    manufacturer == "toyota" ~ "toyota",
    manufacturer == "volkswagen" ~ "volkswagen",
    .default = "other"
  )) |> 
  group_by(year, manufacturer_group) |> 
  summarise(average_cyl = mean(cyl)) |> 
  mutate(year = as.character(year))


# Create the plot ----

# Desired order for bars in plot
bar_order <- c("dodge",
               "toyota",
               "volkswagen",
               "other")

# Define a tooltip using glue syntax
plot_tooltip <- "Manufacturer Group: {manufacturer_group}
                 Year: {year}
                 Average Cyl: {average_cyl}"

# First version of plot without tooltip - it inherits the bar order.
mpg_data |> 
  mutate(manufacturer_group = factor(manufacturer_group, levels = bar_order)) |> 
  ggplot(aes(x = year, y = average_cyl, fill = manufacturer_group)) +
  geom_col() +
  scale_fill_manual(values = c("blue", "purple", "green", "orange"))

# Second version of plot with tooltip - it ignores the bar order.
mpg_data |> 
  mutate(manufacturer_group = factor(manufacturer_group, levels = bar_order)) |> 
  ggplot(aes(x = year, y = average_cyl, fill = manufacturer_group)) +
  geom_col_interactive(aes(tooltip = glue(plot_tooltip))) +
  scale_fill_manual(values = c("blue", "purple", "green", "orange"))

```

This has been run on a machine where I don't have admin access to update to the most recent version, unfortunately. 
I've printed the session info below.

Hopefully you can have a look at this, and thanks for the great work on the package - it's brilliant!

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggiraph_0.8.7 glue_1.6.2    dplyr_1.1.0   ggplot2_3.4.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10       rstudioapi_0.15.0 magrittr_2.0.3    uuid_1.1-0       
 [5] tidyselect_1.2.0  munsell_0.5.0     colorspace_2.1-0  R6_2.5.1         
 [9] rlang_1.0.6       fastmap_1.1.0     fansi_1.0.4       tools_4.2.2      
[13] grid_4.2.2        gtable_0.3.1      utf8_1.2.3        cli_3.6.0        
[17] withr_2.5.0       systemfonts_1.0.4 htmltools_0.5.4   digest_0.6.31    
[21] tibble_3.1.8      lifecycle_1.0.3   farver_2.1.1      purrr_1.0.1      
[25] htmlwidgets_1.6.1 vctrs_0.5.2       labeling_0.4.2    compiler_4.2.2   
[29] pillar_1.8.1      generics_0.1.3    scales_1.2.1      pkgconfig_2.0.3

**Comment by davidgohel** [comment]
Is it not related to #265?

**Comment by LREMitchell** [comment]
You're completely right - I hadn't spotted that one! Sorry for raising this again. I'll close this noting it's a duplicate of #265. 

Thanks again for all your work on this package.

**Comment by LREMitchell** [comment]
This was a duplicate
