### ISSUE TITLE
y-axis alignment issue when changing fonts

### ISSUE THREAD

**Issue by mjdzr** [davidgohel/ggiraph#286]
Somewhat similar to #156, the y-axis labels don't align, and this only happens if I use another font. I'm having this problem when I deploy to shinyapps.io. My dashboard works well locally, but the font change that happens as a result of deploying on shinyapps.io results in y-axis alignment problem. At first I thought the problem is using `hjust = 1` in my dashboard, but the example below is on my own computer, without using dashboard, only with font changes. I'm using the same example as [ggiraph book - Chapter 3](https://www.ardata.fr/ggiraph-book/fonts.html):

```
font_family_exists("Open Sans")
```
[1] TRUE
```
library(gdtools)
register_gfont("Open Sans")
```
[1] TRUE
```
addGFontHtmlDependency(family = "Open Sans")
```
<style></style>

```
dat <- mtcars
dat$carname <- row.names(dat)

gg <- ggplot(dat, aes(drat, carname)) + 
  geom_point() + 
  theme_minimal(base_family = "sans")

validated_fonts(list(sans = "Open Sans"))
```
$sans
[1] "Open Sans"

$serif
[1] "Times New Roman"

$mono
[1] "Courier New"

$symbol
[1] "Symbol"

Running `ggiraph` on the object itself works perfectly:
```
girafe(ggobj = gg)
```
![image](https://github.com/davidgohel/ggiraph/assets/58193630/6882a15d-d97e-4769-9ad8-6971f98065a5)

But adding the font changes the alignment:
```
girafe(ggobj = gg, fonts = list(sans = "Open Sans"))
```
![image](https://github.com/davidgohel/ggiraph/assets/58193630/4029a182-4ace-476d-ab75-c7e24f72ea03)

In many issues, you have mentioned an explanation available in https://davidgohel.github.io/ggiraph/articles/offcran/fonts.html and https://davidgohel.github.io/ggiraph/articles/offcran/customizing.html#fonts, but the links do not exist. Maybe that explanation has already answered this question. In that case, my apologies for duplicate question.

I'm using R 4.3.2, and ggiraph 0.8.7.

Thanks for the fantastic package!

**Comment by davidgohel** [comment]
There are two possible solutions that look easy:

## solution 1

```
library(gdtools)
library(ggiraph)

register_gfont("Open Sans")

dat <- mtcars
dat$carname <- row.names(dat)

gg <- ggplot(dat, aes(drat, carname)) + 
  geom_point() + 
  theme_minimal(base_family = "sans")

girafe(ggobj = gg, fonts = list(sans = "Open Sans"), 
       dependencies = list(gfontHtmlDependency(family = "Open Sans")))
```

## solution 2

```
library(gdtools)
library(ggiraph)

register_gfont("Open Sans")

dat <- mtcars
dat$carname <- row.names(dat)

gg <- ggplot(dat, aes(drat, carname)) + 
  geom_point() + 
  theme_minimal(base_family = "Open Sans")

girafe(ggobj = gg, 
       dependencies = list(gfontHtmlDependency(family = "Open Sans")))
```

**Comment by davidgohel** [comment]
Let me know if it needs to be re-opened. 

Note there will be some work about the font management soon
