### ISSUE TITLE
geom_bar_interactive order data with tooltip

### ISSUE THREAD

**Issue by RozennGZ** [davidgohel/ggiraph#29]
Normally, when ordering data before construct the plot, the factors are displayed in order.
I have an issue using tooltip with geom_bar_interactive. When using a tooltip, the order isn't respected... and I have no way to manage this.

Have you already notice this fact ? Do you have a way to manage it ? 

Please find bellow an example of this issue with a pie chart (I also had this issue with a simple geom_bar_interactive plot).

Thanks in advance,

```
dat_graph=structure(list(gpe = structure(c(8L, 7L, 6L, 5L, 4L, 3L, 2L, 
1L), .Label = c("100", "200", "300", "400", "500", "600", "700", 
"800"), class = c("ordered", "factor")), value = c(16.8720568855297, 
3.00047333010115, 6.62301163513759, 12.3880815455173, 13.1907426160542, 
23.4665351719248, 12.3419168171762, 12.117181998559), gpe_name = c("G8", 
"G7", "G6", "G5", "G4", "G3", "G2", "G1"), label_text = structure(c(4L, 
1L, 7L, 6L, 5L, 8L, 2L, 3L), .Label = c("G7", "G2", "G1", "G8", "G4", "G5", "G6", "G3"), 
class = c("ordered", "factor")), gpe_order = structure(c(8L, 
7L, 6L, 5L, 4L, 3L, 2L, 1L), .Label = c("100", "200", "300", 
"400", "500", "600", "700", "800"), class = c("ordered", "factor"
))), .Names = c("gpe", "value", "gpe_name", "label_text", "gpe_order"
), row.names = c(NA, -8L), class = "data.frame")
dat_graph$gpe_order <- factor(dat_graph$gpe, levels =sort(levels(dat_graph$gpe), TRUE))
```

### Without Tooltip

```
ggplot(dat_graph,aes(x=factor(1),value,fill=gpe_order)) + 
  geom_bar_interactive(stat="identity")+#,aes(tooltip = label_text)) +
  theme_conso()+
  theme(panel.grid=element_blank(),axis.ticks=element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(), axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.border=element_rect(fill=NA,colour="#F2F2F2", size=0),
        panel.background=element_rect(fill="#F2F2F2",colour="#F2F2F2", size=0),
        plot.background=element_rect(fill="#F2F2F2",color="black",size=2,linetype=1))+
  scale_size(guide=FALSE)+
  labs(fill="Groups")+
  coord_polar(theta="y")+
  scale_fill_manual(values = c("100" = "#6CCE24","200" = "#E8CD07","300" = "#8624CE", "400"="#4c4c4c","500"="#2442CE","600"="#CE3124","700"="#24C1CE","800"="#E8860F"))
```

![rplot08](https://cloud.githubusercontent.com/assets/20970251/18439135/6effb0d0-7904-11e6-81f9-d6745b2814bf.png)

### With Tooltip

```
dat_graph$gpe_order <- factor(dat_graph$gpe, levels =sort(levels(dat_graph$gpe), TRUE))

g=ggplot(dat_graph,aes(x=factor(1),value,fill=gpe_order)) + 
  geom_bar_interactive(stat="identity",aes(tooltip = label_text)) +
  theme_conso()+
  theme(panel.grid=element_blank(),axis.ticks=element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(), axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.border=element_rect(fill=NA,colour="#F2F2F2", size=0),
        panel.background=element_rect(fill="#F2F2F2",colour="#F2F2F2", size=0),
        plot.background=element_rect(fill="#F2F2F2",color="black",size=2,linetype=1))+
  scale_size(guide=FALSE)+
  labs(fill="Groups")+
  coord_polar(theta="y")+
  scale_fill_manual(values = c("100" = "#6CCE24","200" = "#E8CD07","300" = "#8624CE",
                               "400"="#4c4c4c","500"="#2442CE","600"="#CE3124","700"="#24C1CE","800"="#E8860F"))
 
    ggiraph(code = print(g),zoom_max=4,width =1)
```

![rplot07](https://cloud.githubusercontent.com/assets/20970251/18439139/753fa19e-7904-11e6-90c1-a09c3abf9df2.png)

**Comment by davidgohel** [comment]
OK, for now, I can't reproduce the issue, I have the same results.


Why are you treating the factor in the first graph as: 

    dat_graph$gpe_order <- factor(dat_graph$gpe, levels =sort(levels(dat_graph$gpe), TRUE))

and for the second one with 

    dat_graph$gpe_order <- factor(dat_graph$gpe, levels =sort(levels(dat_graph$gpe), FALSE))


I hope it's not an issue with Windows, could you add you `sessionInfo()` please?

**Comment by RozennGZ** [comment]
The second "dat_graph$gpe_order <- factor(dat_graph$gpe, levels =sort(levels(dat_graph$gpe), FALSE))" was an error in my last comment. I have tried it again, I have still data not in order when I add a tooltip.

To do it, I have followed the exemple : http://stackoverflow.com/questions/15251816/how-do-you-order-the-fill-colours-within-ggplot2-geom-bar to obtain the fill color in order : 
[1] "100" "200" "300" "400" "500" "600" "700" "800"

Please find below my session info : 
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tibble_1.2         emojifont_0.3.4    chron_2.3-47       ggiraph_0.3.1      ggplot2_2.1.0.9000 shinyjs_0.6        shinyBS_0.61       tidyr_0.6.0        dplyr_0.5.0       
[10] httr_1.2.1         XML_3.98-1.4       RCurl_1.95-4.8     bitops_1.0-6       shiny_0.13.2       reshape_0.8.5     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6       plyr_1.8.4        sysfonts_0.5      R.methodsS3_1.7.1 R.utils_2.3.0     tools_3.2.2       digest_0.6.10     gtable_0.2.0      DBI_0.5           proto_0.3-10     
[11] showtextdb_1.0    xml2_1.0.0        gdtools_0.0.7     htmlwidgets_0.7   grid_3.2.2        R6_2.1.2          rvg_0.1.0         magrittr_1.5      scales_0.4.0      htmltools_0.3.5  
[21] showtext_0.4-4    assertthat_0.1    mime_0.5          xtable_1.8-2      colorspace_1.2-6  httpuv_1.3.3      labeling_0.3      miniUI_0.1.1      munsell_0.4.3     R.oo_1.20.0

**Comment by davidgohel** [comment]
I just tested it on a windows station. Code adapted from yours is below (I don't know about `theme_conso`, and I modified the code to get the same base ggplot object that should receive a `geom_bar` layer or a `geom_bar_interactive` layer.


```
# install.packages("ggiraph")
# install.packages("R.oo")
library(ggiraph)

dat_graph=structure(list(gpe = structure(c(8L, 7L, 6L, 5L, 4L, 3L, 2L, 
1L), .Label = c("100", "200", "300", "400", "500", "600", "700", 
"800"), class = c("ordered", "factor")), value = c(16.8720568855297, 
3.00047333010115, 6.62301163513759, 12.3880815455173, 13.1907426160542, 
23.4665351719248, 12.3419168171762, 12.117181998559), gpe_name = c("G8", 
"G7", "G6", "G5", "G4", "G3", "G2", "G1"), label_text = structure(c(4L, 
1L, 7L, 6L, 5L, 8L, 2L, 3L), .Label = c("G7", "G2", "G1", "G8", "G4", "G5", "G6", "G3"), 
class = c("ordered", "factor")), gpe_order = structure(c(8L, 
7L, 6L, 5L, 4L, 3L, 2L, 1L), .Label = c("100", "200", "300", 
"400", "500", "600", "700", "800"), class = c("ordered", "factor"
))), .Names = c("gpe", "value", "gpe_name", "label_text", "gpe_order"
), row.names = c(NA, -8L), class = "data.frame")
dat_graph$gpe_order <- factor(dat_graph$gpe, levels =sort(levels(dat_graph$gpe), TRUE))



gg <- ggplot(dat_graph,aes(x=factor(1),value,fill=gpe_order)) + 
  coord_polar(theta="y")+
  scale_fill_manual(values = c("100" = "#6CCE24","200" = "#E8CD07","300" = "#8624CE", "400"="#4c4c4c","500"="#2442CE","600"="#CE3124","700"="#24C1CE","800"="#E8860F"))
  

gg_1 <- gg + geom_bar(stat="identity")
gg_2 <- gg + geom_bar_interactive(stat="identity",aes(tooltip = label_text))
print( gg_1 )
print( ggiraph(code = print( gg_2 ), zoom_max = 4, width = 1) )
```

I got the exact same rendering. 

![geom_bar](https://cloud.githubusercontent.com/assets/4331618/18466533/5bc05c48-799c-11e6-92f4-5febd18fb1f7.png)

![geom_bar_interactive](https://cloud.githubusercontent.com/assets/4331618/18466539/64fac348-799c-11e6-998c-79fda2aef21f.png)


The main difference is you are using a dev version of `ggplot2`. See my `sessionInfo()`.

```
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gdtools_0.0.7 ggiraph_0.3.1 ggplot2_2.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6       digest_0.6.9      R.methodsS3_1.7.1 grid_3.2.5       
 [5] plyr_1.8.4        jsonlite_1.0      gtable_0.2.0      scales_0.4.0     
 [9] R.oo_1.20.0       R.utils_2.3.0     xml2_1.0.0        labeling_0.3     
[13] tools_3.2.5       htmlwidgets_0.7   munsell_0.4.3     yaml_2.1.13      
[17] colorspace_1.2-6  rvg_0.1.0         htmltools_0.3.5  
```

**Comment by RozennGZ** [comment]
Thanks ! I have  uninstall and re-install  ggplot2 (not from dev). It works !

**Comment by davidgohel** [comment]
cool
