### ISSUE TITLE
Toolbar elements initial state

### ISSUE THREAD

**Issue by Ari04T** [davidgohel/ggiraph#290]
Hello

I couldn't find it but is there a way to set an initial state for the toolbar elements? Say, start with pan/zoom activated by default? It looks like right now you always have to activate zoom/pan for it to work but maybe I'm just not finding where to change that.

Thanks for the great package, take care.

**Comment by davidgohel** [comment]
Hello

No sorry, that's not an option, and I don't see how to do it easily

**Comment by Ari04T** [comment]
No worries! Thanks for the (super) quick response.
