### ISSUE TITLE
Set display=none as default for automaticall created divs

### ISSUE THREAD

**Issue by giadasp** [davidgohel/ggiraph#295]
I'm sorry I cannot provide a minimal reproducible example.
If it is required please cancel this issue.
When rendering a R markdown html document with a ggiraph with tooltips inside, the javascript automatically creates the divs with class "tooltip_svg_<uid>".
These divs have as defaults the style defined in the ggplot and "position: absolute; opacity: 0"
Then, top and left attributes change values when the user hovers on the plots to show the tooltips.
Since I have some padding on the tooltip style, the divs have padding:5px as default so that they take a 5px height space in the page (after the bookdown "body" class= book).
Thus, the book "body" does not have a 100% height anymore and another scroolbar appears.
Is that possible that you fix the javascript so that those divs appear with a display:none property as a default or maybe find another solution for this bug?
Please let me know.
Giada

**Comment by davidgohel** [comment]
I am sorry, I don't understand the "bug" you are referring to.

CSS `display: none` make the element not displayed!


> I'm sorry I cannot provide a minimal reproducible example.

Can you show what you are talking about with this example : https://www.ardata.fr/ggiraph-book/selections.html#initial-selection

**Comment by giadasp** [comment]
Thank you for the prompt reply.
In your example the divs are the ones with classes "tooltip_svg_da30ce73_d43b_4dc8_b038_e15bf620ac8c" and "tooltip_svg_c1f60463_209f_4b53_a4d7_f48930339306".
As you can see, they are placed just before the end of the <body> tag and they have css style .tooltip_svg_c1f60463_209f_4b53_a4d7_f48930339306 {
    **padding: 5px;**
    background: black;
    color: white;
    border-radius: 2px;
    text-align: left;
    position: absolute;
    pointer-events: none;
    z-index: 999;
}

If there is something in the body that has "height:100%" (such as the bookdown div with class "book" that contains everything) that make the page content overflow and another vertical scroolbar appears.

**Comment by giadasp** [comment]
try to run:
```
<html>
<body>
<div class="book" style="height:100%">
</div> 
<div id="tooltip_svg_c1f60463_209f_4b53_a4d7_f48930339306" style="padding:5px">
</div> 
</body>
</html>
```

bug: you will see that a vertical scrollbar appears because the height of the body is not 100% anymore but 100%+5px

**Comment by giadasp** [comment]
Even with "position:absolute", the scroll bar is present.
Maybe setting "top" and "left" to some default can solve the issue.

**Comment by davidgohel** [comment]
note it is not related to ggiraph, when you set height to 100% and tooltip padding to 5px, ggiraph is not scanning (nor supposed to) scan settings of the web container to decide if it should modify something in your page. 

First, you can adjust your height with css (`calc` is a pure css function)

```
<html>
<body>
<div class="book" style="height:calc(100%-10px)">
</div>
<div id="tooltip_svg_c1f60463_209f_4b53_a4d7_f48930339306" style="padding:5px">
  zz
</div>
</body>
</html>

```

Or you can can use girafe options : 

```
library(tidyverse)
library(ggiraph)

dataset <- mtcars |> add_rownames(var = "carname")

gg_point <- ggplot(
  data = dataset,
  mapping = aes(
    x = wt, y = qsec, color = disp,
    tooltip = carname, data_id = carname
  )
) +
  geom_point_interactive() +
  theme_minimal()

girafe(ggobj = gg_point, options = list(opts_tooltip(css = "padding:0;")))

```

**Comment by giadasp** [comment]
Ok. I'll try the first option, the second is not estetically acceptable.
Mine was just a suggestion to make it more compatible with bookdown.
Thanks for the support.
