### ISSUE TITLE
Use in Shiny

### ISSUE THREAD

**Issue by bhaskarvk** [davidgohel/ggiraph#3]
I'm trying this

```r
output$plot <- renderggiraph({
    plot <- getPlot(input$param1, input$param2)
    return(ggiraph(code={print(plot)}))
})
```

Where getPlot is function that return a ggpol2 map. But the plot doesn't render at all. No errors in R or in javascript console. 

I know the plot generation code is correct, coz if I replace the above with

```r
output$plot <- renderPlot({
    getPlot(input$param1, input$param2)
})
```

This works, but of course the plot is not interactive in this case.

**Comment by davidgohel** [comment]
I can't reproduce the example. 

Function `ggigraph` does not exists, correct names are `ggiraph` and `renderggiraph`.

You can find a shiny example here:
https://github.com/davidgohel/ggiraph/tree/master/inst/shiny

David

**Comment by bhaskarvk** [comment]
Sorry I was manually typing code in Github, I did use the correct function names in actual code.
I'll check your sample and may be try to create a reproducible example.

**Comment by bhaskarvk** [comment]
So I made a sample reproducible app
https://gist.github.com/bhaskarvk/f61cf42c5038c176d8c0

Currently it runs only under Linux/OSX, to run under windows simply download and gunzip the geojson URL in the code. That will bypass the `system` command and allow the code to run under windows.

When I run it, the static map rendered using `renderPlot`  gets displayed, but the interactive map rendered using `renderggiraph` is not getting displayed. No errors in R or javascript console.

If you source the file, and call `ggiraph(code={print(getMap())})` on the command line, then it does work, so it's not working only in shiny. And even when it works outside of shiny, data_id seems to work for only certain columns, my map_id column is 'id', but I can't use it for data_id, I tried a few others like formal_en, but only thing that works (outside shiny) is iso_a3.

**Comment by davidgohel** [comment]
Your code failed on my mac:

    Erreur : isTRUE(gpclibPermitStatus()) n'est pas TRUE # it says isTRUE(gpclibPermitStatus()) is not TRUE

Here is my sessionInfo()

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.4.3     ggiraph_0.1.0   ggthemes_3.0.1  ggplot2_2.0.0   broom_0.4.0    
 [6] rgdal_1.0-4     rgeos_0.3-11    maptools_0.8-37 sp_1.2-1        shiny_0.13.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3       plyr_1.8.3        R.methodsS3_1.7.0 R.utils_2.2.0    
 [5] tools_3.2.3       digest_0.6.9      nlme_3.1-122      gtable_0.1.2     
 [9] lattice_0.20-33   psych_1.5.8       DBI_0.3.1         parallel_3.2.3   
[13] stringr_1.0.0     xml2_0.1.2        gdtools_0.0.6     htmlwidgets_0.5  
[17] grid_3.2.3        R6_2.1.2          rvg_0.0.6.9000    foreign_0.8-66   
[21] reshape2_1.4.1    tidyr_0.4.0       magrittr_1.5      scales_0.3.0.9000
[25] htmltools_0.3     assertthat_0.1    mnormt_1.5-3      mime_0.4         
[29] xtable_1.8-0      colorspace_1.2-6  httpuv_1.3.3      stringi_1.0-1    
[33] munsell_0.4.2     R.oo_1.19.0 
```


Then you are using **plotOutput** - you should use **ggiraphOutput**, see what is used in the exemple link I sent you:
https://github.com/davidgohel/ggiraph/blob/master/inst/shiny/ui.R#L11

**Comment by davidgohel** [comment]
OK, 

    install.packages("gpclib", type = "source") #was necessary

It works when using the correct function `ggiraphOutput("interactiveMap")` instead of `plotOutput("interactiveMap")`.

**Comment by hrbrmstr** [comment]
The `R.utils` pkg has `gunzip` in it (and works across Win/Linux/OS X)

**Comment by bhaskarvk** [comment]
Ah I see, I somehow missed that part. Thanks for pointing out, as well for an excellent project. Thanks @hrbrmstr I'll use that one.
