### ISSUE TITLE
onclick syntax

### ISSUE THREAD

**Issue by adlisval** [davidgohel/ggiraph#30]
I have a _ggplot_ and I try to make it interactive with _[ggiraph](https://davidgohel.github.io/ggiraph/introduction.html)_ package. The _tooltip_ works fine, the **_"onclick"**_ function seems to appear in the Shiny console when I click on the `geom_line`. 

But I can't make it work so when I click a `geom_line_interactive`, to change(using js) the `input type`(from `search` to `submit`) and **set** the `value` of a _dataTable_ `search input`. 

The html of the table's `search input`:

```
<input type="search" class="form-control input-sm" placeholder aria-controls="DataTables_Table_0">
```

Make new column for js used in **_onclick**_ feature:

```
dfMonth$onclick <- sprintf(
  "function clickLine(){document.getElementsByClassName(\"form-control input-sm\").type=\"submit\".value=\"%s\";}",as.character(dfMonth$ISBN) )
```

In server.R file, use the js from onclick column:

```
geom_line_interactive(aes(color=ISBN, group=ISBN, tooltip=ISBN, onclick=onclick))
```

I did try using only document.getElementsByClassName(..... without including it in a function (it has no effect on the `input` field). I can't modify the html, so I can't add an id to the input field.

Please give another 2 or 3 examples for using onclick with js. Thanks

**Comment by davidgohel** [comment]
I am not sure to understand everything, maybe a gist would help. 

I understand you want to work with shiny and you are trying to get a value from a click.

> Please give another 2 or 3 examples for using onclick with js. Thanks

You will find here an example on how to work with shiny and ggiraph:
https://github.com/davidgohel/demoggiraph

David

**Comment by adlisval** [comment]
Thanks for the link, but the example doesn't seem to use `onclick ` . 
And yes, I would like to get the value of a geom_line when **clicking**, and setting it as `value` to an `input` field. This operation should be possible with js, but I don't know why it's not working.

**Comment by davidgohel** [comment]
The example show how to select a element and get its ID in shiny.

 Are you talking about making htmlwidgets talking to each other on the client side?

**Comment by adlisval** [comment]
I guess so. I have a ggplot and a dataTable. And I want when I click on the geom_line in the plot, to get the line's value and set it as search term in the table.

**Comment by davidgohel** [comment]
OK

I don't have example ready for that and I don't know enough DT. I will try to make a gist next week.

**Comment by adlisval** [comment]
Great, thanks a lot. And thanks for the great package.

**Comment by davidgohel** [comment]
Just found that (did not try it but it looks what you're looking for): 

http://stackoverflow.com/questions/35721575/set-value-of-search-box-empty-in-datatable-by-jquery

**Comment by adlisval** [comment]
Ah, that looks interesting. So for using it with onclick feature in ggiraph, the syntax is something like this?:

`dfMonth$onclick <- sprintf("('input[type=\"search\"]').val('%s').keyup()", ,as.character(dfMonth$ISBN) )`

**Comment by davidgohel** [comment]
Not sure the selector is ok but yes, I think `.val('%s').keyup()` should work. 

* val set the value
* keyup trigger the filtering

Not sure about that but I would test it

**Comment by davidgohel** [comment]
Here is an example (without jquery):

https://gist.github.com/davidgohel/68623058bad5b42f253ec8823a732a45

You can try the shiny app by running

    runGist("https://gist.github.com/davidgohel/68623058bad5b42f253ec8823a732a45")

**Comment by adlisval** [comment]
I tested the app in gist and it looks nice, but everytime I click, I get in the Shiny console a syntax error because of the back ticks, from the server code I guess (`SyntaxError: Invalid character: '`' `) Did it work for you? Maybe I need some modifications to handle back ticks?

**Comment by adlisval** [comment]
It works. Thanks a lot. I think this can bring great possibilities to make the data even more powerful by enabling dynamic interaction between different widgets ("making htmlwidgets talk to each other"). 

I avoided the syntax error mentioned above, by changing `data$onclick <- paste0("set_search_val(`", data$label, "`);")` to `data$onclick <- sprintf("set_search_val(\"%s\");",as.character(data$label))`
