### ISSUE TITLE
Tooltip issue when using some shapes 

### ISSUE THREAD

**Issue by ndumin** [davidgohel/ggiraph#31]
It seems that I can choose either 'tooltip' or 'shape', but not both:

```
df1 <- data.frame (
    x = 1:5
  , y = 1:5
  , type = c ('a', 'b', 'c', 'd', 'e')
  , kind = c ('v', 'w', 'x', 'y', 'z')
);

gg <- ggplot (
    df1
  , aes (
        x = x
      , y = y
    )
) +
geom_point_interactive (
    aes (
        shape   = type
      , tooltip = kind
    )
);

ggiraph (code = { print (gg) }, width = 1, height_svg = 9, width_svg = 18);

Error: length(ids) == length(str) is not TRUE
```

Is there a way to make this work?

**Comment by ndumin** [comment]
Sorry -- I wasn't clear what I was looking for.

Your suggestion uses letter names as the shape of each point on the graph.  I don't want that.

I want the default ggplot2 shapes (circle, triangle, square, etc.), like what I would get if I didn't use 'tooltip' at all:

```
gg <- ggplot (
    df1
  , aes (
        x = x
      , y = y
    )
) +
geom_point_interactive (
    aes (
        shape   = type
#      , tooltip = kind
    )
);

ggiraph (code = { print (gg) }, width = 1, height_svg = 9, width_svg = 18);
```

Except that I also want to use 'tooltip' to display the value of "kind" when I hover over each point.

I tried a few variations of your example, but couldn't get it to do what I'm looking for.

**Comment by davidgohel** [comment]
OK, You can't have all the default shape as shape 3, 4 and 7 to 14 are composite symbols.

![symbols](http://sape.inf.usi.ch/sites/default/files/ggplot2-shape-identity.png)

So you will need to specify them with `scale_shape_manual` and make sure 3, 4 and 7:14 are not in the customized scale.  

```
df1 <- data.frame (
  x = 1:5
  , y = 1:5
  , type = c ('a', 'b', 'c', 'd', 'e')
  , kind = c ('v', 'w', 'x', 'y', 'z')
);
shps <- setNames( c(0, 1, 2, 5, 6, 15), df1$type )

gg <- ggplot (
  df1
  , aes (
    x = x
    , y = y
  )
) +
  geom_point_interactive (aes (shape   = type, tooltip = kind), size  = 3) + 
  scale_shape_manual(values = shps)

ggiraph (code = { print (gg) }, width = 1, height_svg = 9, width_svg = 18);
```

**Comment by ndumin** [comment]
Thanks for the help!  It works now.

I didn't realize those shapes were special.

I really do appreciate that you took time to help me with this.

PS -- I really like the capabilities that ggiraph provides!  Thank you for providing it!

**Comment by davidgohel** [comment]
Maybe there are workarounds - I will try (later)

**Comment by davidgohel** [comment]
I have added a note in the man of `geom_point_interactive`.

David
