### ISSUE TITLE
zoom_max

### ISSUE THREAD

**Issue by cardiomoon** [davidgohel/ggiraph#33]
Thank you for wonderful package !!

After the update to ggiraph 0.3.1.9000 and ggplot2 2.1.0.9001, I am not able to use zoom the plot with the following code.

data=mtcars
data$id=1:nrow(data)

p<-ggplot(data=data,aes(x=wt,y=mpg))+
      geom_point_interactive(aes(tooltip=rownames(data),data_id=id))

ggiraph(code={print(p)},zoom_max=10)

I am using R version 3.3.2, MacOS 10.11.4 and RStudio 1.0.44

**Comment by davidgohel** [comment]
This is temporary. I am migrating from d3 v3 to v4 and have to refactor the zoom/pan 

David

**Comment by davidgohel** [comment]
Hello,

The zoom is back.

David

**Comment by cardiomoon** [comment]
Dear David Gohel,

Thank you very much !

I really appreciate your packages.

Sincerely,

Keon-Woong Moon


2016. 11. 4. 오후 8:59 David Gohel <notifications@github.com> 작성:
