### ISSUE TITLE
Sizing Policy

### ISSUE THREAD

**Issue by paulofelipe** [davidgohel/ggiraph#35]
First of all, thanks for this package.

I have a question about the `sizingPolicy` in`ggiraph.R`. Is there any reason to avoid `browser.fill = TRUE`?

```
htmlwidgets::createWidget(
			name = 'ggiraph',
			x,
			width = NULL,
			height = NULL,
			package = 'ggiraph',
			sizingPolicy = sizingPolicy(knitr.figure = FALSE)
)
```

I'm having problems with this package in a flexdashboard environment. The ggiraph output does not fit the panel. 

Thank you,

Paulo.

**Comment by davidgohel** [comment]
This would have no effect, see parameters `width` and `width_svg, height_svg`.

I will have a try this week. What is the choosen layout?

David

**Comment by paulofelipe** [comment]
I'm using the column layout with this example:

```
dataset = iris
dataset$tooltip = paste0("Specie: ", dataset$Species, "\n",
                         "Sepal Length: ", dataset$Sepal.Length)
dataset$clickjs = paste0("alert(\"",dataset$Species, "\")" )

# plots
gg_point = ggplot(dataset, aes(x = Sepal.Length, y = Petal.Width,
		color = Species, tooltip = tooltip, onclick = clickjs) ) +
	geom_point_interactive(size = 3) 

ggiraph(code = {print(gg_point)})
```

I'm creating 2 x 2 dashboard. If I use the default values for `width_svg` and `height_svg`, the height of the plot is higher than the panel. Even if a select a large value, the `width` resizes automatically.

In order to observe the same effect in the height, I change `.style( "position", "static")` for FlexDashboard in `ggiraph.js`.

Thanks,

Paulo.

[teste_ggiraph.zip](https://github.com/davidgohel/ggiraph/files/579179/teste_ggiraph.zip)

**Comment by davidgohel** [comment]
I made tests and indeed, it does not always fit in flexdashboard. There is no bug, it's just how things are implemented (you must have an original width and height when generating a graph). 

You should tune a width greater than height and maybe use `vertical_layout: scroll` in flexdashboard.

**Comment by paulofelipe** [comment]
I was interested in a responsive plot. I understand the design of the package. By the way, great package! Thank you!

**Comment by davidgohel** [comment]
I understand (it's only responsive *horizontally*). 
Maybe later when I will be more efficient with d3.js
