### ISSUE TITLE
shinyapps.io and ggiraph

### ISSUE THREAD

**Issue by garthtarr** [davidgohel/ggiraph#37]
FYI, I've just submitted a question to RStudio, regarding the interaction between shinyapps.io and the ggiraph package.

https://support.rstudio.com/hc/en-us/community/posts/239330128-shinyapps-and-ggiraph

Repeated below in case you have any suggestions.

###########

There's a nice package, ggiraph, that gives tooltips to ggplots (amongst other features).  

It works perfectly when run locally, however, when run on the shinyapps.io server it fails.  This also happens when I generate a rmarkdown report - I get the same error which prevents the report being created.

I've loaded a minimal worked example here:

https://garthtarr.shinyapps.io/ggiraphtest/

 

When I run the same code locally, it works:

```s
library(shiny)
require(ggiraph)

server <- function(input, output) {
output$distPlot <- renderggiraph({

x = data.frame(x = rnorm(26),
y = rnorm(26),
lab = letters)
p = ggplot(x,aes(x=x,y=y,tooltip=lab)) + 
geom_point_interactive()
ggiraph(code = {print(p)}, width = 0.75)
})
}

ui <- fluidPage(
ggiraphOutput("distPlot")
)

shinyApp(ui = ui, server = server)
```

Any ideas on how I can overcome this?

**Comment by davidgohel** [comment]
Hi,

I can't reproduce the issue. 
What's your sessionInfo?

**Comment by garthtarr** [comment]
False alarm .... I installed the latest github version and it's now working... thanks!  I didn't think the package version would be the issue because it was working locally but not when I pushed it out to shinyapps.io, but it must have been.  Now working here: https://garthtarr.shinyapps.io/ggiraphtest/

**Comment by davidgohel** [comment]
Cool
Good news for me :)

David
