### ISSUE TITLE
Is it possible to derive data points by selecting subpopulations in the graphs?

### ISSUE THREAD

**Issue by codingbutstillalive** [davidgohel/ggiraph#38]
Hi!

Thanks for this cool package. I wonder if it will be possible to receive user-selected data points from the graphs. This feature would also be useful to update a second (or third) plot based on the current selection of points in a graph.

Best regards,
Sebastian

**Comment by davidgohel** [comment]
Hi,

Yes, in shiny.
There are examples available here:
https://github.com/davidgohel/ggiraph/tree/master/inst/shiny

David

**Comment by codingbutstillalive** [comment]
Thank you!
