### ISSUE TITLE
geom_histogram

### ISSUE THREAD

**Issue by GiovanninoPaneEvino** [davidgohel/ggiraph#42]
This is amazing! Would it be possible though to add the geom_histogram? Thanks for the consideration :-)

**Comment by davidgohel** [comment]
It's possible, but you would only get one single tooltip per histogram.

**Comment by daattali** [comment]
Yep, one tooltip for bin. Still would be cool :)

**Comment by davidgohel** [comment]
`geom_histogram_interactive` has been implemented (one could only get one single tooltip per group/histogram).

**Comment by ChristelSwift** [comment]
hi David, could you give an example of how you can specify the tooltip for a histogram to show the frequency for each bin please?

**Comment by davidgohel** [comment]
Hi, sure 

```
zz <- ggplot(diamonds, aes(carat, tooltip = ..count..)) + geom_histogram_interactive() 
ggiraph(ggobj = zz)
```

This SO post explain the `..count..` better than I would: 
https://stackoverflow.com/a/30058379/3315962
