### ISSUE TITLE
Zoom_max option in Shiny

### ISSUE THREAD

**Issue by jbergenstrahle** [davidgohel/ggiraph#46]
Hi David,

I'm using ggiraph in my shiny application. However, the zoom function does not work. The plot works with zoom outside of shiny if I just open it in a single browser window. However, In shiny, the "scroll wheel" only scrolls the whole window, without zooming. 

Is the zooming supposed to work in shiny? I'm using the ggiraphOutput to create the output element. This would be a great addition to your package if this is not implemented. Or I'm doing something wrong?

---------------------------------------------------------------------------
dummy example
----------------
server.R
-----------
```R
shinyServer(function(input,output, session) {
  
  
  output$testPlot <- renderggiraph({
    
    data = as.data.frame(cbind(c(1,2,3,4,5), c(1,2,3,4,5)))
    
    gg<- ggplot(data=data, aes(x=data$V1, y=data$V2)) + 
      xlab("X coordinate")+ylab("Y coordinate")+ coord_equal() +
      geom_point_interactive(
        aes( data_id = rownames(data), tooltip=rownames(data)), col="black", size = 3, alpha = 0.4 ) +
      theme(
        legend.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent", colour = NA),
        plot.background = element_rect(fill = "transparent", colour = NA),
        axis.title.x = element_text(colour = "orange"),
        axis.title.y = element_text(colour = "orange"),
        legend.title = element_text(colour = "orange"),
        legend.text = element_text(colour = "orange"),
        panel.grid = element_line(linetype="dashed"),
        panel.grid.major = element_line(colour = "gray")
      )
    
    ggiraph(code=print(gg), zoom_max=5, selection_type = "single",
            width = 1,  hover_css = "fill:#FF3333;stroke:black;cursor:pointer;", selected_css = "fill:#FF3333;stroke:black;")
  })
})

```
------------
ui.R
------------
```R
navbarPage("Test",

ggiraph::ggiraphOutput("testPlot")
)
```
-------------------------------------------------------------------------------------------

Thanks,
Joseph

**Comment by davidgohel** [comment]
Hi Joseph,

This happens because there is no plot.background color, therefore, there is no element to catch the scroll action (if scrolling on a poitn for example, it works as expected... but that's not intuitive). 

The following code should work:

```
shinyServer(function(input,output, session) {
  
  
  output$testPlot <- renderggiraph({
    
    data = as.data.frame(cbind(c(1,2,3,4,5), c(1,2,3,4,5)))
    
    gg<- ggplot(data=data, aes(x=data$V1, y=data$V2)) + 
      xlab("X coordinate")+ylab("Y coordinate")+ coord_equal() +
      geom_point_interactive(
        aes( data_id = rownames(data), tooltip=rownames(data)), col="black", size = 3, alpha = 0.4 ) +
      theme(
        legend.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent", colour = NA),
        plot.background = element_rect(fill = "white", colour = NA),
        axis.title.x = element_text(colour = "orange"),
        axis.title.y = element_text(colour = "orange"),
        legend.title = element_text(colour = "orange"),
        legend.text = element_text(colour = "orange"),
        panel.grid = element_line(linetype="dashed"),
        panel.grid.major = element_line(colour = "gray")
      )
    
    ggiraph(code=print(gg), zoom_max=5, selection_type = "single",
            width = 1,  hover_css = "fill:#FF3333;stroke:black;cursor:pointer;", selected_css = "fill:#FF3333;stroke:black;")
  })
})
```

David

**Comment by jbergenstrahle** [comment]
Thanks a lot David,

I realized a few things after your comments. 
You are correct that without background, zooming can only be performed via the spots, and by adding a background that is fixed. However, after some testing I realized that the zooming only works if you open your shiny app in the browser (which in the end will be most important), but not when you run the app with "Run in Window" from your local R session. Maybe this is a obvious thing, but might be worth mentioning.

Thanks for the quick reply and a great package

/JB

**Comment by davidgohel** [comment]
I can zoom in viewer pane and in a shiny app displayed in rstudio browser. 

What is your os and what is your rstudio version?

**Comment by jbergenstrahle** [comment]
I see, might be something on my end then. I just updated to newest rstudio but still the same.

R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

**Comment by davidgohel** [comment]
OK, I leave the issue open, I will have a try on a VM later.

**Comment by davidgohel** [comment]
Sorry, I was not able to reproduce that issue (tried with ubuntu rstudio OS server and on my local OX installation).

Reopen if necessary.
