### ISSUE TITLE
Error when trying to use geom_point_interactive inside another package: Error in eval(expr, envir, enclos) : object 'Geom' not found

### ISSUE THREAD

**Issue by osofr** [davidgohel/ggiraph#48]
Hi, 

I am trying to call `geom_point_interactive` inside my package. This fails, however, even when I import the entire namespace of `ggplot2` and `ggiraph`. I've tried this on CRAN and dev versions of `ggplot2` and `ggiraph`.

So I am importing the name spaces of both packages (would prefer to avoid importing everything, but it still fails even with this set-up): 
```R
#' @import ggplot2
#' @import ggiraph
```

I also have the following plotting function (exported by my package):

```R
plotMSEs <- function(PredictionModel, K = 1) {
  datMSE <- PredictionModel$get_best_MSE_table(K = K)
  datMSE[["model"]] <- factor(datMSE[["model"]], levels = datMSE[["model"]][order(datMSE[["MSE"]], decreasing = TRUE)]) # order when flipping coords
  datMSE$tooltip <- "MSE = " %+% format(datMSE[["MSE"]], digits = 3, nsmall=2) %+% " [" %+% format(datMSE$CIlow, digits = 3, nsmall=2) %+% "-" %+% format(datMSE$CIhi, digits = 3, nsmall=2)  %+% "]"
  datMSE$onclick <- "window.location.hash = \"#jump" %+% 1:nrow(datMSE) %+% "\""
  p <- ggplot(datMSE, aes(x = model, y = MSE, ymin=CIlow, ymax=CIhi)) 
  p <- p + geom_point_interactive(aes(color = algorithm, tooltip = tooltip, data_id = model.id, onclick = onclick), size = 2, position = position_dodge(0.01)) # alpha = 0.8
  p
}
```

Trying to call this function fails with an error: "Error in eval(expr, envir, enclos) : object 'Geom' not found"

Note that everything works perfectly the moment I add a line `require("ggplot2")` to the above function code. The trouble is, its not kosher to do such things inside packages, so I am looking for an alternative solution. Any thoughts on what might be causing this? Much appreciated and thanks for an awesome package. 

Best,
Oleg

**Comment by davidgohel** [comment]
Hi,

Not sure about this but I would *requires* ggplot2, see:
https://github.com/davidgohel/ggiraph/blob/master/DESCRIPTION#L13

`ggrepel` is using that option also:
https://github.com/slowkow/ggrepel/blob/master/DESCRIPTION#L13

David

**Comment by osofr** [comment]
Thanks. 

Ideally I would like to avoid loading the entire namespace of ggplot2, given that my package is using it only once inside a small function. That function is not crucial to overall functionality of the package. I guess what you are saying is that at the moment there is no way of avoid this?

**Comment by davidgohel** [comment]
Unless identifying all functions to import from ggplot2, I don't see alternative for now
