### ISSUE TITLE
 Tooltip error

### ISSUE THREAD

**Issue by fmusili** [davidgohel/ggiraph#49]
Have been using tooptips for sometime now but today all over a sudden they are giving an error when in shiny as shown in the picture:

<img width="564" alt="screenshot 2017-02-24 12 03 41" src="https://cloud.githubusercontent.com/assets/25815765/23297353/4b0d6660-fa8a-11e6-969f-5fdb371c5a52.png">

 the background text is messing my shiny app, kindly help.

**Comment by davidgohel** [comment]
Sorry, it's not possible to reproduce the issue here. 

Reopen the issue if necessary but provide `sessionInfo()` and an code that I can run.

KR,
David
