### ISSUE TITLE
Throw error for "bad" characters for tooltips

### ISSUE THREAD

**Issue by mmillsexp** [davidgohel/ggiraph#5]
I have found that using the `'` (single quotes) character the `tooltip` functionality will not display any tooltips for any points, even those without the bad character:

```
dataset <- mtcars
dataset$tooltip <- row.names(dataset)

good_tooltip <- ggplot(dataset, aes(x = disp, y = qsec, color = wt, tooltip = tooltip)) + 
  geom_point_interactive(size=3)
ggiraph(code = {print(good_tooltip)}, width = 7, height = 6)
## Tooltips work as expected

dataset$tooltip[1] <- "bad' character"
bad_tooltip <- ggplot(dataset, aes(x = disp, y = qsec, color = wt, tooltip = tooltip)) + 
  geom_point_interactive(size=3)
ggiraph(code = {print(bad_tooltip)}, width = 7, height = 6)
## No tooltips displayed
```

If this isn't a bug with your package but just a limitation of what JS/Bootstrap allows in the tooltip can those special characters be listed somewhere in the package documentation? I don't know much at all about what goes in to making the tooltips so I know myself and I would assume most R users who don't know much about JS would really appreciate it.

**Comment by davidgohel** [comment]
True.

I think this can be solved by raising an error if a bad character is used. And a note in the help file of course.

David

**Comment by mmillsexp** [comment]
That would be awesome, thanks!

**Comment by bhaskarvk** [comment]
Alternatively you can wrap the tooltip text in `htmltools::htmlEscape(tooltip, TRUE)`.

**Comment by mmillsexp** [comment]
Thanks @bhaskarvk, that fixed it!

**Comment by davidgohel** [comment]
Hi,

The function complains now when a single quote is in a tooltip.

@bhaskarvk @mmillsexp thanks for the tip, very useful. Note this can't be used when using custom HTML (with tags) as "<" will be transformed as "&lt;".

**Comment by antuki** [comment]
Thank you for fixing this issue ! However, i'm interested if someday you find a solution to be able to add single quotes (apostrophes in french) in tooltips which is a character very used in french sentences (i'm currently using " instead but it's not very pretty). I really love using ggiraph and i'm testing all possibilities !

**Comment by davidgohel** [comment]
@antuki please use `&#39;` instead, i.g. write a function that transform your text:

```
someday_true <- function(x){
  gsub("'", "&#39;", x )
}
```

**Comment by antuki** [comment]
Perfect, thank you. I just read that "\'" may work too !
