### ISSUE TITLE
Shiny: can't fix height of ggiraphOutput() 

### ISSUE THREAD

**Issue by awunderground** [davidgohel/ggiraph#50]
Thank you for making a great package!

This may be similar to #35 Sizing Policy.

I'm struggling to get predictable plot sizes in Shiny applications using ggiraphOutput. 
```
ggiraphOutput("chart", width = "100%", height = "400px")
```
I was hoping this would render a plot with height of 400 pixels and the width would vary based on the browser width, but the height of my plot changes based on browser size. Additionally, the font sizes change and are generally much bigger than without `ggiraph`. Here's the `ggplot2` call:

```
      gg_bar <- distribution %>%
        ggplot(aes(x = percentile, y = value, fill = subgroup, tooltip = tooltip)) +
          geom_bar_interactive(position = "dodge", stat = "identity") +
          scale_y_continuous(limits = c(y.min, as.numeric(y.max)), labels = scales::dollar) +
          expand_limits(y = origin) +
          theme_urban() +
          theme(axis.ticks.length = unit(0, "points"),
                     axis.line = element_blank())
    
      ggiraph(code = {print(gg_bar)}, width = 1, height = 5.418)
```
I tried setting the height in pixels and then coming up with a ratio of height in inches and width in inches that made sense. Is there any way around this issue? Am I missing something or is this something that needs to be developed?

**Before:**

![without](https://cloud.githubusercontent.com/assets/11818850/23564539/4e2e0898-0018-11e7-9936-e155db622fa4.PNG)

**After:**

![width](https://cloud.githubusercontent.com/assets/11818850/23564547/5686e4d8-0018-11e7-8a1c-13fcf5cadb15.PNG)

**Comment by davidgohel** [comment]
Sorry for the delay. 

I have made improvements in the sizing management. 
With the new version (on github for now), widget should fit available size in shiny applications. `width` can be used to limit the width of the graph (1 meaning 100% and .5 half the available space)

I made a note about sizing here: https://davidgohel.github.io/ggiraph/articles/sizing.html

In your case, I think `width` should be around `.7`. 

Could you make a try and tell me if it's better?

David

**Comment by RobertMyles** [comment]
@awunderground Can I ask what `theme_urban` is??? Looks awesome!

(sorry for commenting on a closed issue, I haven't been able to find any info on that theme anywhere!)

**Comment by awunderground** [comment]
@RobertMyles I work at the Urban Institute. We have a [ggplot2 theme](https://github.com/UrbanInstitute/urban_R_theme) that gets _close_ to our [style guide](http://urbaninstitute.github.io/graphics-styleguide/).

**Comment by RobertMyles** [comment]
@awunderground Awesome, thanks.
