### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by cardiomoon** [davidgohel/ggiraph#51]
Thank you for developing great packages.
I have developed "ggiraphExtra" package using your package ggiraph and made a shiny app for exploratory plots. It works very well. Please visit http://web-r.org:3838/explore.
But recently after update of ggiraph package to 0.3.3, my shiny app cause javascript error.

Following is a captured image.

http://web-r.org/?module=file&act=procFileDownload&file_srl=13845&sid=a33bf23f45781efa503a22fadc955ac2&module_srl=126

Uncaught Reference Error: ggiraph is not defined at Object.factory.
You can see the other app causing error at : http://r-ggplot2.com:3838/explore.

How can I fix it?

**Comment by davidgohel** [comment]
Hello,

for now, I have no idea what is going on.

Can you provide a reproducible example (a code I could ship in a simple shiny app)?  

Thanks
David

**Comment by davidgohel** [comment]
Here is what I tried (but it works):

```
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(ggiraphExtra)
library(ggiraph)
xx <- ggPoints(aes(x=wt,y=mpg,color=am),data=mtcars,method="lm",interactive=TRUE)

ui <- fluidPage(

   # Sidebar with a slider input for number of bins
   sidebarLayout(
      sidebarPanel(),

      # Show a plot of the generated distribution
      mainPanel(
         ggiraphOutput("distPlot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

   output$distPlot <- renderggiraph({
     print(xx)
   })
}

# Run the application
shinyApp(ui = ui, server = server)
```

**Comment by cardiomoon** [comment]
It is related to renderUI.
Followings are reproducible example.

library(shiny)
library(ggiraph)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
  uiOutput("test") 
  
   
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
  output$test=renderUI({
      tagList(
        ggiraphOutput("Plot"),
        plotOutput("Plot1")
      )
  })
  
   output$Plot <- renderggiraph({
     g <- ggplot(mpg, aes( x = displ, y = cty, color = hwy) ) + theme_minimal()
     my_gg <- g + geom_point_interactive(aes(tooltip = model), size = 2) 
     ggiraph(code = print(my_gg), width = .7)
   })
   
   output$Plot1 <- renderPlot({
     g <- ggplot(mpg, aes( x = displ, y = cty, color = hwy) ) + theme_minimal()
     g+geom_point()
   })
}

# Run the application 
shinyApp(ui = ui, server = server)

**Comment by davidgohel** [comment]
Sorry, I can't reproduce, everything is ok on my local installation.

Do you have other informations that could help? Also in the link you sent (http://r-ggplot2.com:3838/explore), there is no error.

**Comment by cardiomoon** [comment]
In large shiny app, you have to put one or more ggiraphoutput in ui.R. If you put all ggiraphoutput in server.ui(only uiOutput in ui.R), the ggiraphoutput is not able to be seen in certain circumstances.
I am not sure the reason.
