### ISSUE TITLE
IE 11 Compatibility Issue

### ISSUE THREAD

**Issue by IanWesley** [davidgohel/ggiraph#52]
Sorry for not sending a pull request.  After I wrote you on Stake Overflow I realized there had been some tweaks since the CRAN version.  I figured I would test this out this morning.  But when I installed the development version from github, I ran into some errors.  Rather than submit a pull request without testing it I thought it would be better to open an issue and let you correct it.   

I was able to solve all of my IE 11 compatibility issues by modifying the resize_ function that used to live in \ggiraph\htmlwidgets\lib\styles-0.0.1\styles.js.  However it looks like you have made some changes to this function and moved it to ggiraph-lib.js.  Basically changing the .style to .attr seemed to resolve all of my issues - I don't know the difference between how d3 treats .style and .attr, but it solved my problem.   

My guess is making a similar change to your new resize function would do the trick:

```
function resize_(id_str, width, height) {

  if( !window[id_str + '_flexdashboard'] ) return ;

  var svg_elt = d3.select('#' + id_str + " svg");
  var ratio = window[id_str + '_ratio'];
  var h_max = width / ratio;
  if( h_max > height ){
    var width_ = width * (height / h_max );
    svg_elt.attr("width", width_ ).attr("height", height );
  } else {
    svg_elt.attr("width", width ).attr("height", height );
  }
}
```
Also please let me know if there are any bit sized things you could use a hand with on ggiraph.  It is great and I would be happy to help anyway I can!

**Comment by davidgohel** [comment]
Hi

I got the reason: IE11 doesn't support classes...
https://kangax.github.io/compat-table/es6/

I need to *up* my JavaScript skills to solve that (seems that typescript may be the solution...).

**Comment by davidgohel** [comment]
Hi

Can you have a try with the new version? I think it is OK now.
