### ISSUE TITLE
Hover effect over duplicated ids (e.g. geom_map_interactive/geom_polygon_interactive)

### ISSUE THREAD

**Issue by TommiKarki** [davidgohel/ggiraph#53]
Hi David,

Thanks for the fantastic package.

#26 selection with duplicated id works, how about hover effect when there are duplicated ids?

For example with with geom_map_interactive, if there are several polygons with the same id, the same tooltip shows for all polygons with the same id, but the mouse hover only highlights each one of the polygons at a time, but not all of them (of course, it selects the one which the mouse is hovering on).

This might often be the desired action, but is there a way to have the mouse hover to highlight all elements with the same id simultaneously?

See for example the state "Michigan" in the example of geom_map_interactive, the mouse hover only highlights southern or northern part at once, whilst it is one state with single id.

**Comment by davidgohel** [comment]
Hi

yeah, I know about that. I will do something soon.

**Comment by ehbick01** [comment]
Hey!

This seems to be happening for duplicated IDs for similar plots across multiple `blogdown` rendered posts as well. Does this fall under the same issue?

When building a `geom_rect_interactive` object across three separate rmd files that are rendered as separate blog posts, the data-id for the last rmd rendered is used across all of the `geom_rect_interactive` objects.

**Comment by davidgohel** [comment]
Hi,

No, I don't think that is the same issue. 
 
Could you open a new issue please? (don't forget the `sessionInfo()`result where I can read ggiraph and rvg versions)

David
