### ISSUE TITLE
ggRadar interactive shifts graph location right

### ISSUE THREAD

**Issue by GeraldCNelson** [davidgohel/ggiraph#54]
With the following code running in RStudio, the plot is centered in the plot window when Interactive = FALSE, but is shifted to the right when interactive is true and the legend is cut off.

```
  p <- ggRadar(spiderData, aes(colour=year), rescale = FALSE, interactive = TRUE, use.label = FALSE,
               legend.position = "right")
```

**Comment by GeraldCNelson** [comment]
While I don't understand why the interactive setting causes the graph to show up in a different place in the Rstudio plot window, it appears to be related to how the graph is initially sized and then resized when the window shape is changed.

**Comment by davidgohel** [comment]
I am not author of `ggiraphExtra`. 

However, there was an size and position issue that should be fixed now and I suspect this was linked to your issue. 

KR
