### ISSUE TITLE
Exporting the svg?

### ISSUE THREAD

**Issue by ldecicco-USGS** [davidgohel/ggiraph#56]
I'm sure I've missed it somewhere, but is there a way to export the svg?

**Comment by davidgohel** [comment]
it's an htmlwidget, you can `htmlwidgets::saveWidget()` or use Rmarkdown documents

**Comment by ldecicco-USGS** [comment]
Unless I'm mistaken (TOTALLY probable), that saves the html. What I'm trying to figure out is if I could just export the svg? So, like what `ggsave` would  if you specified a svg format, except with all the id's that I specify with this package (and maybe custom style or javascript). 

This would really help me with collaborating with other projects that don't use R, and don't want to use an iframe (for instance, I can tell the graphic designer that I gave the polygons or paths certain id's, then they could mess with the css)

**Comment by davidgohel** [comment]
No you're right.

You can export the svg by using `rvg::dsvg()`, you would get a svg file with its id but you would loose lot of features also.

David

**Comment by ldecicco-USGS** [comment]
Looks pretty promising, thanks!

**Comment by ldecicco-USGS** [comment]
Whoops...that last one was responding to a different thread...but anyways - this is exactly what I need, thanks a ton!

**Comment by davidgohel** [comment]
you're welcome

**Comment by sjackman** [comment]
Export to SVG
```r
dsvg(file = "mtcars.svg")
ggplot(mtcars, aes(x = hp, y = mpg, tooltip = paste(hp, mpg))) + geom_point_interactive() 
dev.off()
```

Export to HTML
```r
htmlwidgets::saveWidget(file = "mtcars.html",
  girafe(print(ggplot(mtcars)
    + aes(x = hp, y = mpg, tooltip = paste(hp, mpg))
    + geom_point_interactive())))
```

The HTML is interactive. Hovering over the data points reveals the tool tip. The SVG is not however interactive (when viewed with Safari, Chrome, or Gapplin). Is it possible to make an interactive SVG?

**Comment by davidgohel** [comment]
No

> You can export the svg by using rvg::dsvg(), you would get a svg file with its id but you would loose lot of features also.

**Comment by davidgohel** [comment]
If you want to get rid of R ecosystem after the SVG is produced, you will need 

1. to use JavaScript libraries located here: 
https://github.com/davidgohel/ggiraph/tree/master/inst/htmlwidgets/lib
2. To adapt code https://github.com/davidgohel/ggiraph/blob/master/inst/htmlwidgets/girafe.js and https://github.com/davidgohel/ggiraph/blob/master/R/girafe.R#L114 to produce output necessary for your technology 

In that case, I would recommend you to recode everything from scratch if only interested in tooltips and hover effects. Any solution would require knowing what will be the target (a static web site with Hugo? a node server? a python server, ...)

**Comment by sigmapi** [comment]
I have started this, as I too wanted to export a graph into standalone SVG that contains a minimal javascript, so that can be interactive (tooltip, hover and onclick actions). Either viewed as is in a browser or embedded in a web page.
But it's not fully complete yet and I haven't thought how to publish it. 
It could evolve to a feature in ggiraph.

**Comment by sjackman** [comment]
I was thinking of either…
1. a standalone SVG shared with someone on say Slack
2. an SVG on a static web site, possibly GitHub Pages

Thanks for your answer, David. I'll stick with a saved HTML widget file for now to share my results with others.
