### ISSUE TITLE
ggiraph input$plot_selected

### ISSUE THREAD

**Issue by calkcc** [davidgohel/ggiraph#58]
Hi David,

This is a question for using ggiraph and the on click event for maps on Shiny, further to the issue highlighted on this link:

https://github.com/davidgohel/ggiraph/issues/20

I have two maps on two separate tabs on Shiny: map1 on tab1 and map2 on tab2.

It appears that the input$selected_plot on reacts to the selection on map1, but not map2.

Is it possible to register input$selected_plot from multiple plots, or is it just the first plot which has the selection argument specified?

I have the following:

output$plot1=renderggiraph({ggiraph(code=print(p1()),width=1.2, height=3.6, selection_type="single")})
output$plot2=renderggiraph({ggiraph(code=print(p5()),width=1.2, height=3.6, selection_type="single")})

Both of which have their data_id set up for both plots. I just need to know if input$selected_plot only reacts to one plot or not. I can't get it to react to the second one, as the selection remains null when I switch over to the second tab and try to click on an area.

Thanks,
Calvin

**Comment by davidgohel** [comment]
Hi 

If there are 2 ggiraph, there are two different set of selection, each related to its own plot.

The selection remains null because the `input$selected_plot` is not linked to any plot. You should play with `input$selected_plot1` and `input$selected_plot2`instead (**input$selected_** + `id`)
