### ISSUE TITLE
could not find function "dsvg"

### ISSUE THREAD

**Issue by AlexandraOikonomopoulou** [davidgohel/ggiraph#59]
When I am trying to make just a simple scatter plot it runs ok. When I use the command 
ggiraph(code = print(q), width = .5) 

An error appears 
Error in ggiraph(code = print(p)) : could not find function "dsvg"

This happens even when I use the examples. Any thoughts what this error could be?

**Comment by davidgohel** [comment]
something must be wrong in your installation. Without `sessionInfo()` nor reproducible code, I can't do anything.
