### ISSUE TITLE
Tooltip style

### ISSUE THREAD

**Issue by kismsu** [davidgohel/ggiraph#6]
Hi, is there any easy way to change tooltip style? I'd like to make a box a bit more transparent.

Thank you in advance

**Comment by davidgohel** [comment]
There will be.

You can overwrite the css but it's not elegant.

**Comment by kismsu** [comment]
To be honest I'm not really strong in CSS. Where is a style definition for the tooltip? Is is a part of a Bootstrap?

**Comment by davidgohel** [comment]
Hi,

Function `ggiraph` has now an argument `tooltip_extra_css` that can contain css instructions.
