### ISSUE TITLE
Shiny Rmd Flexdashboard - Chart does not display

### ISSUE THREAD

**Issue by philstraforelli** [davidgohel/ggiraph#60]
I'm trying to use `ggiraph` in a shiny flexdashboard, but I was running into an issue where the `ggiraph` chart does not appear even though the `ggplot` chart does.

Here's a reproducible example of the issue I'm running into:

    ---
    title: "Untitled"
    output: 
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
    runtime: shiny
    ---

    ```{r setup, include=FALSE}
    library(flexdashboard)
    library(ggiraph)
    library(magrittr)
    dataset = iris
    dataset$tooltip = dataset$Species
    dataset$clickjs = paste0("alert(\"",dataset$Species, "\")" )
    ```

    Inputs {.sidebar}
    ---

    ```{r}
    selectInput("Species", "Species", choices = c("setosa", "versicolor", "virginica"))

    filtered_df <- reactive({
          	dataset[dataset$Species == input$Species, ]
    })
    ```

    Column
    -----------------------------------------------------------------------

    ### Chart

    ```{r}
    plot <- reactive({
	     ggplot(filtered_df(), aes(x = Sepal.Length, y = Petal.Width,
                                    color = Species, tooltip = tooltip, onclick = clickjs) ) +
       geom_point_interactive()
    })

    renderggiraph({
	     ggiraph(code = {print(plot())}, flexdashboard = TRUE) 
    })
    ```

Please let me know if you need more details. The chart appears in the Viewer pane, but not after changing the option in the sidebar. Same if I move the app onto Chrome. It doesn't appear on Firefox at all.

**Comment by davidgohel** [comment]
Hello, 

Thanks for reporting that. I don't know yet if this can be fixed, it works when not programming with Rmd but with R standard code. 

David

**Comment by davidgohel** [comment]
Hello

Problem should be fixed now (you don't need `flexdashboard=TRUE` anymore)


    ---
    title: "Untitled"
    output: 
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
    runtime: shiny
    ---

    ```{r setup, include=FALSE}
    library(flexdashboard)
    library(ggiraph)
    library(magrittr)
    dataset = iris
    dataset$tooltip = dataset$Species
    dataset$clickjs = paste0("alert(\"",dataset$Species, "\")" )
    ```

    Inputs {.sidebar}
    ---

    ```{r}
    selectInput("Species", "Species", choices = c("setosa", "versicolor", "virginica"))

    filtered_df <- reactive({
          	dataset[dataset$Species == input$Species, ]
    })
    ```


    Column
    -----------------------------------------------------------------------

    ### Chart

    ```{r}
    plot <- reactive({
	     ggplot(filtered_df(), aes(x = Sepal.Length, y = Petal.Width,
                                    color = Species, tooltip = tooltip, onclick = clickjs) ) +
       geom_point_interactive()
    })

    renderggiraph({
	     ggiraph(code = {print(plot())}) 
    })
    ```
