### ISSUE TITLE
Export the GeomInteractive* objects

### ISSUE THREAD

**Issue by Tutuchan** [davidgohel/ggiraph#62]
I'm writing a package that makes use of ggiraph and ggplot2, more precisely of the `update_geom_defaults()` function of ggplot2.

This function requires a `Geom` object as its first argument. For the moment, I use

```r
update_geom_defaults(ggiraph:::GeomInteractiveBar, ...)
``` 

but I would prefer not using `:::` in my package as it creates a NOTE during the CRAN check.

Would it be possible for you to export the GeomInteractive objects from ggiraph ?

**Comment by davidgohel** [comment]
Agree, using `:::` is not allowed if you want to go on cran.

I am planning to modify theses later. I would have to export all Geom and document them!!! noooo. What do you want to do exactly? Can you share on github?

**Comment by Tutuchan** [comment]
Sorry about the hassle, I can make a PR if you'd like !

This is basically what I want to do:

```r
init_theme = function(...) {
  ggplot2::update_geom_defaults("bar",  list(fill = "red", colour = "white"))
  ggplot2::update_geom_defaults("line", list(colour = "red"))

  # same for ggiraph but with :::
  update_geom_defaults(ggiraph:::GeomInteractiveBar,  list(fill = "red", colour = "white"))
  update_geom_defaults(ggiraph:::GeomInteractiveLine, list(colour = "red))
}
```

This allows me to call the `init_theme()` function at the start of a .Rmd and have all the plots with these values.

**Comment by davidgohel** [comment]
OK, I will see how to export that later. It seems I don't have to document them

**Comment by davidgohel** [comment]
(j'espère que tu n'es pas pressé, désolé ;) - j'ai pas le temps en ce moment mais j'essayerai de le trouver la semaine pro)

**Comment by Tutuchan** [comment]
Pas de souci, c'est un package interne, il n'ira jamais sur le CRAN donc je suis pas pressé :)
