### ISSUE TITLE
geofacet + ggiraph ?

### ISSUE THREAD

**Issue by mtmx** [davidgohel/ggiraph#63]
Thanks again David for your awesome package.
It would be great if geom_*_interactive functions were compatible with geofacet (https://github.com/hafen/geofacet) ?

By now this instruction :

```
my_gg <- ggplot(state_unemp, aes(year, rate)) +
  geom_line_interactive(aes(tooltip = rate), size = 2) +
  facet_geo(~ state, grid = "us_state_grid2") +
  scale_x_continuous(labels = function(x) paste0("'", substr(x, 3, 4))) +
  ylab("Unemployment Rate (%)")
ggiraph(code = print(my_gg) )
```

causes this error :
`Error in grid.newpage() : svgd only supports one page`

**Comment by davidgohel** [comment]
You're welcome.

The issue here is that geofacet is calling indirectly `grid.newpage()`. These create a new device.

You can better understand what is really happening with the following code:

```
pdf(file = "ddd.pdf")
print(my_gg)
dev.off()
```

See ddd.pdf, it contains a blank page and the expected page.
