### ISSUE TITLE
Tooltip into a modal window

### ISSUE THREAD

**Issue by Rozenn** [davidgohel/ggiraph#67]
Hello,

I'am using ggiraph to display graph into a modal window. But, tooltip are not display because of the z-index.
I found here (https://github.com/twbs/bootstrap/issues/5014) that the issue can be resolved by pushing a higher z-index.

Manually, I change the z-index and it looks that it's working (tooltip is displayed). But how can I change this in the ggplot function directly ? I try to use "tooltip_extra_css' to change this value but it's adding another z-index in addition to the current z-index:999.

![tooltip_help1](https://user-images.githubusercontent.com/6977122/28630243-0cc1ab9c-722a-11e7-8cdd-c48d3057fd8c.png)
![tooltip_help2](https://user-images.githubusercontent.com/6977122/28629821-c470ac72-7228-11e7-86f0-af3253de02bd.png)

Thanks in advance,

Rozenn

**Comment by davidgohel** [comment]
Hi Rozenn,

I added argument `tooltip_zindex` so that you can define its value.

++
David
