### ISSUE TITLE
error when loading ggiraph

### ISSUE THREAD

**Issue by dmusick** [davidgohel/ggiraph#68]
Hello...
When attempting to load the ggiraph package, it fails with the message:
namespace 'tibble' is already loaded, but>=1.3.1 is required.  If I attempt lo load the latest 'tibble' from CRAN, I get the error that tibble is installed through ggplot2 and can't be uninstalled.  Any ideas?

regards,
Don Musick
dmusick@genesystech.com

**Comment by davidgohel** [comment]
yes, 

use argument `force=TRUE` when using function `install.packages`.

**Comment by davidgohel** [comment]
excuse me, `force=TRUE` does not exist...

I would start from a fresh R session and use `update.packages`.

**Comment by dmusick** [comment]
I used the force=TRUE argument for ggiraph as well as tibble and it appears that both loaded ok.  However, when I try to set library(ggiraph) I get the same message of "tibble is already loaded but >=1.3.1 is required.  If I type in the console ?tibble, I get a message in the help panel that tibble.rdb is corrupt.  Thoughts?

**Comment by davidgohel** [comment]
Can you try update.packages from a fresh new r session?

**Comment by dmusick** [comment]
scratch the last post.  Restarted R session and ggiraph loaded fine.  Thanks!

**Comment by davidgohel** [comment]
Cool, thanks
