### ISSUE TITLE
font config error: unable to match font pattern

### ISSUE THREAD

**Issue by dmusick** [davidgohel/ggiraph#69]
Hello David....
When generating an interactive bar plot in shiny, the plot does not appear and the message above appears in it's place.  I've read through the message thread in closed issues and have installed homebrew, then cairo and finally devtools with the same error.  Using Mac OSX Sierra 10.12.4.

**Comment by dmusick** [comment]
sorrry.... I meant gdtools

**Comment by dmusick** [comment]
Hello David...
Following Christian Jacksons adivce:

1. Install homebrew. Follow internet instructions.
2. From terminal type: "brew install cairo"
3. In R type: install.packages("gdtools").... note the gdtools package is from git_hub(davidgohel/gdtools)
4. the error we've all been talking about disappeared after this.

In the R console, the following error occured:

Warning in runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
Warning: Error in runHook: lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/gdtools/R/gdtools.rdb' is corrupt
Stack trace (innermost first):
    96: <Anonymous>
    95: stop
    94: value[[3L]]
    93: tryCatchOne
    92: tryCatchList
    91: tryCatch
    90: getNamespace
    89: asNamespace
    88: getExportedValue
    87: ::
    86: match.fun
    85: lapply
    84: validate_fonts
    83: dsvg
    82: ggiraph
    81: func [#25]
    80: origRenderFunc
    79: output$Bar1
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>
Warning in runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
Warning: Error in runHook: lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/gdtools/R/gdtools.rdb' is corrupt
Stack trace (innermost first):
    96: <Anonymous>
    95: stop
    94: value[[3L]]
    93: tryCatchOne
    92: tryCatchList
    91: tryCatch
    90: getNamespace
    89: asNamespace
    88: getExportedValue
    87: ::
    86: match.fun
    85: lapply
    84: validate_fonts
    83: dsvg
    82: ggiraph
    81: func [#25]
    80: origRenderFunc
    79: output$Bar1
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>

Any Ideas?

**Comment by davidgohel** [comment]
Close and restart R session.

**Comment by dmusick** [comment]
Hello again David....Here's the new error after restarting R:

Warning: Error in DSVG_: function 'gdtools_RcppExport_validate' not provided by package 'gdtools'
Stack trace (innermost first):
    84: DSVG_
    83: dsvg
    82: ggiraph
    81: func [#25]
    80: origRenderFunc
    79: output$Bar1
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>

When the shiny app launches, it is visible in the viewer with the same message of DSVG error, however when I slect 'view in browser', the browser briefly appears (but grayed out) then R crashes (presumably due to the DSVG error).

Any guidance would be greatly appreciated.

**Comment by davidgohel** [comment]
OK.

Sorry. There has been a change of Rcpp's version used to compile GitHub's version. Could you install gdtools from CRAN? It should be easy now you re-installed Cairo and all dependencies.

1. Close all R sessions
2. Open a new R session.
3. run `install.packages("gdtools")`

It should be OK then.

David

**Comment by dmusick** [comment]
Hi David....
Ok, I've reinstalled gdtools, but once again have the error "font config error: unable to match font pattern".  Oddly, running sys_font prior to this reinstall of gdtools showed a ton of installed fonts, but after the reinstall it shows none.  Do I need to install Cairo again manually?

regards,
Don

**Comment by dmusick** [comment]
Hi David...
I installed Cairo again manually, and the command prompt warned that it was already installed.  Again, using sys_fonts() shows no fonts installed and of course I get the same "unable to match font pattern" error.  Any ideas?

**Comment by davidgohel** [comment]
I think your cairo needs to be reinstalled even if it says it is already install. Let's start again

Close all R sessions.

In a terminal, run the 3 following commands.

```
brew update
brew upgrade
brew reinsall cairo
```


Start a new R session and run

```
sessionInfo()
devtools::install_github("davidgohel/gdtools") 
devtools::install_github("davidgohel/rvg")
devtools::install_github("davidgohel/ggiraph")
```

**Comment by dmusick** [comment]
Woo hoo!  That did the trick... thanks a bunch David!!

**Comment by ghoshCoder** [comment]
Hi David,
I am getting an error for the following lines of code.
Running rstudio on linux. Any help would be much appreciated.
Also, wondering if the gdtools package uses the fonts.conf under the library/gdtools/fontconfig directory?

Shubhro

`library(ReporteRs)
doc <- pptx()
doc <- addSlide( doc, slide.layout = "Title and Content" )
doc <- addPlot(doc, fun= function() plot(1))`

`doc <- addPlot(doc, fun= function() plot(1)) Error in dml_pptx(file = filename, width = width, height = height, offx = offx,  :    unused arguments (fontname_serif = fontname_serif, fontname_sans = fontname_sans, fontname_mono = fontname_mono, fontname_symbol = fontname_symbol, next_rels_id = next_rels_id)
`

**Comment by davidgohel** [comment]
Hi

I need `sessionInfo()` just in case of.

> Also, wondering...

yes:
https://github.com/davidgohel/gdtools/blob/master/R/load.R#L2

**Comment by ghoshCoder** [comment]
Thanks for the prompt reply.
session info given below

`R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.4 (Maipo)

Matrix products: default
BLAS: /opt/microsoft/ropen/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
 [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ReporteRs_0.8.6      ReporteRsjars_0.0.2  gdtools_0.1.6        readxl_1.0.0        
[5] RevoUtils_10.0.6     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] zip_1.0.0         Rcpp_0.12.13      cellranger_1.1.0  compiler_3.4.2   
 [5] plyr_1.8.4        bindr_0.1         R.methodsS3_1.7.1 R.utils_2.3.0    
 [9] base64enc_0.1-3   tools_3.4.2       digest_0.6.12     uuid_0.1-2       
[13] tibble_1.3.4      gtable_0.2.0      pkgconfig_2.0.1   png_0.1-7        
[17] rlang_0.1.2       shiny_1.0.5       yaml_2.1.14       bindrcpp_0.2     
[21] rJava_0.9-9       officer_0.1.8     dplyr_0.7.4       xml2_1.1.1       
[25] knitr_1.14        grid_3.4.2        glue_1.2.0        R6_2.2.0         
[29] rvg_0.1.6         ggplot2_2.2.1     purrr_0.2.2       magrittr_1.5     
[33] scales_0.5.0      htmltools_0.3.5   assertthat_0.1    xtable_1.7-4     
[37] mime_0.3          colorspace_1.2-6  httpuv_1.3.5      lazyeval_0.2.0   
[41] munsell_0.4.2     R.oo_1.20.0      
`

**Comment by ghoshCoder** [comment]
I see the fonts.conf under the library/gdtools/fontconfig has windows paths. Should I just copy the fonts.conf from /etc/fonts/fonts.conf into library/gdtools/fontconfig ?

**Comment by davidgohel** [comment]
Ohhh

just re-read your message. You are on the wrong thread, here is about `ggiraph`. You are having an issue with `ReporteRs`. 

> unused arguments (fontname_serif = fontname_serif, fontname_sans = fontname_sans, fontname_mono = fontname_mono, fontname_symbol = fontname_symbol, next_rels_id = next_rels_id)

You need to update `ReporteRs` (cran version is `0.8.8`) and `rvg`.

**Comment by davidgohel** [comment]
@ghoshCoder Don't do anything with `fonts.conf`, it has nothing to do with the error you reported :)

**Comment by ghoshCoder** [comment]
Thanks. Which version of rvg? the latest?

**Comment by davidgohel** [comment]
@ghoshCoder yes

**Comment by ghoshCoder** [comment]
Thanks that worked
