### ISSUE TITLE
Support for multiple hover effects

### ISSUE THREAD

**Issue by bhaskarvk** [davidgohel/ggiraph#7]
Is it possible to integrate https://ianlunn.github.io/Hover/, for multiple hover effects, I tried using some of the CSS in it directly in hover_css var, but no go.
It would be awesome to have an array of css effects to chose from. may be include the css in the package and add hover_class parameter in the ggiraph function

**Comment by davidgohel** [comment]
Hi,

I am going to write a vignette about customizing hover effects (and tooltips).
