### ISSUE TITLE
tooltip persists when deleting the graph from shiny 

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/ggiraph#70]
[...]

I created graphs with tooltips. When I display a tooltip on the graph and then remove the renderUI in which the graph was to replace by another element, the tooltip remains and filled the page as you can see on the attach files (IMG1). Therefore, I cannot click on buttons because of the tooltip. It's quite annoying because it obstructs all reactives elements. I tried exactly the same app but with older versions of ggiraph (0.3.2) and everything is fine with this version, I don't have the problem (IMG2 : the tooltip is at the bottom of the webpage).
![img1_issue](https://user-images.githubusercontent.com/6977122/29448107-546a7276-83f5-11e7-8c08-63a457ff3d7d.png)
![img2_ok](https://user-images.githubusercontent.com/6977122/29448108-546dbc4c-83f5-11e7-975a-537c96b81989.png)

Don't hesitate if you need more information...

Thanks in advance !

Rozenn.

**Comment by davidgohel** [comment]
@Rozenn your issue is here :)

**Comment by davidgohel** [comment]
Hi,

Could you update your package with github version please?

There is now a new js function to delete the tooltip. 

If your ggiraph output id is 'xxx', you can use it from shiny with: 
`session$sendCustomMessage(type = 'xxx_tooltip_remove', message = "xxx")`

Or in javascript with function `tooltip_remove('xxx')`.

**Comment by Rozenn** [comment]
Hi, 

Yes, I tested and it works (before and after deployment). Thanks !

You can close the issue !
