### ISSUE TITLE
resize to fit the page as plotOutput

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/ggiraph#71]
https://stackoverflow.com/questions/45191999/ggiraph-plot-doesnt-resize-to-fit-the-page

@felixgrossmann your issue is here

**Comment by felixgrossmann** [comment]
@davidgohel Thank you! :)

**Comment by davidgohel** [comment]
Hi,

It can not be done because plotOutput redraw the raster plot each time the window is resized. `ggiraph` is an htmlwidget and sizing is specific to each htmlwidget.

Function `ggiraph` is provided with arguments `width_svg` and `height_svg`, these will define the aspect ration. Then you can use argument `width` (0 < width < 1) that will be use to scale size of the plot in the html page. 

If you want it to be non responsive, use `use_widget_size` to force usage of htmlwidget width and height.
