### ISSUE TITLE
Position of pan-zoom in markdown

### ISSUE THREAD

**Issue by mtmx** [davidgohel/ggiraph#72]
Hello David,
In the latest github version of your package, it seems the three pan/zoom options (very useful by the way !) are displayed in the top right corner of the .rmd document, and not in the top right corner of the plot.
Here's an example, am I missing something ?

---
title: "Untitled"
output: html_document
---

```{r ggp,echo=F, message=F, warning=F, fig.width=10,fig.height=10}
library(ggplot2)
library(ggiraph)


dataset = iris
dataset$tooltip = dataset$Species
dataset$clickjs = paste0("alert(\"",dataset$Species, "\")" )

gg_point = ggplot(dataset, aes(x = Sepal.Length, y = Petal.Width,
		color = Species, tooltip = tooltip, onclick = clickjs) ) +
	geom_point_interactive()

ggiraph(code = {print(gg_point)}, zoom_max = 2)
```

.

**Comment by davidgohel** [comment]
Hi,

Thanks

fixed in the github version

**Comment by mtmx** [comment]
Ok thanks !
I'm a bit confused about sizing plots in rmarkdown.
With the same rmd example, how do you change width since "width" is deprecated ? I can't find the vignette about sizing anymore.

**Comment by davidgohel** [comment]
I am too :/ Should be better from now...

`width` is no more deprecated! Update from cran or github (again!).

**Comment by mtmx** [comment]
Magnifique !
