### ISSUE TITLE
making geom_text_interactive labels transparent

### ISSUE THREAD

**Issue by antuki** [davidgohel/ggiraph#78]
Hello [me again... but i love using your packages !]

I would like to add some tooltips to a plot without adding any feature on the plot. My idea was to use geom_text_interactive and then make the label transparent (solution 1) or label="" (solution2). 
Unfortunately both solutions don't work. The label disappears but the tooltip disappears with it too... 

Do you have any solution for me ?

Thank you !

```
data <- data.frame(x=c(1,2,3,4),y=c(2,2,2,2))
# example with tooltip and label
plot <- ggplot(data,aes(tooltip=x)) + geom_text_interactive(aes(x=x,y=y,label="HAHAHA"), color="#000000")
ggiraph(code = {print(plot)})

# solution 1 doesn't work
plot1 <- ggplot(data,aes(tooltip=x)) + geom_text_interactive(aes(x=x,y=y,label="HAHAHA"), color="#00000000")
ggiraph(code = {print(plot1)})

# solution 2 doesn't work
plot2 <- ggplot(data,aes(tooltip=x)) + geom_text_interactive(aes(x=x,y=y,label=""), color="#000000")
ggiraph(code = {print(plot2)})
```

**Comment by davidgohel** [comment]
No sorry, a tooltip can only be displayed if mouse is over an existing element; transparent or empty text is not producing any svg element.

**Comment by antuki** [comment]
OK, too bad! But TY for the answer !
