### ISSUE TITLE
Option to have tooltips follow the cursor

### ISSUE THREAD

**Issue by pelotom** [davidgohel/ggiraph#79]
Currently on bar graphs for example, the tooltip appears near where the cursor enters the bar, but doesn't move from that spot. On larger bars this looks a bit odd because the text is stuck nowhere near the center of the bar and possibly near other bars, making it look ambiguous. It would be nice to have an option to make the tooltip's position follow the cursor continuously wherever it moves.

**Comment by davidgohel** [comment]
Sorry for the delay.

The github version (soon on cran) fix that behavior, the tooltip will now follow cursor.
