### ISSUE TITLE
geom_smooth doesn't work

### ISSUE THREAD

**Issue by kismsu** [davidgohel/ggiraph#8]
Hi, I've noticed that `geom_smooth` function does't work with your package.

```r
library(ggiraph)
mytheme_main <- theme( panel.background = element_blank(), 
                       panel.grid.major = element_line(colour = "#dddddd"), 
                       axis.ticks = element_line(colour = "#dddddd") )

dataset <- mtcars
dataset$tooltip <- row.names(dataset)

gg_point_1 <- ggplot(dataset, aes(x = disp, y = qsec, 
                                  color = wt, tooltip = tooltip ) ) + 
    geom_point_interactive(size=3) + geom_smooth()
    

ggiraph(code = {print(gg_point_1 + mytheme_main)}, width = 7, height = 6)

```

returns a chart wit no smoothing line.

I've tried to find where does it brake the only thing I can tell is that

```r
 ggplot(dataset, aes(x = disp, y = qsec, 
                                  color = wt, tooltip = tooltip ) ) + 
    geom_point(size=3) + geom_smooth()
```

doesn't work, but the following does

```
 ggplot(dataset, aes(x = disp, y = qsec, 
                                  color = wt) ) + 
    geom_point(size=3) + geom_smooth()
```

**Comment by davidgohel** [comment]
A workaround is to specify `tooltip` in the aes of `geom_point_interactive`

```
library(ggiraph)
mytheme_main <- theme( panel.background = element_blank(), 
                       panel.grid.major = element_line(colour = "#dddddd"), 
                       axis.ticks = element_line(colour = "#dddddd") )

dataset <- mtcars
dataset$tooltip <- row.names(dataset)

gg_point_1 <- ggplot(dataset, aes(x = disp, y = qsec, 
                                  color = wt ) ) + 
  geom_point_interactive(aes(tooltip = tooltip), size=3) + geom_smooth()


ggiraph(code = {print(gg_point_1 + mytheme_main)}, width = 7, height = 6)
```

**Comment by davidgohel** [comment]
Hi,

This is not a bug, this is geom_smooth behavior.

`aes` elements are used a *x variables*:

    library(ggplot2)
    ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, tooltip = Species ) ) + 
      geom_smooth() +
      geom_point(size=3) + labs(title="enough data per group")

![rplot3](https://cloud.githubusercontent.com/assets/4331618/13496113/c4ed41b8-e14e-11e5-8c3b-ede216d5d748.png)

    iris$rowid <- paste0("dummy", seq_len(nrow(iris)) )
    ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, dummy = rowid ) ) + 
      geom_smooth() +
      geom_point(size=3) + labs(title="not enough data per smooth!")
    
![rplot2](https://cloud.githubusercontent.com/assets/4331618/13496120/c962072e-e14e-11e5-8135-93d529bd1ebe.png)
