### ISSUE TITLE
Size differences between ggplot ggiraph

### ISSUE THREAD

**Issue by f-leborgne** [davidgohel/ggiraph#81]
Hello,

I just tried to use the ggiraph package in order to add tooltip on a ggplot graph. It seems to me very promising except I have one major issue : all the objects for which I specified a size (geom_text, geom_rect, panel.grid.minor.y) appears largely bigger in ggiraph (in google chrome) than in standard ggplot (in R). An example of my plot is in the attached file.
Of course I could manually reduce the size of all the objects but it would be more comfortable if the size remained the same. It is possible to do this automatically ? 

Thanks a lot

Best regards
Florent

[example.zip](https://github.com/davidgohel/ggiraph/files/1463849/example.zip)

**Comment by davidgohel** [comment]
The result is responsive. If displayed as you do, it will use the width of the page. If in a rmarkdown or shiny, it will fit into its container (usually a div). 

You could use an rmarkdown doc instead of savehtmlwidget. 

There are also options to fix width and height of the widget (see the help page of ggiraph)

**Comment by f-leborgne** [comment]
I think I misspoke, I have no problem with the global size of the plot that I fix with width and height parameters of the ggiraph function. My problem is for a plot of the same global width in R and in google chrome (half of my screen for example) in google chrome the label of the x-axis are largely bigger than in R and then overlap. In other words I have on my screen two plots of the same global size (one in R one in GG) but on which the text is very different in size !
I attached a screenshot where you can see the rendering differences.

Thanks 

Best regards
Florent
![screenshot](https://user-images.githubusercontent.com/32433180/32720042-a74df254-c862-11e7-983c-95a8f645f61f.JPG)

**Comment by davidgohel** [comment]
You do not compare same things. First is an *on screen* device, second is an *svg device*. If you want the same rendering, use fonts, point size, width and height. 

You will probably meet the same issue with pdf, svglite, png...
Good luck, this is not that easy.
