### ISSUE TITLE
Geom_polygon margins

### ISSUE THREAD

**Issue by smitsrr** [davidgohel/ggiraph#85]
I am creating a geom_polygon_interactive and am having issues with the size of the margins around the size of the plot.  I looked over Issue [#50](https://github.com/davidgohel/ggiraph/issues/50) and was unable to resolve the size issues. I reproduced the error and was able to alleviate it by not using `coord_map("polyconic")`. 

However, I feel the polyconic projection is a better map projection and it would be nice to include it in my visualization. 

Thanks for the great package otherwise! I had been attempting to use the nearPoints feature, but that also doesn't deal well with the polyconic projection. 

Here is a small sample of what I did to demonstrate the issue:

```
library(ggplot2)
library(mapdata)
library(shiny)
library(data.table)
library(ggiraph)

map.county <- map_data('county')
counties<- data.table(map.county)

ui <- fluidPage(
  
  # Application title
  titlePanel("ggiraph plot margins"),
fluidRow(column(6,
                div(style="width:900px;height:700px;", 
                    ggiraphOutput("county_map"))
                ),
         column(6,
                div(style="width:900px;height:700px;", 
                    ggiraphOutput("county_map_all")))
  )
)

server <- function(input, output) {
  output$county_map<- renderggiraph({
    p<- ggplot(counties, aes(x=long, y=lat, group = group)) +
      # coord_map("polyconic" ) +  # comment or uncomment this line to see the changes
      theme(plot.margin = unit(c(.1,.1,.1,.1), "cm")) + 
      geom_polygon_interactive(aes(tooltip = subregion))
    
    ggiraph(code = {print(p)},width = 1, height = 5.418)
  })
  
  output$county_map_all<-renderggiraph({
  # just two states
  p<- ggplot(counties[counties$region %in% c("alabama", "georgia"),], aes(x=long, y=lat, group = group)) +
    # coord_map("polyconic" ) +  # comment or uncomment this line to see the changes
    theme(plot.margin = unit(c(.1,.1,.1,.1), "cm")) + 
    geom_polygon_interactive(aes(tooltip = subregion))
  ggiraph(code = {print(p)},width = 1, height = 5.418)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by davidgohel** [comment]
I have 2 comments: 

`ggiraph` has no height parameter. 

Is this code intentional? You specified a 6 column width element (6/12 -> 50%) and then you fixed "width:900px;height:700px;".

```
column(6,
                div(style="width:900px;height:700px;", 
                    ggiraphOutput("county_map_all")))
```


I don't see any issue to fix, maybe I misunderstood something. Could you close the issue?

**Comment by davidgohel** [comment]
Hi,

Sorry, closing that, I don't understand the issue to fix (margins are managed by ggplot not by ggiraph and I can't see any issue when running your example).

**Comment by smitsrr** [comment]
My apologies for not responding earlier. I was able to reproduce the issue I was having. If I don't set the map equal to "polyconic", it's mostly fine, but I much prefer that projection. 

This is what is produced when the maps are set to polyconic:
![margins](https://user-images.githubusercontent.com/8473398/34644567-4c27a9f6-f2f6-11e7-8d67-1c778ffad504.JPG)

As opposed to having that line commented out:
![margins_2](https://user-images.githubusercontent.com/8473398/34644593-dbc859fc-f2f6-11e7-8b29-ae25f07414de.JPG)

The latter margins are more appealing to the eye, but I prefer the polyconic projection. 

Here's my edited code:
```
library(ggplot2)
library(mapdata)
library(shiny)
library(data.table)
library(ggiraph)

map.county <- map_data('county')
counties<- data.table(map.county)

ui <- fluidPage(
  
  # Application title
  titlePanel("ggiraph plot margins"),
  fluidRow(column(6,
                  ggiraphOutput("county_map")), 
          column(6,
                 ggiraphOutput("county_map_all"))
  )
)

server <- function(input, output) {
  output$county_map<- renderggiraph({
    p<- ggplot(counties, aes(x=long, y=lat, group = group)) +
      coord_map("polyconic" ) +  # comment or uncomment this line to see the changes
      theme(plot.margin = unit(c(.1,.1,.1,.1), "cm")) + 
      geom_polygon_interactive(aes(tooltip = subregion))
    
    ggiraph(code = {print(p)},width = 1)
  })
  
  output$county_map_all<-renderggiraph({
    # just two states
    p<- ggplot(counties[counties$region %in% c("alabama", "georgia"),], aes(x=long, y=lat, group = group)) +
      coord_map("polyconic" ) +  # comment or uncomment this line to see the changes
      theme(plot.margin = unit(c(.1,.1,.1,.1), "cm")) + 
      geom_polygon_interactive(aes(tooltip = subregion))
    ggiraph(code = {print(p)},width = 1)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by davidgohel** [comment]
Hi

As I said, margins are managed by `ggplot2`, not by `ggiraph`. Maybe you can play with arguments `width_svg,height_svg` - see http://davidgohel.github.io/ggiraph/reference/ggiraph.html#arguments
