### ISSUE TITLE
doc_parse_file: internal error: Huge input lookup [1]

### ISSUE THREAD

**Issue by dm3ll3n** [davidgohel/ggiraph#87]
I get this error when using ggiraph in Shiny. I am attempting to plot just over 50,000 points with `geom_point_interactive` but am unable to do so due to the `Huge input lookup` error. The same dataset will plot if I include a facet. It appears to occur in the call to `read_xml`.

A quick google of the error lead me here:
https://stackoverflow.com/questions/27452140/parsing-xml-into-an-r-data-frame

```
Warning: Error in doc_parse_file: internal error: Huge input lookup [1]
Stack trace (innermost first):
    85: <Anonymous>
    84: stop
    83: doc_parse_file
    82: read_xml.character
    81: read_xml
    80: ggiraph
    79: postProcessPlot...
    78: func..
    77: origRenderFunc
    76: output$trends_plot
     1: runApp
```

**Comment by davidgohel** [comment]
I can't reproduce your issue on my machine:

```
library(ggiraph)
library(ggplot2)
np <- 50000
x <- data.frame(x = rnorm(np), 
                y = rnorm(np), 
                tooltip = sample(letters, size = np, replace = TRUE), 
                stringsAsFactors = FALSE )
zz <- ggplot(data = x, aes(x=x,y=y,tooltip = tooltip)) + geom_point_interactive()
ggiraph(ggobj = zz)

```

But your diagnostic should be correct, xml2 have options to avoid that error:

https://github.com/r-lib/xml2/blob/master/R/xml_parse.R#L93

Even if I add an option for that, I am afraid you will get troubles when displaying the plot:

1. 50 000 points are likely to be too dense to show something from the data (*big potatoe* effect)
2. I have trouble displaying the output in a browser (too much element too render)

David

**Comment by dm3ll3n** [comment]
50,000 points is a lot, but it is possible to draw insights with the right alpha level. When trying to construct an example to reproduce the error, it became clear that it occurs when specifying both the tooltip and the data_id.

This should reproduce it:

```r
library(ggiraph)
library(ggplot2)

np <- 50000

x <- data.frame(x = rnorm(np), 
	y = rnorm(np),
	id = 1:np,
	stringsAsFactors = FALSE )

x$tooltip <- sprintf("(%s)", paste(x$x, x$y, sep = ', '))

zz <- ggplot(data = x,
		aes(x=x,y=y, tooltip = tooltip, data_id = id)) +
	geom_point_interactive(alpha=0.1, size=2)
	
ggiraph(ggobj = zz, zoom_max = 5, selection_type = 'multiple',
				width_svg = 10, height_svg = 10)
```

**Comment by davidgohel** [comment]
OK, your choice :)

I can reproduce now, thanks.

**Comment by jamesdalg** [comment]
I'm getting the same issue. I'm trying to create a heatmap with detailed tooltips.

**Comment by jamesdalg** [comment]
data <- read_xml( path ,options="HUGE") is the solution that worked for me. It allows large parsing of xml.

**Comment by davidgohel** [comment]
You can now use argument `xml_reader_options` with value `list(options = "HUGE")`.

This will create the interactive graphic but the rendering will be very slow and may be difficult to share with *low ressource* machines !
