### ISSUE TITLE
trouble installing ggiraph and rvg.

### ISSUE THREAD

**Issue by CRG180** [davidgohel/ggiraph#88]
I'm new to R programming and even newer to github.  I have had trouble installing and loading both ggiraph and rvg in Rstudio. I'm using a Mac with High Sierra and R version 3.4.3 (2017-11-30).  **When I install ggiraph or rvg I get the following code:**

> install.packages("ggiraph")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/ggiraph_0.4.2.tgz'
Content type 'application/x-gzip' length 270284 bytes (263 KB)
==================================================
downloaded 263 KB

The downloaded binary packages are in
	/var/folders/yh/_1jcbf2s3c93_mhgsnlkyrkm0000gn/T//RtmpnqdxmC/downloaded_packages

**When I try and load the package I get the following code:**

> library(ggiraph)
Error: package or namespace load failed for ‘ggiraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found

I've been successful with almost every other package minus rjava so far.  I'm having trouble figuring this one out. Any help would be great thank you.

**Comment by davidgohel** [comment]
Hi,

Could you try to re-install cairo first? Close all your R sessions then run the following commands from a terminal:

```
brew update
brew upgrade
brew reinsall cairo
```

**Comment by CRG180** [comment]
David,
Thanks for the response.  I found I was having the same problem as mentioned above with Cairo.  I figured out I needed to install XQuartz at https://www.xquartz.org/ .  I may have done this in the past but I needed to reinstall it after I destroyed my hard drive during a bad install of high sierra.  Thanks, I look forward to using the package!! 

Charles

**Comment by Jeremieauger** [comment]
Thanks @CRG180 :) Installing XQuartz solved it for me!

**Comment by jalozanocampo** [comment]
Thanks @CRG180 Installing XQueartz Solved it for me too!

**Comment by solomondaner** [comment]
I am having the same error (shown below) for gdtools and rvg on my macbook pro. Both of them work fine on my windows laptop. I tried to run the comman brew update on my terminal but it gives me the following error : Error: unexpected symbol in "brew update" 

Error: package or namespace load failed for ‘gdtools’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
 dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
 Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
 Reason: image not found

**Comment by davidgohel** [comment]
The instructions described at the link below should help

https://github.com/davidgohel/gdtools#for-mac-os-users

**Comment by solomondaner** [comment]
Thank you it worked.
