### ISSUE TITLE
Can't run a simple example

### ISSUE THREAD

**Issue by AJABADI** [davidgohel/ggiraph#89]
Hi, 
I just found out about ggiraph and was excited to try to use it in my code for a reactive plot but when I run a simple example, R shows "busy" and never stops, unless I force stop it which used to produce an "Unexpected termination" error but I updated all the packages again and it doesn't even show that anymore.

I run R 3.3.3 x64 on Windows 10 using Rstudio
Following is the code I try to run:
`# ggiraph simple example -------
library(ggplot2)
library(ggiraph)

# create dataset
dataset = mtcars
dataset$carname = row.names(mtcars)

# plots
gg_point = ggplot(
  data = dataset,
  mapping = aes(x = wt, y = qsec, color = disp,
                tooltip = carname, data_id = carname) ) +
  geom_point_interactive() + theme_minimal()

ggiraph(ggobj = gg_point, width = .7 )`

Thanks

**Comment by AJABADI** [comment]
Found the probelm:
https://stackoverflow.com/questions/48889846/r-ggiraph-no-plot-when-running-r-file

**Comment by davidgohel** [comment]
I dont think it is related. The first time you install gdtools, it needs to
create an index file for all the system fonts. You just have to wait once
and then its ok
