### ISSUE TITLE
Clipping implementation 

### ISSUE THREAD

**Issue by mattmills49** [davidgohel/ggiraph#9]
I've noticed that if the facet labels or the title exceeds the width of the graph output the text just won't show. 

    mtcars$facet_var <- ifelse(mtcars$am == 1, "This Facet Label Is Way Too Long", "none")
    good_plot <- ggplot(aes(x = hp, y = mpg), data = mtcars) +
      geom_point() +
      facet_wrap(~facet_var, ncol = 2) +
      ggtitle("Another unnecessarily Long Title to use") +
      theme(strip.text = element_text(face = "bold", size = 14))
    
    ggiraph(code = print({good_plot}), width = 6)

The facet label is fine when the width is 6 but cuts off when the width is shorter:

    ggiraph(code = print({good_plot}), width = 3)

Is there a way for the rendering to just get cut off the extra characters like `ggplot2` does?

**Comment by davidgohel** [comment]
Yes, this is because clipping is not yet managed in `rvg`.
