### ISSUE TITLE
geom_bar_interactive displays NA values in tooltip when using position "dodge"

### ISSUE THREAD

**Issue by CRG180** [davidgohel/ggiraph#90]
I'm running into a problem with `ggiraph`.  Most of the bars when using the tooltip appear as NA values.  I want the tooltip to display the sum of `disp` for each `as.factor(gear)` by every `as.factor(cyl)` using the `position = "dodge"` in `geom_bar_interactive`.  The picture below is a screenshot of my cursor over one of the bars.  The tooltip output = NA.  Note I'm using `mtcars` as dummy data. Therefore, the graph may not make a whole lot of sense practically. 

```{r}
library(ggplot2)
library(ggiraph)

d7 <-ggplot(data = mtcars, aes(x= as.factor(cyl), y= disp)) +
  labs(title = "Total Disp by Cyl and Gear",
       subtitle = "Cars for fun",
       x = "Cyl", y = "Disp") +
  guides(fill=guide_legend(title="Gear")) +
  scale_fill_manual(values =  c(`3` = "#f7831d",`4` = "#ef1cd0",`5` = "#0036f9"), na.value = "black")

my_gg5 <- d7+geom_bar_interactive(aes(tooltip = disp , data_id =as.factor(cyl), 
fill = as.factor(gear)), 
color = "black", stat="summary", fun.y ="sum", position = "dodge")

ggiraph(code = print(my_gg5),hover_css = "fill:green")
```
![ggirph screen shot](https://user-images.githubusercontent.com/33331944/36993328-2ad45a1a-2073-11e8-9ac2-9a9863fd3a8d.png)

**Comment by davidgohel** [comment]
I think the issue here is related to the fact you are using `stat="summary", fun.y ="sum"`. `disp` should also be summarized but there is no implemented mechanism for that (stat only apply to y). 

```
library(ggplot2)
library(ggiraph)
library(dplyr)

dat <- mtcars %>% 
  mutate(cyl = as.factor(cyl), gear = as.factor(gear) ) %>% 
  group_by(cyl, gear) %>% 
  summarise(disp = sum(disp, na.rm = TRUE))

d7 <-ggplot(data = dat, aes(x= cyl, y= disp, fill = gear, group = gear)) +
  geom_bar_interactive(aes(tooltip = disp), color = "black", stat="identity", position = position_dodge())


ggiraph(code = print(d7), hover_css = "fill:green")
```

**Comment by CRG180** [comment]
David thank you! Very helpful.

Charles
