### ISSUE TITLE
can't resize ggiraph in notebook

### ISSUE THREAD

**Issue by ChristelSwift** [davidgohel/ggiraph#92]
hi there,
i noticed plots produced with ggiraph in notebook have a wide margin to the left, which is not the case with simple ggplot.  

I tried to adjust the plot size in the chunk definition using fig.width / fig.height but neither had any effect.
see the difference between these 2 chunks:

    ```{r fig.height=4}
    zz <- ggplot(diamonds, aes(carat, tooltip = ..count..)) + geom_histogram_interactive()    
    ggiraph(ggobj = zz)
    ```
    ```{r message=FALSE, fig.height=4}
    ggplot(diamonds, aes(carat)) + geom_histogram() 
    ```
Is there a way to force ggiraph to behave like ggplot, ie reduce the margin to the left?

many thanks!

**Comment by davidgohel** [comment]
Hi

ggiraph is an *htmlwidget* and is not a simple image. That's why the behavior can be different.

This help page should answer your questions: https://davidgohel.github.io/ggiraph/reference/ggiraph.html#widget-sizing.

David
