### ISSUE TITLE
Feature request: Crosstalk (SharedData) integration

### ISSUE THREAD

**Issue by andbarker** [davidgohel/ggiraph#93]
I really like the simplicity (and consistency) of ggiraph outputs - especially compared to plotly/ggplotly.  Are there any plans to extend ggiraph to accept SharedData sources for crosstalk brushing/filtering?

I understand that ggiraph is a htmlwidgets package, which is one of the key requirements:
https://rstudio.github.io/crosstalk/authoring.html

**Comment by davidgohel** [comment]
There is no plan as `ggiraph` does not seem to fit Crosstalk requirements:

[0] Operates on data frames, or data frame-like objects
[X] Displays individual rows/observations/data points
[X] Supports highlighting/fading and hiding/showing of data points
[X] Provides a gesture for selecting data points, and API for dismissing selection

As I understand things, the htmlwidget needs **one input** data.frame to be shared across different htmlwidgets but `ggiraph` input is a `ggplot` object (which can contain several data.frame) not a single data.frame. 

That said, ggiraph already support: 

[X] Displays individual rows/observations/data points
[X] Supports highlighting/fading and hiding/showing of data points
[X] Provides a gesture for selecting data points, and API for dismissing selection

So if you want to use a selection, it is available in a reactive value...

**Comment by andbarker** [comment]
Fair enough.
I'll have to look further into the highlighting and fading functions.
Thanks for the quick response - and thanks for creating such a great package.
