### ISSUE TITLE
Incapable d'obtenir ggiraph

### ISSUE THREAD

**Issue by inesmercier** [davidgohel/ggiraph#94]
Bonjour, 
Je tente d'installer ggiraph mais en suis incapable. Voici ce que j'ai fait : 

> install.packages("devtools")
essai de l'URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/devtools_1.13.5.tgz'
Content type 'application/x-gzip' length 439289 bytes (428 KB)
==================================================
downloaded 428 KB

The downloaded binary packages are in
	/var/folders/c6/qczxp5bn2zb2th__gbj9nh8h0000gn/T//RtmpBpkECe/downloaded_packages

> devtools::install_github('davidgohel/ggiraph')
Downloading GitHub repo davidgohel/ggiraph@master
from URL https://api.github.com/repos/davidgohel/ggiraph/zipball/master
Installing ggiraph
'/Library/Frameworks/R.framework/Resources/bin/R'  \
  --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/c6/qczxp5bn2zb2th__gbj9nh8h0000gn/T/RtmpBpkECe/devtools7c373e604941/davidgohel-ggiraph-1942555'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘ggiraph’ ...
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  impossible de charger l'objet partagé '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found
ERROR: lazy loading failed for package ‘ggiraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ggiraph’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ggiraph’
Installation failed: Command failed (1)

Êtes-vous en mesure de m'aider ? 
Bonne journée 
Inès

**Comment by SamGG** [comment]
Bonjour Ines,
a) pour une plus large audience, poste tes questions en anglais
b) en lisant les messages d'erreur, avec un peu d'habitude, tu verras qu'en ggiraph ne peut s'installer parce qu'il manque le package gdtools (ou que R n'est pas arrivé à l'installer au moment voulu)
Donc, essaie d'installer gdtools, et si l'installation est OK, alors réessaie ggiraph.
Si gdtools ne s'installe pas, vois les erreurs possibles comme https://github.com/davidgohel/gdtools/issues/24
La 1ere action à tenter est de coller le message d'erreur dans un moteur de recherche.
Bon courage.

**Comment by davidgohel** [comment]
@SamGG merci! 

@inesmercier, could you follow my explanations here: https://stackoverflow.com/questions/48199737/cant-install-flextable/48224291#48224291



#88

**Comment by inesmercier** [comment]
@SamGG  @davidgohel 
Thank you so much for your quick response! Sorry for the french i joined GitHub yesterday and am new to R and coding in general for that matter! 
It worked by installing  quartz: https://www.xquartz.org as it was mentioned in the page you told me to look up @davidgohel 

Have a good day 
Inès

**Comment by davidgohel** [comment]
@inesmercier no, I did not say installing quartz. I said to follow my explanations here: https://stackoverflow.com/questions/48199737/cant-install-flextable/48224291#48224291

**Comment by inesmercier** [comment]
@davidgohel yes i know but someone commented that he managed to solve it by installing quartz. 
Is this not a good way to solve my problem ? 

Inès

**Comment by davidgohel** [comment]
I know but I think the correct solution is the one I provided.

**Comment by inesmercier** [comment]
it's done. 
Indeed with your explanations i got no warning messages 
thank you

**Comment by davidgohel** [comment]
cool, thanks for the feedback.
