### ISSUE TITLE
Use marker colour in tooltip

### ISSUE THREAD

**Issue by royfrancis** [davidgohel/ggiraph#95]
Say I have a marker (a point) with a certain colour. Can I capture the colour information from that marker to be used in my tooltip?

As an example, see below from highcharts.
![14quq](https://user-images.githubusercontent.com/5083500/37958741-93774628-31b1-11e8-95dc-9f4f171833b3.png)

**Comment by davidgohel** [comment]
I never thought about this. I don't think it is possible without hacking the htmlwidget. 

That is an excellent suggestion as an improvment.

**Comment by tdeenes** [comment]
Actually it requires only minimal modification in ggiraph if you can assume that bootstrap is loaded. In JS, instead of the ggiraph tooltip, use bootstrap:

```javascript
function set_tooltip(id) {
  $('#' + id + ' *[title]').tooltip({
      trigger: 'hover',
      html: true,
      container: 'body',
      placement: 'auto top'
    });
}
```

Then you can use the 'show.bs.tooltip' event and retrieve whatever attribute of the element which the tooltip belongs to:
```javascript
jQuery(document).ready(function ($) {
    $('body').on('show.bs.tooltip', function (e) {
        //suppose e.target is an SVG point
        var color = e.target.getAttribute("fill");
        console.log('Marker color: ' + color)
    });
});
```

**Comment by davidgohel** [comment]
@tdeenes thanks, that can be useful. But one of the first solved issue was to make the package non-jQuery-dependent.

**Comment by tdeenes** [comment]
Good point, I was not aware of this. Just for the records; [this project](http://thednp.github.io/bootstrap.native/) provides an option for using Bootstrap components without jQuery.

**Comment by davidgohel** [comment]
Sorry for the delay.

The new github version (>=0.5.0) has now new functions: girafe, girafe_options and few helper functions to help specify the animations you want. The code below is demonstrating how to use marker fill color as background color for the tooltip:

```
library(ggplot2)

dataset <- mtcars
dataset$carname = row.names(mtcars)

gg_point = ggplot(data = iris,
    mapping = aes(x = Sepal.Length, y = Petal.Length, color = Species,
                  tooltip = Species, data_id = Species) ) +
  geom_point_interactive() + theme_minimal()

x <- girafe(ggobj = gg_point)
x <- girafe_options(x = x, opts_tooltip(use_fill = TRUE) )
print(x)
```
