### ISSUE TITLE
Foreign characters in tooltip

### ISSUE THREAD

**Issue by rodik** [davidgohel/ggiraph#96]
Hi, I'm having trouble with Eastern European characters in Tooltips. They are replaced by questionmarks (�). Saved HTML plots will also have this issue. Here is a reproducible example:
```{r}
library(ggiraph)
library(ggplot2)

# some data with šđčćž
name <- c("Prvi", "Špičković", "Đidža")
value <- c(1,2,3)
# convert to utf8
name <- enc2utf8(name)
# create data.frame
df <- data.frame(name, value)
# plot
gg_plt <- ggplot(df, aes(x=name, y=value, tooltip = name, data_id = name)) +
  geom_bar_interactive(stat='identity')
# ggiraph
wid <- ggiraph(ggobj=gg_plt)
wid
```
The second and third string will be: �pi�kovi� ... and ... �id�a
My collation settings:

```
> Sys.getlocale()
[1] "LC_COLLATE=Croatian_Croatia.1250;LC_CTYPE=Croatian_Croatia.1250;LC_MONETARY=Croatian_Croatia.1250;LC_NUMERIC=C;LC_TIME=Croatian_Croatia.1250"
```

**Comment by davidgohel** [comment]
Hi, 

Thanks, your code looks valid... I will have a try on a windows computer this week.

**Comment by pvictor** [comment]
Hi,
Maybe it will help, it works fine with `stringi` by converting name to UTF-8 and escaping unicode in tooltip : 

```r
library(ggiraph)
library(ggplot2)

# some data with šđčćž
name <- c("Prvi", "Špičković", "Đidža")
value <- c(1,2,3)
# convert to utf8
name <- stringi::stri_enc_toutf8(name)
# create data.frame
df <- data.frame(name, value)
# plot
gg_plt <- ggplot(df, aes(x=name, y=value, tooltip = stringi::stri_escape_unicode(name), data_id = name)) +
  geom_bar_interactive(stat='identity')
# ggiraph
wid <- ggiraph(ggobj=gg_plt)
wid
```
Result:
![image](https://user-images.githubusercontent.com/4415580/38767508-3aab1ea8-3fe3-11e8-82e3-82a84c3a1fe9.png)

And I'm on Windows too ;)

Victor

**Comment by rodik** [comment]
Thank you. I will use stringi.

**Comment by davidgohel** [comment]
I am closing the issue as @pvictor has provided a nice solution.
