### ISSUE TITLE
geom_hline_interactive, geom_vline_interactive

### ISSUE THREAD

**Issue by nllspc** [davidgohel/ggiraph#97]
Would you be open to a pull request with these two geoms? I have working versions of both. The only problem so far is a warning message, "Warning: Ignoring unknown aesthetics: tooltip". Despite the warning, the tooltip works. Haven't tried onclick or data_id.

**Comment by davidgohel** [comment]
Yes, thank you

Can you make sure it is working with onclick and data_id also?

**Comment by nllspc** [comment]
All three verified as working now

**Comment by davidgohel** [comment]
cool, thank you, send the PR and I will review it this WE (or next week :))

David
