### ISSUE TITLE
click, dblclick, hover and brush events with ggiraph in shiny

### ISSUE THREAD

**Issue by cegbuna** [davidgohel/ggiraph#99]
Thanks for the packages. Makes interaction with `ggplot2 `seamless. 

Is there an option to use the interaction events such as `brush`, `hover `and `click `via `shiny`? I tried using the following code in the `ui `but got the error below. I was hoping `ggiraph `would support these events.

```
ggiraphOutput("plotWOR_COPField", height = 594,
                              click = "plot1_clickField",
                              dblclick = "plot1_dblclickField",
                              hover = "plot1_hoverField",
                              brush = brushOpts(
                                id = "plot1_brushField",
                                resetOnNew = TRUE
                              )
```

`ERROR: unused arguments (click = "plot1_clickField", dblclick = "plot1_dblclickField", hover = "plot1_hoverField", brush = brushOpts(id = "plot1_brushField", resetOnNew = TRUE))`

Thank you.

**Comment by davidgohel** [comment]
Yes, these are features (but arguments you used do not exists...). 

You can have a look here: https://davidgohel.github.io/ggiraph/articles/offcran/using_ggiraph.html#shiny-usage

Or here https://davidgohel.github.io/ggiraph/index.html

KR

**Comment by cegbuna** [comment]
Perfect! Thanks for the quick response.

**Comment by cegbuna** [comment]
David, 

I noticed that when using `geom_smooth` the fit doesn't display when the data_id is specified

**Linear fit doesn't show but selection works because the `data_id`  is specified**
```
output$plot <- renderggiraph({
    p <- ggplot(mtcars, aes(x=wt,y=mpg,data_id = row.names(mtcars))) +
      geom_point_interactive(size = 3) +
      geom_smooth(method = "lm", formula = formula) +
      stat_poly_eq(formula = formula, parse = TRUE) + 
      theme_minimal()
    ggiraph(code = print(p),
            hover_css = "fill:red;cursor:pointer;",
            selection_type = "multiple",
            selected_css = "fill:red;")
})
```
vs.
**Linear fit is shown but selection doesn't work because the `data_id`  isn't specified**

```
output$plot <- renderggiraph({
    p <- ggplot(mtcars, aes(x=wt,y=mpg)) +
      geom_point_interactive(size = 3) +
      geom_smooth(method = "lm", formula = formula) +
      stat_poly_eq(formula = formula, parse = TRUE) + 
      theme_minimal()
    ggiraph(code = print(p),
            hover_css = "fill:red;cursor:pointer;",
            selection_type = "multiple",
            selected_css = "fill:red;")
})
```
Any clues to why this strange behavior occurs?
Thanks again.

**Comment by davidgohel** [comment]
Yes, read #8

**Comment by sebdalgarno** [comment]
Hi David,
Like the original poster I am looking for a way to capture the value of a hover event within a shiny app. I have looked through the resources you linked to but only see a way to access selected values through 'plotly_selected'. Is this possible? I am hoping to link highlighting from girafe plot and leaflet map.

**Comment by davidgohel** [comment]
@sebdalgarno capturing hovering is not an option as it is used only to animate the elements that have an associated id (provided with `data_id` argument in geom functions).

`xxxx_selected` will only contain selected elements (selected with click or lasso selection). 

I am not sure I understand *[...]Like the original poster[...]*. If you are referring to the image that can be seen on the README, it shows click actions, not hover actions.

**Comment by sebdalgarno** [comment]
By 'original poster' I simply meant the person who first opened this issue. Thanks for the great package. If you do not think you will add capture of hover events in the future, I will close this issue

**Comment by davidgohel** [comment]
No problem, you are welcome. You don't need to close the issue, it's been closed few months ago!

That may be implemented in the future, I will give a try in the next development run.
